#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Cyclic redundancy check
#+OPTIONS: num:nil H:2


* Overview
Cyclic Redundancy Check循环冗余检验，是基于数据计算一组效验码，用于核
对数据传输过程中是否被更改或传输错误。
* The Basic Idea Behind CRC Algorithms
The basic idea of CRC algorithms is simply to treat the message as an
enormous binary number, to divide it by another fixed binary number,
and to make the remainder from this division the checksum. Upon
receipt of the message, the receiver can perform the same division and
compare the remainder with the "checksum" (transmitted remainder).
* Binary Arithmetic with No Carries
Adding two numbers in CRC arithmetic is the same as adding numbers in
ordinary binary arithmetic except there is no carry. This means that
each pair of corresponding bits determine the corresponding output bit
without reference to any other bit positions. For example:

#+begin_src sh
        10011011
       +11001010
        --------
        01010001
        --------
#+end_src
There are only four cases for each bit position:

#+begin_src sh
   0+0=0
   0+1=1
   1+0=1
   1+1=0  (no carry)
# Subtraction is identical:
        10011011
       -11001010
        --------
        01010001
        --------
#+end_src

In fact, both addition and subtraction in CRC arithmetic is equivalent
to the XOR operation, and the XOR operation is its own inverse. 

Here's a fully worked division:
#+begin_src sh
            1100001010
       _______________
10011 ) 11010110110000
        10011,,.,,....
        -----,,.,,....
         10011,.,,....
         10011,.,,....
         -----,.,,....
          00001.,,....
          00000.,,....
          -----.,,....
           00010,,....
           00000,,....
           -----,,....
            00101,....
            00000,....
            -----,....
             01011....
             00000....
             -----....
              10110...
              10011...
              -----...
               01010..
               00000..
               -----..
                10100.
                10011.
                -----.
                 01110
                 00000
                 -----
                  1110 = Remainder
#+end_src

Thus we see that CRC arithmetic is primarily about XORing particular
values at various shifting offsets.

* Choosing A Poly
Choosing a poly is somewhat of a black art and the reader is referred
to[fn:1] (p.130-132) which has a very clear discussion of this issue. 

Some popular polys are:

| name        | Polys                                            |        Hex |
|-------------+--------------------------------------------------+------------|
| CRC12       | x^12 + x^11 + x^3 + x^2 + x + 1                  |      0x80F |
| CRC16       | x^16 + x^15 + x^2 + 1                            |     0x8005 |
| CRC16-CCITT | x^16 + x^12 + x^5 + 1                            |     0x1021 |
| CRC32       | x^32 + x^26 + x^23 + x^22 + x^16 + x^12 +        | 0x04C11DB7 |
|             | x^11+ x^10 + x^8 + x^7 + x^5 + x^4 + x^2 + x + 1 |            |

* A Straightforward CRC Implementation
#+begin_src sh
            3   2   1   0   Bits
          +---+---+---+---+
 Pop! <-- |   |   |   |   | <----- Augmented message
          +---+---+---+---+
       1    0   1   1   1   = The Poly
#+end_src
To perform the division perform the following:

#+begin_src sh
   Load the register with zero bits.
   Augment the message by appending W zero bits to the end of it.
   While (more message bits)
      Begin
      Shift the register left by one bit, reading the next bit of the
         augmented message into register bit position 0.
      If (a 1 bit popped out of the register during step 3)
         Register = Register XOR Poly.
      End
   The register now contains the remainder.
#+end_src

* A Table-Driven Implementation
 The straightforward method operates at the bit level, it is rather awkward
 to code (even in C), and inefficient to execute (it has to loop once
 for each bit). To speed it up, we need to find a way to enable the
 algorithm to process the message in units larger than one bit.

For the purposes of discussion, let us switch from a 4-bit poly to a
32-bit one. Our register looks much the same, except the boxes
represent bytes instead of bits, and the Poly is 33 bits (one implicit
1 bit at the top and 32 "active" bits) (W=32).

#+begin_src sh
             3    2    1    0   Bytes
          +----+----+----+----+
 Pop! <-- |    |    |    |    | <----- Augmented message
          +----+----+----+----+
         1<------32 bits------>
#+end_src
Consider for a moment that we use the top 8 bits of the register to
calculate the value of the top bit of the register during the next 8
iterations. Suppose that we drive the next 8 iterations using the
calculated values (which we could perhaps store in a single byte
register and shift out to pick off each bit). Then we note three
things:

+ The top byte of the register now doesn't matter. No matter how many
  times and at what offset the poly is XORed to the top 8 bits, they
  will all be shifted out the right hand side during the next 8
  iterations anyway.
+ The remaining bits will be shifted left one position and the
  rightmost byte of the register will be shifted in the next byte
+ While all this is going on, the register will be subjected to a
  series of XOR's in accordance with the bits of the pre-calculated
  control byte.

Perhaps you can see the solution now. Putting all the pieces together
we have an algorithm that goes like this:

#+begin_src sh
   While (augmented message is not exhausted)
      Begin
      Examine the top byte of the register
      Calculate the control byte from the top byte of the register
      Sum all the Polys at various offsets that are to be XORed into
         the register in accordance with the control byte
      Shift the register left by one byte, reading a new message byte
         into the rightmost byte of the register
      XOR the summed polys to the register
      End
#+end_src

As it stands this is not much better than the SIMPLE algorithm.
However, it turns out that most of the calculation can be precomputed
and assembled into a table. As a result, the above algorithm can be
reduced to:

#+begin_src sh
While (augmented message is not exhaused)
      Begin
      Top = top_byte(Register);
      Register = (Register << 24) | next_augmessage_byte;
      Register = Register XOR precomputed_table[Top];
      End
#+end_src

The above is a very efficient algorithm requiring just a shift, and
OR, an XOR, and a table lookup per byte. 

In C, the algorithm main loop looks like this:
#+begin_src c
     r=0;
     while (len--)
       {
        byte t = (r >> 24) & 0xFF;
        r = (r << 8) | *p++;
        r^=table[t];
       }
#+end_src
where len is the length of the augmented message in bytes, p points to
the augmented message, r is the register, t is a temporary, and table
is the computed table. This code can be made even more unreadable as
follows:

#+begin_src c
r=0;
   while (len--)
          r = ((r << 8) | *p++) ^ t[(r >> 24) & 0xFF];
#+end_src

* A Slightly Mangled Table-Driven Implementation
Despite the terse beauty of the above lines, those optimizing hackers
couldn't leave it alone. The trouble, you see, is that this loop
operates upon the AUGMENTED message and in order to use this code, you
have to append W/8 zero bytes to the end of the message before
pointing p at it. Depending on the run-time environment, this may or
may not be a problem; if the block of data was handed to us by some
other code, it could be a BIG problem. One alternative is simply to
append the following line after the above loop, once for each zero
byte:

*最后还需要传入W/4次的0*
#+begin_src c
for (i=0; i<W/4; i++)
           r = (r << 8) ^ t[(r >> 24) & 0xFF];
#+end_src

However, at the further expense of clarity (which, you must admit, is
already a pretty scare commodity in this code) we can reorganize this
small loop further so as to avoid the need to either augment the
message with zero bytes, or to explicitly process zero bytes at the
end as above. 

#+begin_src sh
              3    2    1    0   Bytes
           +----+----+----+----+
    +-----<|    |    |    |    | <----- Augmented message
    |      +----+----+----+----+
    |                ^
    |                |
    |               XOR
    |                |
    |     0+----+----+----+----+
    v      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    +----->+----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
        255+----+----+----+----+
#+end_src


*Algorithm*

1. Shift the register left by one byte, reading in a new message byte.
2. Use the top byte just rotated out of the register to index the
   table of 256 32-bit values.
3. XOR the table value into the register.
4. Goto 1 iff more augmented message bytes.

Now, note the following facts:

+ *TAIL* *处理最后补入的0* The W/4 augmented zero bytes that appear at
  the end of the message will be pushed into the register from the
  right as all the other bytes are, but their values (0) will have no
  effect whatsoever on the register because 1) XORing with zero does
  not change the target byte, and 2) the four bytes are never
  propagated out the left side of the register where their zeroness
  might have some sort of influence. Thus, the sole function of the
  W/4 augmented zero bytes is to drive the calculation for another W/4
  byte cycles so that the end of the REAL data passes all the way
  through the register.
+ *HEAD* *若register初始是0,开始的4次循环仅仅是把0移出* If the initial
  value of the register is zero, the first four iterations of the loop
  will have the sole effect of shifting in the first four bytes of the
  message from the right. This is because the first 32 control bits
  are all zero and so nothing is XORed into the register. Even if the
  initial value is not zero, the first 4 byte iterations of the
  algorithm will have the sole effect of shifting the first 4 bytes of
  the message into the register and then XORing them with some
  constant value (that is a function of the initial value of the
  register).

These facts, combined with the XOR property
#+begin_src sh
   (A xor B) xor C = A xor (B xor C)
#+end_src

mean that message bytes need not actually travel through the W/4 bytes
of the register. Instead, they can be XORed into the top byte just
before it is used to index the lookup table. This leads to the
following modified version of the algorithm.
#+begin_src sh
    +-----<Message (non augmented)
    |
    v         3    2    1    0   Bytes
    |      +----+----+----+----+
   XOR----<|    |    |    |    |
    |      +----+----+----+----+
    |                ^
    |                |
    |               XOR
    |                |
    |     0+----+----+----+----+
    v      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    |      +----+----+----+----+
    +----->+----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
        255+----+----+----+----+
#+end_src

*Algorithm*

1. Shift the register left by one byte, reading in a new message byte.
2. XOR the top byte just rotated out of the register with the next
   message byte to yield an index into the table ([0,255]).
3. XOR the table value into the register.
4. Goto 1 iff more augmented message bytes.

This is an *IDENTICAL* algorithm and will yield *IDENTICAL* results. The
C code looks something like this:

#+begin_src c++
   r=0;
   while (len--)
          r = (r<<8) ^ t[(r >> 24) ^ *++];
#+end_src
* "Reflected" Table-Driven Implementations
*DEFINITION:* A value/register is reflected if it's bits are swapped
around its centre. For example: 0101 is the 4-bit reflection of 1010.

Turns out that UARTs (those handy little chips that perform serial IO)
are in the habit of transmitting each byte with the least significant
bit (bit 0) first and the most significant bit (bit 7) last (i.e.
reflected).

The bytes are processed in the same order, but the bits in each byte
are swapped; bit 0 is now bit 7, bit 1 is now bit 6, and so on. 

*不是对信息bytes的镜像,而是改变算法*
In this situation, a normal sane software engineer would simply
reflect each byte before processing it. However, it would seem that
normal sane software engineers were thin on the ground when this early
ground was being broken, because instead of reflecting the bytes,
whoever was responsible held down the byte and reflected the world,
leading to the following "reflected" algorithm which is identical to
the previous one except that everything is reflected except the input
bytes.

#+begin_src sh
        Message (non augmented) >-----+
                                      |
      Bytes   0    1    2    3        v
           +----+----+----+----+      |
           |    |    |    |    |>----XOR
           +----+----+----+----+      |
                     ^                |
                     |                |
                    XOR               |
                     |                |
           +----+----+----+----+0     |
           +----+----+----+----+      v
           +----+----+----+----+      |
           +----+----+----+----+      |
           +----+----+----+----+      |
           +----+----+----+----+      |
           +----+----+----+----+      |
           +----+----+----+----+<-----+
           +----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+
           +----+----+----+----+255
#+end_src
*Notes:*

+ The table is identical to the one in the previous algorithm except
  that each entry has been *reflected*.
+ The initial value of the register is the same as in the previous
  algorithm except that it has been *reflected*.
+ The bytes of the message are processed in the same order as before
  (i.e. the message itself is *not reflected*).
+ The message bytes themselves don't need to be explicitly reflected,
  because everything else has been!

* Initial and Final Values
In addition to the complexity already seen, CRC algorithms differ from
each other in two other regards:

+ The initial value of the register.
+ The value to be XORed with the final register value.

For example, the "CRC32" algorithm initializes its register to
FFFFFFFF and XORs the final register value with FFFFFFFF.
* Example
#+INCLUDE: "./files/crc_example.c" src c
* CRC Algorithms
+ A [[http://automationwiki.com/index.php?title=CRC-16-CCITT]["CRC16" (CRC-16-CCITT)]] implementation on AutomationWiki.
+ [[http://www.drdobbs.com/implementing-the-ccitt-cyclical-redundan/199904926][Implementing The CCITT Cyclical Redundancy Check]] on Dr Dobbs.
+ [[http://create.stephan-brumme.com/crc32/][Fast CRC32 Compare]]
+ [[https://users.ece.cmu.edu/~koopman/crc/][Best CRC Polynomials]]
+ [[http://www.networkdls.com/Software/View/CRC32][A C++ Class that encapsulates the official CRC32 algorithm]]
+ [[http://stackoverflow.com/questions/302914/crc32-c-or-c-implementation][CRC32 C or C++ implementation on the stackoverflow]]
+ A CRC algorithm in C: [[./files/crc.zip][crc.zip]]

** A Parameterized Model For CRC Algorithms
The algorithm is from [[http://www.repairfaq.org/filipg/LINK/F_crc_v34.html][A Parameterized Model For CRC Algorithms]].

+ *REFIN* This is a boolean parameter. If it is FALSE, input bytes are
  processed with bit 7 being treated as the most significant bit (MSB)
  and bit 0 being treated as the least significant bit. If this
  parameter is FALSE, each byte is reflected before being processed.
+ *REFOUT* This is a boolean parameter. If it is set to FALSE, the
  final value in the register is fed into the XOROUT stage directly,
  otherwise, if this parameter is TRUE, the final register value is
  reflected first.

The crc algorithm and genarating a lookup table are in the
[[./files/crcmodel.tar.gz][crcmodel.tar.gz]].

* More
+ [[http://www.repairfaq.org/filipg/LINK/F_crc_v3.html][A PAINLESS GUIDE TO CRC ERROR DETECTION ALGORITHMS]]
+ [[https://barrgroup.com/Embedded-Systems/How-To/CRC-Calculation-C-Code][CRC Implementation Code in C/C++]]

* Footnotes

[fn:1] Tanenbaum, A.S., "Computer Networks", Prentice Hall, 1981, ISBN: 0-13-164699-0. Comment: Section 3.5.3 on pages 128 to 132 provides a very clear description of CRC codes. However, it does not describe table-driven implementation techniques.



