#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Domain names host
#+OPTIONS: num:nil H:2


* namecheap[fn:1]
强烈推荐。namecheap的价格不算最便宜的，但是各方面做得真的真的都很好，
包括但不限于：速度，控制台，客服响应，稳定性，免费的ssl和whois privacy
等等。而且碰到了域名转出和退款什么的都完全不拖泥带水，可以说性价比非常
高。

* name.com
价格上来说，新注册的会比GoDaddy贵一些，10刀左右，但人家续费也是同一个
价，不会一不小心被高价续费，那叫一个心疼。http://name.com 的问题是他们
的域名服务器更新速度跟GoDaddy差不多，改个DNS都要好几个小时。

但这几年http://name.com:

1. 大部分域名都提价了，比如.com从$9.99到了$10.99。
2. 在别人都开始提供免费ssl的时候，他们居然连自己的主站都不用ssl（印象
   中是后来才开始用）。
* GoDaddy
+ 最近几年出过好几次DNS被黑的情况，要知道域名注册商的DNS服务器被黑可不
  是小事情。几千万的网站随时解析不了，但就是这样GoDaddy还是被黑了不止
  一次。可见内部管理已经僵化，反应不过来了。
+ GoDaddy前几年偷域名的事情搞得沸沸扬扬。许多人在GoDaddy上搜好的域名第
  二天上去买了就发现被GoDaddy给抢注了，到了二级市场价格直接翻上成百上
  千倍。
+ 这个公司的定价策略不是很透明。比如有一次看到.com域名2.99刀的，点进去
  一看原来是要签两年合约的第一年才2.99刀，第二年就要回到14.99.算下来两
  年也没比namecheap便宜多少
+ 本身的销售团队KPI考核压力太大，连他们的客服都是不遗余力地想卖你东西。
  有什么问题打电话过去问题还没解决先问你要不要续费，哭笑不得。
+ DNS更新速度很慢。至少前几年要好几个小时才生效。几年没用了不知道现在
  有没有好点了。
* enom
enom在国内可能知名度不是很高，但其实是很老牌的域名注册商，namecheap直
到最近之前还只是个enom的分销商（就是说他们直到最近才成为ICANN的正式域
名注册商）。Google App提供的域名管理后台就是GoDaddy和enom二选一，换句
话说Google也是enom的分销商之一。

enom现在的问题是他们企业路线对我们不友好。这个公司逆互联网的趋势而行，
这几年极其注重分销市场，而懒得搭理最终消费者市场（怀疑公司是不是被三哥
把持了）。搞到现在他们的零售价格比起 name.com 和 namecheap 都要更高
一些。

金牌会员50元每年，金牌会员一般在淘宝上30元左右能买到

* SSL
1. startssl免费: https://www.startssl.com/
2. cloudflare的免费版自带ssl: https://www.cloudflare.com/plans/

* DNS记录管理
一般是国外域名就直接把name server(域名服务器)转到[[https://www.cloudflare.com/][CloudFlare]]， 国
内的转到[[https://www.dnspod.cn/][DNSPod-免费智能DNS解析服务商]].

* Domain Price Comparison
https://www.domcomp.com/

这个网站还提供返利，可以折上再折，加入方法很简单，点击右上角的
affiliate。

登陆以后会进到dashboard，也就是控制台。你会看到有一个链接在中间是绿色
的，这个就是你的返利链接

下面（请注意这一步很重要），点一下你的返利链接，回到了
http://domcomp.com 的主页。是不是看上去什么都没变？ 其实不然，你的返利
码已经在cookie里面了。接下来就直接点namecheap的价格链接去namecheap注册
账号+买域名吧！

买的时候有几点要注意
+ 记得每次都要注册新账号，但是namecheap貌似只对新注册账号有返利。
+ 每次买之前，都最好确认一下返利码在cookie里面，做法就是登陆一下专
  门点一下返利链接，然后再点namecheap。这个时候刷新返利控制台，看看点
  击数(clicks)有没有增加.

* Footnotes

[fn:1] https://www.zhihu.com/question/19551906
 

