#+SETUPFILE: ~/.emacs.d/src/org-templates/level-3.org
#+TITLE: Programming Pearls: Column7
#+OPTIONS: num:nil H:2

* Book notes
** Overview
一天中密西西比河的流量是多少？

作者估算：河口宽度大约1 mile，大约1/250英里深，他猜测流速是5mile每小时或
120mile每天。

1mile * 1/250mile * 120 miles/day = 1/2 mile^3/day

** 基本技巧
*** 两个答案好于一个
估算中密西西比河的流域是 1000 × 1000 miles， 一年雨量大约1英尺，
（1/5000英里每年）。
1000miles * 1000miles * 1/5000 mile/year = 200 mile^3/year
200mile^3/year/400days/year = 1/2 mile^3/day
*** 快速检查
+ Rule1： 相加的单位与原来一样。
+ Rule2： 相乘的单位是单位的相乘。
*** 经验法则
72法则。

假如一笔钱以年利率百分比r存y年。如果r×y=72,那么钱将成2倍。这个估算大
体正确，存1000以6%的年利率存12年之后为2012.

72法则对估算指数增长非常实用。双倍对于程序员来说很熟悉：2^10=1024，10
倍双倍就是1thousand，20个双倍就是1million。

假如一个指数型复杂度的程序花10秒解决一个n=40的问题，每把n增加1就增加
12%的运行时间。72法则告诉我们，运行时间成2倍当n增加6，也就是1000倍
（2^10）当n增加60(6*10)。所以当n=100时，程序花10,000秒，也就几小时。当n
增加到160,时间成为10^7 秒,那这时间大约是多少呢？

很难记住一年的时间是3.155×10^7 秒，另一方面，很难忘记Tom Duff的实用经
验准则，1%多的误差：

       *$\pi$ 秒是1纳世纪。* ($\pi$ seconds is a nanocentury.)
*** 练习
不断练习提高自己的估算技巧。

书中估算密西西比河的流量并不是特别技巧好，比如直接估测出流速是5mile每
小时，很难直观想出这个数字。

推荐[[http://book.douban.com/subject/4904724/][《这也能想到?——巧妙解答无厘头问题》]] 这本书，全书都是估算题目，
1. 明白估算的目标精确度只需要达到一个数量级，和真实数据不超过10倍就是
   比较好的估算。
2. 估算一个东西的范围的关键是几何平均数。比如这里流量最小1mile每小时，
   最大10mile每小时，那么估算它为3mile每小时（几何平均）。比如地球的密
   度，比水大，比铁小，取它们的几何平均。
** 利特尔法则(Little's law)


* Problems

