#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Comparing and Merging Files with GNU diff and patch Notes
#+OPTIONS: num:nil H:2

* Overview
gnu diff was written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower. Wayne Davison designed and implemented
the unified output format. The basic algorithm is described in
“An O(ND) Difference Algorithm and its Variations”, Eugene W. Myers,
Algorithmica Vol. 1 No. 2, 1986, pp. 251–266; and in “A File Comparison
Program”, Webb Miller and Eugene W. Myers, Software—Practice
and Experience Vol. 15 No. 11, 1985, pp. 1025–1040. The algorithm was
independently discovered as described in “Algorithms for Approximate String Matching”, E. Ukkonen, Information and Control Vol. 64, 1985,
pp. 100–118.

* Chapter 1: What Comparison Means
** 1.1 Hunks
When comparing two files, diff finds sequences of lines common to
both files, interspersed with groups of differing lines called
/hunks/.

** 1.2 Suppressing Differences in Blank and Tab Spacing
The ‘-E’ and ‘--ignore-tab-expansion’ options ignore the distinction
between tabs and spaces on input. A tab is considered to be equivalent
to the number of spaces to the next tab stop. diff assumes that tab
stops are set every 8 print columns.

The ‘-b’ and ‘--ignore-space-change’ options are stronger. They
ignore white space at line end, and consider all other sequences of one or
more white space characters to be equivalent.

=diff= considers the following two lines to be equivalent, where ‘$’
denotes the line end:
#+begin_verse
Here lyeth muche rychnesse in lytell space. -- John Heywood$
Here lyeth muche rychnesse in lytell space. -- John Heywood $
#+end_verse

The ‘-w’ and ‘--ignore-all-space’ options are stronger still. They
ignore difference even if one line has white space where the other line has
none.

=diff= considers the following two lines to be equivalent, where ‘$’ denotes the line end and ‘^M’
denotes a carriage return:
#+begin_verse
Here lyeth muche rychnesse in lytell space.-- John Heywood$
 He relyeth much erychnes seinly tells pace. --John Heywood ^M$
#+end_verse








** 1.3 Suppressing Differences in Blank Lines
The ‘-B’ and ‘--ignore-blank-lines’ options ignore insertions or
deletions of blank lines. These options affect only lines that are completely
empty; they do not affect lines that look empty but contain space or tab
characters.
** 1.4 Suppressing Case Differences
To request this, use the ‘-i’ or ‘--ignore-case’ option.
** 1.5 Suppressing Lines Matching a Regular Expression
To ignore insertions and deletions of lines that match a grep-style regular
expression, use the ‘-I regexp’ or ‘--ignore-matching-lines=regexp’
option. For example, ‘diff -I ’^[[:digit:]]’’ ignores all changes to lines
beginning with a digit.

You can specify more than one regular expression for lines to ignore
by using more than one ‘-I’ option. diff tries to match each line against
each regular expression.
** 1.6 Summarizing Which Files Differ
diff simply reports whether files differ. The ‘-q’ and ‘--brief’
options select this output format.

Unlike diff, cmp cannot compare directories; it can only compare two
files.
** 1.7 Binary Files and Forcing Text Comparisons
You can force diff to consider all files to be text files, and compare them
line by line, by using the ‘-a’ or ‘--text’ option.

You can also force diff to consider all files to be binary files, and
report only whether they differ (but not how). Use the ‘-q’ or ‘--brief’
option for this.

Use the ‘--binary’ option to force diff to read and write binary data
instead.

The ‘--strip-trailing-cr’ causes diff to treat input lines that end
in carriage return followed by newline as if they end in plain newline












* Chapter 2: diff Output Formats
** 2.2.1 Detailed Description of Normal Format
All line numbers are the original line numbers in each file. The types
of change commands are:

+ *‘lar’*: Add the lines in range r of the second file after line l of the
  first file. For example, ‘8a12,15’ means append lines 12–15 of file 2
  after line 8 of file 1; or, if changing file 2 into file 1, delete lines 12–15 of file 2.
+ *‘fct’*: Replace the lines in range f of the first file with lines
  in range t of the second file. This is like a combined add and
  delete, but more compact. For example, ‘5,7c8,10’ means change lines
  5–7 of file 1 to read as lines 8–10 of file 2; or, if changing file
  2 into file 1, change lines 8–10 of file 2 to read as lines 5–7 of file 1.
+ *‘rdl’* Delete the lines in range r from the first file; line l is
  where they would have appeared in the second file had they not been
  deleted. For example, ‘5,7d3’ means delete lines 5–7 of file 1; or,
  if changing file 2 into file 1, append lines 5–7 of file 1 after
  line 3 of file 2.

** 2.3 Showing Differences in Their Context
you will
also want to see the parts of the files near the lines that differ, to help you
understand exactly what has changed. These nearby parts of the files are
called the /context/.

gnu diff provides two output formats that show context around the
differing lines: context format and unified format.

** 2.3.1 Context Format
To select this output format, use the ‘-C lines’, ‘--context[=lines]’,
or ‘-c’ option. The argument lines that some of these options take is
the number of lines of context to show.
*** 2.3.1.1 Detailed Description of Context Format
The lines that differ between the two files start with one of
the following indicator characters, followed by a space character:

+ ‘!’: A line that is part of a group of one or more lines that
  changed between the two files. There is a corresponding group of
  lines marked with ‘!’ in the part of this hunk for the other file.

+ ‘+’ An “inserted” line in the second file that corresponds to
  nothing in the first file. 

+ ‘-’ A “deleted” line in the first file that corresponds to nothing
  in the second file.

** 2.3.2 Unified Format
To select this
output format, use the ‘-U lines’, ‘--unified[=lines]’, or ‘-u’ option. The
argument lines is the number of lines of context to show.

*** 2.3.2.1 Detailed Description of Unified Format
Unified format hunks look like this:
#+begin_verse
@@ from-file-range to-file-range @@
line-from-either-file
line-from-either-file...
#+end_verse

The lines that actually differ between the two files have one of the
following indicator characters in the left print column:
+ ‘+’ A line was added here to the first file.
+ ‘-’ A line was removed here from the first file.
*** 2.3.2.2 An Example of Unified Format
#+begin_src sh
$ diff -u  test1 test2
--- test1	2012-09-26 22:55:50.875392031 +0800
+++ test2	2012-09-26 23:09:39.927172792 +0800
@@ -1,11 +1,13 @@
-The Way that can be told of is not the eternal Way;
-The name that can be named is not the eternal name.
 The Nameless is the origin of Heaven and Earth;
-The Named is the mother of all things.
+The named is the mother of all things.
+
 Therefore let there always be non-being,
 so we may see their subtlety,
 And let there always be being,
 so we may see their outcome.
 The two are the same,
 But after they are produced,
-they have different names.
\ No newline at end of file
+they have different names.
+They both may be called deep and profound.
+Deeper and more profound,
+The door of all subtleties!
\ No newline at end of file

#+end_SRC

** 2.3.3.1 Showing Lines That Match Regular Expressions
use the ‘-F regexp’ or ‘--show-function-line=regexp’ option.

Here are suggested regular expressions for some
common languages:
#+begin_src sh
‘^[[:alpha:]$_]’
   C, C++, Prolog
‘^(’   Lisp
‘^@node’    Texinfo
#+end_src

The ‘-F’ and ‘--show-function-line’ options find the nearest unchanged
line that precedes each hunk of differences and matches the given
regular expression.

** 2.3.3.2 Showing C Function Headings
To show in which functions differences occur for C and similar languages,
you can use the ‘-p’ or ‘--show-c-function’ option.

** 2.3.4 Showing Alternate File Names
Here are the first two lines of the output from ‘diff -C 2
--label=original --label=modified lao tzu’:
#+begin_src sh
  *** original
  --- modified
#+end_src

** 2.4 Showing Differences Side by Side
The gutter contains one of the following markers:
#+begin_verse
white space
The corresponding lines are in common. That is, either the
lines are identical, or the difference is ignored because of one
of the ‘--ignore’ options (see Section 1.2 [White Space],
page 6).

‘|’   The corresponding lines differ, and they are either both complete
or both incomplete.

‘<’ The files differ and only the first file contains the line.
‘>’ The files differ and only the second file contains the line.
‘(’ Only the first file contains the line, but the difference is
ignored.
‘)’ Only the second file contains the line, but the difference is
ignored.
‘\’ The corresponding lines differ, and only the first line is incomplete.
‘/’ The corresponding lines differ, and only the second line is
incomplete.
#+end_verse
*** 2.4.1 Controlling Side by Side Format
The ‘-y’ or ‘--side-by-side’ option selects side by side format.

You can set the width of the output with the ‘-W columns’
or ‘--width=columns’ option.

The ‘--left-column’ option prints only the left column of two common
lines. The ‘--suppress-common-lines’ option suppresses common
lines entirely

*** 2.4.2 An Example of Side by Side Format
Here is the output of the command =‘diff -y -W 65 lao tzu’=.

#+begin_src sh
The Way that can be told of i <
The name that can be named is <
The Nameless is the origin of	The Nameless is the origin of
The Named is the mother of al |	The named is the mother of al
			      >
Therefore let there always be	Therefore let there always be
so we may see their subtlety,	so we may see their subtlety,
And let there always be being	And let there always be being
so we may see their outcome.	so we may see their outcome.
The two are the same,		The two are the same,
But after they are produced,	But after they are produced,
they have different names.    \	they have different names.
			      >	They both may be called deep 
			      >	Deeper and more profound,
			      >	The door of all subtleties!%  
#+end_src

** 2.6 Merging Files with If-then-else
To merge two files, use diff with the ‘-D name’ or ‘--ifdef=name’
option. The argument name is the C preprocessor identifier to use in
the #ifdef and #ifndef directives.

* Chapter 3: Incomplete Lines
When an input file ends in a non-newline character, its last line is
called an incomplete line because its last character is not a newline. All
other lines are called full lines and end in a newline character. Incomplete
lines do not match full lines unless differences in white space are
ignored
* Chapter 4: Comparing Directories



* seldom use
** 2.6.1 Line Group Formats
You should quote format, because it typically contains shell
metacharacters.
‘--old-group-format=format’
These line groups are hunks containing only lines from the
first file. The default old group format is the same as the
changed group format if it is specified; otherwise it is a format
that outputs the line group as-is.

‘--new-group-format=format’
These line groups are hunks containing only lines from the
second file. The default new group format is same as the
changed group format if it is specified; otherwise it is a format
that outputs the line group as-is.

‘--changed-group-format=format’
These line groups are hunks containing lines from both files.
The default changed group format is the concatenation of
the old and new group formats.

‘--unchanged-group-format=format’
These line groups contain lines common to both files. The
default unchanged group format is a format that outputs the
line group as-is.

In a line group format, ordinary characters represent themselves; conversion
specifications start with ‘%’ and have one of the following forms.
‘%<’ stands for the lines from the first file, including the trailing
newline. Each line is formatted according to the old line
format (see Section 2.6.2 [Line Formats], page 27).
‘%>’ stands for the lines from the second file, including the trailing
newline. Each line is formatted according to the new line
format.
‘%=’ stands for the lines common to both files, including the trailing
newline. Each line is formatted according to the unchanged
line format.
‘%%’ stands for ‘%’.
‘%c’C’’ where C is a single character, stands for C. C may not be a
backslash or an apostrophe. For example, ‘%c’:’’ stands for
a colon, even inside the then-part of an if-then-else format,
which a colon would normally terminate.
‘%c’\O’’ where O is a string of 1, 2, or 3 octal digits, stands for the
character with octal code O. For example, ‘%c’\0’’ stands
for a null character.

‘Fn’ where F is a printf conversion specification and n is one of
the following letters, stands for n’s value formatted with F.
‘e’ The line number of the line just before the
group in the old file.
‘f’ The line number of the first line in the group
in the old file; equals e + 1.

‘l’ The line number of the last line in the group in
the old file.
‘m’ The line number of the line just after the group
in the old file; equals l + 1.
‘n’ The number of lines in the group in the old file;
equals l - f + 1.
‘E,F,L,M,N ’
Likewise, for lines in the new file.


