#+SETUPFILE: ~/.emacs.d/src/org-templates/level-3.org
#+TITLE: The Algorithm Design Manual
#+OPTIONS: num:nil H:2

* Overview
** homepage
+ http://www.cs.sunysb.edu/~algorith/
+ http://www.algorist.com/

** solution
+ official:
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Main_Page
+ other blog:
  http://blog.panictank.net/category/algorithmndesignmanualsolutions/

+ Introduction to Algorithm Design
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Introduction-TADM2E

+ Algorithm Analysis
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Algo-analysis-TADM2E

+ Data Structures
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Data-structures-TADM2E-2

+ Sorting and Searching
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Sorting-searching-TADM2E

+ Graph Traversal
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Graphs-TADM2E

+ Weighted Graph Algorithms
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Weighted-graphs-TADM2E

+ Combinatorial Search and Heuristic Methods
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Search-TADM2E

+ Dynamic Programming
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Divide-TADM2E

+ Intractable Problems and Approximation Algorithms
  http://nbl.cewit.stonybrook.edu:60128/mediawiki/index.php/Hardness-TADM2E

** errata
http://www.cs.sunysb.edu/~skiena/algorist/book/errata
* About book
Equally important is what we do not do in this book. We do not stress the
mathematical analysis of algorithms, leaving most of the analysis as informal arguments. You will not find a single theorem anywhere in this book. When more
details are needed, the reader should study the cited programs or
references. 

 Each chapter’s exercises will
contain links to 3-5 relevant “Programming Challenge” problems from
http://www.programming-challenges.com.
