#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: 检测笔记本
#+OPTIONS: num:nil H:2


* 检测硬件配置
AIDA64

* 检测屏幕
 在AIDA64顶部菜单栏，点击“工具”-"显示器检测"，然后会打开AIDA64
 Monitor Diagnostics，点击右下角的”Auto Run Selected Tests“直接开始
 屏幕检测。如果仅仅只检测屏幕亮点，坏点，暗点之类，可以直接点击"Color
 Tests"，然后点击”Run Selected Tests“开始检测。

* 检测硬盘
 检测硬盘，主要是查看硬盘通电时间和通电次数，一般推荐用HD Tune或者
 CrystalDiskInfo。

打开HD Tune，点击健康，我们主要看下面的"09 累计通电时间计数"和"0C 通电
周期计数"。一般来说通电时间40小时以下，通电次数50次以下都算正常。

* 检测CPU
一般用CPU-Z检测CPU的详细信息。

* 检测显卡
一般用GPU-Z检测显卡的详细信息。

* 检测电池
一般用BatteryMon检测电池的详细信息。

* 检测USB接口
 自备u盘，分别插入每个USB接口，检测能否正常读取数据。

* 检测读卡器
    自备SD卡或者MMC卡等，插入读卡器，检测能否正常读取数据。

* 检测光驱
    自备光盘，放入光驱，检测能否正常读取光盘。

* 检测蓝牙和无线网卡
    打开蓝牙和WIFI。自备带蓝牙的手机或者其他蓝牙设备，试试能
    否连接。无线网络打开后，搜下周围，看看能否搜到无线信号。（当然前提
    是，周围有WIFI信号）

* 检测喇叭和显示效果
    打开Windows自带的音频视频或者自备的音频视频文件，听下喇叭效果，看
    下视频效果。

* 检测摄像头和麦克风

* Service Tag

开机F2看BIOS 的配置。看看编号是不是在底座看见的那个编号。以及在里面可
以看见硬件的配置可以对下配置查保修：
http://www.dell.com/support/troubleshooting/cn/zh/cndhs1/TroubleShooting/ProductSelector


* dell 全球服务转移

转移服务的表格的话，其实大家都会填的，只有原始购买者可能不知道。原始邮
箱原来没有的话就写N/A就好了。其他的信息就是你现在的信息。全球转移服务
的网站是：
http://support.dell.com/support/topics/global.aspx/support/dellcare/en/international_ownership_transfer_form1?c=us&cs=19&l=en&s=dhs&redirect=1

转移服务的是转移成功了还是信息不全的话会发邮件给你邮箱通知的，时间大概
要半个月到1个月。甚至更长，那么我们要还可以填写加快服务转移的申请。地
址是：
http://www.dell.com/content/topics/reftopic.aspx/pub/ccare/transfer_status?c=us&cs=19&l=en&s=dhs
。

