#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: GR
#+OPTIONS: num:nil H:2

* nacoki

https://www.flickr.com/photos/nacoki/269246217

Recent some flickr ask me about the trick on GR-D
so I would like to share some of my experience on using this.
 
the basic setting of my GR-D
+ customize image setting 1
- highest contrast
- highest sharpness
- highest color depth ( i think this also relate to the saturation of the photo )
 
many people ask about the post-production,
actually i m quite lazy on this, n i m not good at photoshop
so, all of my photo are using iPhoto 6 to manage.
as the setting in the GR-D are already enough,
so i will only increase the CONTRAST on some of the photo,
to make the subject matter much sharp.
 
the mode I always use:
+ P mode ( nearly all the time *daylight )
- AUTO iso ( range 64- 200) * over 200 will affect the color as i feel
- AUTO white balance ( actually always wrong )
- customize image setting 1
- MULTI AF ( favourable for MACRO )
- MULTI photometry ( easy to get some interesting light effect )
 
+ M mode ( when i want to have long exposure * night time/ low light intensity)
- same as P mode setting
- f 2.4
- duration (2 sec -15 sec) * above 15 sec, the GR-D loading like a fool :P
 
many people ask about the COLOR of my photo,
the main point isn't the post-production,
or the customize setting ( but i prefer using the maximum )
But what i think is the SHUTTER SPEED.
when you compare with two setting,
+ f2.4, 1 sec , iso AUTO ( assume to be 200 )
+ f2.4, 1/10 , iso 800
I can sure the one with 1 sec have better color result,
as it accumulate more light
instead of push up the iso.
GR-D is a strange machine,
the longer time exposure = vivid color.

e.g.
www.flickr.com/photos/nacoki/267170208/

 
I found that when you using P mode,
the slowest shutter speed is 1 sec,
as it is quite enough for many situation
BUT you need to have a STEADY HAND ( maybe you can use triport )
actually many of my photo are shooting at 1 sec.

* 理光GR拍摄设置经验、技巧大全
一、高对比黑白（森山模式） 
高对比黑白，必须用点测光。 
——来自：垃圾叔叔 

1：设定 鲜艳度5 对比度5 鲜明度6 然后 白平衡 复合 B2G2 重点测光 效果完美 
——来自：垃圾叔叔 

二、快门次数查看方法： 
关机状态下，按住播放键和方向键（下），就可以看到你的快门次数。 
+ SH 快门数 
+ ST 闪光灯数 

今天发现理光一个小功能很好用菜单里的完全自动对焦，设置为开启后，快速按
下快门，即可按照snap预设直接拍摄慢一点半按快门，照旧对焦 
——来自Reven 


三、关于设置ISO100，自动变为ISO320的解决方法

把“动态范围补偿”设定为“关”（默认设置是“自动”），然后再回到感光度
调节菜单，ISO设定多少就是多少，不会再变成320. 欢迎盖楼交流设置心得。 


四、理光GRⅡ固件更新方法 
1. 首先下固件固件下载：
   http://www.ricoh-imaging.com.cn/ricoh/DownloadServlet?param=queryDetail&id=53 
2. 格式化SD卡（卡内资料请保存），然后将固件解压缩，放SD卡根目录 
3. 然后开机，按menu，选第三个设定，最后一个“确认固件版本”，然后选确
   定。 下载的文件解压后，放到sd卡根目录下，开机，打开菜单，检查固件版
   本，确认升级就可以了。完成后先别开机，先把sd卡上的固件文件删了，然
   后就好了 

* 经典延续 理光GR海外长期使用心得
http://photo.poco.cn/special_topic/topic_id-15819-p-1.html#content_hash

* Groups
+ [[http://www.douban.com/group/grd/][GR Fans Club]]
+ [[http://www.douban.com/group/476211/?ref=sidebar][理光GR \ GRⅡ俱乐部]]
+ [[http://www.douban.com/group/147985/][理光GR系列]]


