#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Interactive Data Visualization for the Web
#+OPTIONS: num:nil H:2


* Preface
On design process:

+ Designing Data Visualizations: Intentional Communication from Data
  to Display by Noah Iliinsky and Julie Steele. O’Reilly Media, 2011.
+ Data Visualization: A Successful Design Process by Andy Kirk. Packt
  Publishing, 2012.
+ The Functional Art: An Introduction to Information Graphics and
  Visualization by Alberto Cairo. New Riders, 2012
+ Information Dashboard Design: The Effective Visual Communication of
  Data by Stephen Few. O’Reilly Media, 2006.

On the practicalities of working with data:
+ Bad Data Handbook: Mapping the World of Data Problems by Q. Ethan
  McCallum. O’Reilly Media, 2012
+ Data Analysis with Open Source Tools: A Hands-On Guide for
  Programmers and Data Scientists by Philipp K. Janert. O’Reilly
  Media, 2010.
+ Python for Data Analysis: Agile Tools for Real World Data by Wes
  McKinney.O’Reilly Media, 2012.
* Introduction
** Why Interactive?
The basic functions of most interactive visualization tools have
changed little since 1996, when Ben Shneiderman of the University of
Maryland first proposed a “Visual Information-Seeking Mantra”:
/overview first, zoom and filter, then details-ondemand/.
* Introducing D3
D3’s official home on the Web is d3js.org.
** What It Doesn’t Do
+ D3 is intended primarily for  explanatoryvisualization work, as
  opposed to exploratory  visualizations.
+ D3 doesn’t even try to support older browsers.
+ D3’s core functionality doesn’t handle bitmap map tiles, such as
  those provided by Google Maps or Cloudmade. D3 is great with
  anything vector—SVG images or GeoJSON data—but wasn’t originally
  intended to work with traditional map tiles.
+ D3 doesn’t hide your original data.
** Origins and Context
Protovis made generating visualizations simple, even for users without
prior programming experience. Yet to achieve this, it created an
abstract representation layer. The designer could address this layer
using Protovis syntax, but it wasn’t accessible through standard
methods, so debugging was difficult.

In 2011, Mike Bostock, Vadim Ogievetsky, and Jeff Heer officially
announced D3, the next evolution in web visualization tools. Unlike
Protovis, D3 operates directly on the web document itself. This means
easier debugging, easier experimentation, and more visual
possibilities. The only downside to this approach is a potentially
steeper learning curve.

** Alternatives

*** Easy Charts
+ DataWrapper: A beautiful web service that lets you upload your data
  and quickly generate a chart that you can republish elsewhere or
  embed on your site. This service was originally intended for
  journalists, but it is helpful for everyone. 
+ Flot; A plotting library for jQuery that uses the HTML canvas
  element and supports older browsers, even all the way back to
  Internet Explorer 6. It supports limited visual forms (lines,
  points, bars, areas), but it is easy to use.
+ Google Chart Tools: Having evolved from their earlier Image Charts
  API, Google’s Chart Tools can be used to generate several standard
  chart types, with support for old versions of IE.











* cc
#+begin_src python

#+end_src

#+begin_src c++

#+end_src


#+begin_src sh

#+end_src
