#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Quantitative Trading: How to Build Your Own Algorithmic Trading Business
#+OPTIONS: num:nil H:2

* Overview

It provides a great overview of the process of setting up a "retail"
quantitative trading system, using MatLab or Excel. He makes the
subject highly approachable and gives the impression that "anyone can
do it". Although there are plenty of details that are skipped over
(mainly for brevity), the book is a great introduction to how
algorithmic trading works. 

Source codes: [[./files.QuantitativeTrading.tar.gz][QuantitativeTrading.tar.gz]]
* Sources of Trading Ideas
P10

* Chapter 2
For historical stock data, there is another quality
that may be even more important than their frequencies: whether
the data are free of survivorship bias.

Finding prospective quantitative trading strategies is not difficult.
There are:
+ Business school and other economic research web sites.
+ Financial web sites and blogs focusing on the retail investors.
+ Trader forums where you can exchange ideas with fellow traders.
* Chapter 3
epchan.com/book/
example31.m, with “sharperatio” as both username and password.


* cc
#+begin_src python

#+end_src

#+begin_src c++

#+end_src


#+begin_src sh

#+end_src
