#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE: Linux Overview
#+OPTIONS: num:nil H:2


* TI 
** TI Category:Linux
http://processors.wiki.ti.com/index.php/Category:Linux
** Linux Utils Internals
http://processors.wiki.ti.com/index.php/Linux_Utils_Internals

** Linux Toolchain
 http://processors.wiki.ti.com/index.php/Linux_Toolchain

* Wiki
** gumstix
http://wiki.gumstix.org/index.php?title=Main_Page
** eLinux wiki
http://elinux.org/Main_Page

* Linux Kernel
** TI
+ The DaVinci GIT kernel
  http://processors.wiki.ti.com/index.php/DaVinci_GIT_Linux_Kernel

  The DaVinci GIT kernel is the focus of community development, and
  staging area for DaVinci support to be pushed up to mainline. It is
  regularly kept up-to-date with the mainline kernel, and welcomes
  contributions including patches from all; coordinated on its mailing
  list

+ TI Arago project PSP releases
  http://processors.wiki.ti.com/index.php/DaVinci_PSP_Releases
  TI Arago project PSP releases: TI developers maintain their own
  "arago" tree based on the above community tree, but also including
  work-in-progress drivers which may not be available yet in the
  community tree. They also make official PSP releases including
  U-Boot and so on. The arago tree does not accept patches from
  developers outside TI.

+ MontaVista Linux Professional Edition 4.0 for DaVinci
  http://www.mvista.com/boards.php?vendorsearch=&boardname=&archgroup=All&processor=Davinci&edition=All&v=All&a0=1
  MontaVista Linux Professional Edition 4.0 for DaVinci is available
  with support contracts, but based on a relatively old kernel
  (2.6.10)

+ Mainline kernel
  http://git.kernel.org/?p=linux/kernel/git/torvalds/linux-2.6.git;a=summary
  there is the Mainline kernel which has much support merged from the
  community DaVinci GIT tree, but naturally lags behind it in terms of
  DaVinci support.



   

* project
** OpenEmbedded
http://www.openembedded.org/wiki/Main_Page
** Poky Linux
http://www.pokylinux.org/
** Ubuntu ARM
https://wiki.ubuntu.com/ARM
