#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE: U-Boot Overview
#+OPTIONS: num:nil

* Offical website
http://www.denx.de/wiki/U-Boot/WebHome

* Boot Linux Kernel
* U-Boot Commands
** bdinfo - print Board Info structure
The =bdinfo= command (short: =bdi=) prints the information that U-Boot
passes about the board such as memory addresses and sizes, clock
frequencies, MAC address, etc. This information is mainly needed to be
passed to the Linux kernel.

#+begin_src sh
=> bdi
memstart    = 0x00000000
memsize       = 0x20000000
flashstart  = 0xFC000000
flashsize   = 0x04000000
flashoffset = 0x00000000
sramstart   = 0x00000000
sramsize    = 0x00000000
bootflags   = 0xFFFE6530
...
#+end_src
** md - memory display
#+begin_src sh
md - memory display

Usage:
md [.b, .w, .l] address [# of objects]
#+end_src
The md can be used to display memory contents both as hexadecimal and
ASCII data.

#+begin_src sh
=> md 0x100000
00100000: 8083764e bd86200a 60a19054 2c12c402    ..vN.. .`..T,...
00100010: c101d028 00438198 7ab01239 62406128    ...(.C..z..9b@a(
00100020: 0c900d05 320b4581 1ca3d0a2 c498293a    ....2.E.......):
#+end_src

** mm - memory modify (auto-incrementing)
#+begin_src sh
mm - memory modify (auto-incrementing address)

Usage:
mm [.b, .w, .l] address
#+end_src
** mtest
#+begin_src sh
 mtest <start-address> <end-address> <test pattern> <# of iterations>
#+end_src

*** Example
#+begin_src sh
Target# mtest 0x80000000 0xA0000000 0xaa55aa55 3 (referred as Test A)
Target# mtest 0xA0000000 0xC0000000 0xaa55aa55 3 (referred as Test B)
#+end_src
** List files on a FAT32 formated SD card
#+begin_src sh
TI8168_EVM# mmc rescan 0
TI8168_EVM# fatls mmc 0
#+end_src
** Set static ip
#+begin_src sh
TI8168_EVM# setenv ipaddr <your static ip>
#+end_src

* U-Boot Environment Variables
** =bootargs=
bootargs: The contents of this variable are passed to the Linux kernel
as boot arguments (aka "command line").
** =bootcmd=
bootcmd: This variable defines a command string that is automatically executed when the initial countdown is not interrupted. 
This command is only executed when the variable bootdelay is also
defined!
** =ethaddr=
ethaddr: Ethernet MAC address for first/only ethernet interface (= eth0 in Linux). 
This variable can be set only once (usually during manufacturing of
the board). U-Boot refuses to delete or overwrite this variable once
it has been set.
** =serverip=
serverip: TFTP server IP address; needed for tftp command.


* U-Boot Scripting Capabilities
#+begin_src sh
$ mkimage -A arm -O linux -T script -C none -a 0 -e 0 -n "boot" -d boot.cmd boot.scr
#+end_src

* Misc
** examine the boot arguments
Note: Once your system is up and running, if you have a simple shell login, you can normally examine the boot arguments that were used by the kernel for the most recent boot with the command:

#+begin_src sh
$ cat /proc/cmdline
#+end_src

* Further Reading
http://www.denx.de/wiki/view/DULG/MoreInformationFurtherReading
