#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: 浅谈设计模式
#+OPTIONS: num:nil H:2


读完GOF的[[http://www.amazon.com/Design-Patterns-Elements-Reusable-Object-Oriented/dp/0201633612/ref=sr_1_1?ie=UTF8&qid=1394635442&sr=8-1&keywords=Design+Patterns][Design Patterns: Elements of Reusable Object-Oriented
Software]]和图文并茂的[[http://www.amazon.com/First-Design-Patterns-Elisabeth-Freeman/dp/0596007124/ref=sr_1_2?ie=UTF8&qid=1394635442&sr=8-2&keywords=Design+Patterns][Head First Design Patterns]]，一时并不是那么快消化
和理解，所以试着用自己的语言总结一下。

《Design Patterns》在Introduction章中"如何选一种模式设计"一节中给出了一
张表格，5个创建模式（Abstract Factory; Builder; Factory Method;
Prototype; Singleton)，7个结构模式(Adapter; Bridge; Compose;
Decorator; Facade; Flyweight; Proxy)和11个行为模式（Chain of
Responsibility; Command; Interpreter; Iterator; Mediator; Memento;
Observer; State; Strategy; Template Method; Visitor)。

设计模式提倡：
1. 面向接口编程而不是实现；
2. 使用组合优于继承;
3. 程序模块低耦合,高内聚
4. 独立出变化部分，适应后期变化

设计模式并不是只局限OO中，主要理解设计模式的思想，但它也引入了一定的复
杂度，不要烂用设计模式，宗旨是写简单而清晰的代码。

 The best way to learn to write simple code is to write simple code!
 Patterns, like all forms of compexity, should be avoided until they
 are absolutely necessary. That's the first thing beginners need to
 learn. Not the last thing.[fn:1]

所有例子的代码在[[https://github.com/shishougang/DesignPattern-CPP][这里]]。

面向对象化的基本原则：
+ 封装那些改变的
+ 使用组合优于继承
+ 面向接口编程，而不是实现
+ 追求交互对象间的松耦合
+ 类需要可扩展，
+ 依赖与抽象类，而不是依赖具体类

* Footnotes

[fn:1] http://blog.codinghorror.com/head-first-design-patterns/



