#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Don't Make me Think 2nd
#+OPTIONS: num:nil H:2
http://www.sensible.com/secondedition

* Foreward
And while these conventions may change, there is one constant that never
changes: human nature.

* introduction
Jared Spool and his usability consulting cohorts at User Interface Engineering
(www.uie.com) even have “It depends” T-shirts.

* how we really use the web
See Jakob Nielsen’s October 1997 Alertbox column, “How Users Read on the Web” available
at www.useit.com.

I’d observed this behavior for years, but its significance wasn’t really clear to
me until I read Gary Klein’s book Sources of Power: How People Make
Decisions.

* street signs and breadcrumbs
Actually, the truth is a little more complicated than that. If you’re interested, Keith Instone has
an excellent treatment of the whole subject of Breadcrumbs at
http://user-experience.org.

* usability testing on 10 cents a day
See Jakob Nielsen’s March 2000 Alertbox column “Why You Only Need to Test with 5 Users”
at www.useit.com for a good discussion of the topic.

You can download the chapter for free at http://www.sensible.com/secondedition.
