#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Usability Overview
#+OPTIONS: num:nil H:2


* General
** Usability.gov research-based guidelines
http://usability.gov/guidelines/index.html

This excellent set of Web design and
usability guidelines, published by the
National Cancer Institute (NCI), includes
very nice examples and references to the
research each guideline is based on.
If you have a usability question, it’s always
worth checking here first to see if they’ve
covered it.
* Blogs
** Jakob Nielsen's Web site, useit.com
www.useit.com

Beginning with Usability Engineering in 1984, Jakob Nielsen has long
been usability's most articulate and thought-provoking advocate. 

Also check out his Neilsen Norman Group
reports(http://www.nngroup.com/reports/). 

** WebWord
http://www.webword.com/
John Rhodes

UsabilityViews.com
http://www.usabilityviews.com/

Chris McEvoy

These sites are currently the two best ways to keep up to date on
everything that’s being published online about usability. John Rhodes’
WebWord is more of a true blog in that he comments on the articles he
links to, but Chris McEvoy is dogged in tracking down everything worth
looking at. Between the two of them, you won’t miss anything.

* Books(Web Usability)
** Steve Krug
http://www.sensible.com/

+ Don't Make Me Think(A Common Sense Approach to Web Usability)
+ Rocket Surgery Made Easy : The Do-It-Yourself Guide to Finding and Fixing Usability Problems

** Information Architecture for the World Wide Web: Designing Large-Scale Web Site
Peter Morville (Author), Louis Rosenfeld (Author)

** Why We Buy: The Science of Shopping--Updated and Revised for the Internet, the Global Consumer, and Beyond
Paco Underhill (Author)

** Sources of Power: How People Make Decisions
Gary Klein (Author)

** The Practice of Creativity: A Manual for Dynamic Group Problem-Solving
George M. Prince (Author), Steve Krug (Foreword)

** Homepage Usability: 50 Websites Deconstructed
Jakob Nielsen (Author), Marie Tahir (Author)

** Web Application Design Handbook: Best Practices for Web-Based Software 
Susan Fowler (Author), Victor Stanwick (Author)
** Defensive Design for the Web: How to improve error messages, help, forms, and other crisis points
Matthew Linderman (Author), Jason Fried (Author)

** A Practical Guide to Usability Testing 
Joseph S. Dumas (Author), Janice C. Redish (Author)

In the same vein, Caroline Jarrett (www.formsthatwork.com/),
whom I consider the authority on designing Web forms, is
writing the definitive book on, well...designing Web forms. If it hasn’t appeared
by 2006, send her an email and pester her about it.

* Books
** Donald A. Norman
+ The Design of Everyday Things
  Donald A. Norman (Author)

+ Emotional Design: Why We Love (or Hate) Everyday Things
  Donald A. Norman (Author)

* Books about testing in general(Rocket Surgery Made Easy: The Do-It-Yourself Guide to Finding and Fixing Usability Problems)
** Handbook of Usability Testing (Second Edition) 
Jeffrey Rubin and Dana Chisnell, John Wileong one of the best on the
subject, and the new edition with co-author Dana Chisnell has made a
very good thing even better.

** A Practical Guide to Usability Testing (Revised Edition)
Joseph Dumas and Janice (Ginny) Redish, Intellect, 1999.Between them,
Joe and Ginny probably know more about usability testing than the rest
of us put together, and they both make a wonderful habit of sharing
what they know.
** Usability Testing Essentials: Ready, Set, Test!
Carol Barnum, Longman, 2010.As I write this, Carol is still working on
this major revision of her excellent 2002 book, but I know it will be
well worth reading, with new topics like accessibility and
international usability testing.
** Paper Prototyping
Carolyn Snyder, Morgan Kaufmann, 2003.As Johnny Carson would have
said, “Every single thing you need to know about paper prototyping is
in this book.” And a very good book on testing in general, too.
** Moderating Usability Tests
Joseph Dumas and Beth Loring, Morgan Kaufmann, 2008.An entire
book—based on 40 years of combined experience—about the process of
facilitating a test. A very quick and very informative read.
** Measuring the User Experience
Thomas Tullis and William Albert, Morgan Kaufmann, 2008.If you need to
do some quantitative testing (for instance, if your boss insists on a
benchmark test so you can “prove” your site has improved later), you
must read this book.
** Recruiting Without Fear
Will Schroeder, David Brittan, and Jared Spool. Usability Interface
Engineering, 43-page downloadable PDF, $49.99
http://www.uie.com/reportsJared Spool’s company has been recruiting
test participants since 1988, and this white paper explains how they
do it.
** 233 Tips and Tricks for Recruiting Users as Participants in Usability Studies 
Deborah Sova and Jakob Nielsen, Nielsen Norman Group, 144-page
downloadable PDF, $79.95 http://www.nngroup.com/reportsCo-author
Deborah Sova draws on years of experience as a recruiter to offer
plenty of sound advice.
** Letting Go of the Words: Writing Web Content That Works
Janice (Ginny) Redish, Morgan Kaufmann, 2007.Ginny’s book is the best
advice available on fixing usability problems that are the result of
less-than-perfect writing or editing—and avoiding them in the first
place. One Web writer described it to me as “life-altering” and I
think she’s right.
** Forms that Work: Designing Web Forms for Usability
Caroline Jarrett and Gerry Gaffney, Morgan Kaufmann, 2008.Almost every
Web site has some forms, and almost every Web form has usability
problems. This book is to forms what Ginny’s book is to writing.
 
* Misc
** Usability News
http://psychology.wichita.edu/surl

This newsletter is my favorite source of usability research. Published twice a
year by the Wichita State University Software Usability Research Laboratory
(SURL), it always contains several very nice, bite-sized pieces of well-thoughtout
research. The full archives are available online.
