#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Usability Overview
#+OPTIONS: num:nil H:2


* General
** Usability.gov research-based guidelines
http://usability.gov/guidelines/index.html

This excellent set of Web design and
usability guidelines, published by the
National Cancer Institute (NCI), includes
very nice examples and references to the
research each guideline is based on.
If you have a usability question, it’s always
worth checking here first to see if they’ve
covered it.
* Blogs
** Jakob Nielsen's Web site, useit.com
www.useit.com

Beginning with Usability Engineering in 1984, Jakob Nielsen has long
been usability's most articulate and thought-provoking advocate. 

Also check out his Neilsen Norman Group
reports(http://www.nngroup.com/reports/). 

** WebWord
http://www.webword.com/
John Rhodes

UsabilityViews.com
http://www.usabilityviews.com/

Chris McEvoy

These sites are currently the two best ways to keep up to date on
everything that’s being published online about usability. John Rhodes’
WebWord is more of a true blog in that he comments on the articles he
links to, but Chris McEvoy is dogged in tracking down everything worth
looking at. Between the two of them, you won’t miss anything.

* Books(Web Usability)
** Steve Krug
http://www.sensible.com/

+ Don't Make Me Think(A Common Sense Approach to Web Usability)
+ Rocket Surgery Made Easy : The Do-It-Yourself Guide to Finding and Fixing Usability Problems

** Information Architecture for the World Wide Web: Designing Large-Scale Web Site
Peter Morville (Author), Louis Rosenfeld (Author)

** Why We Buy: The Science of Shopping--Updated and Revised for the Internet, the Global Consumer, and Beyond
Paco Underhill (Author)

** Sources of Power: How People Make Decisions
Gary Klein (Author)

** The Practice of Creativity: A Manual for Dynamic Group Problem-Solving
George M. Prince (Author), Steve Krug (Foreword)

** Homepage Usability: 50 Websites Deconstructed
Jakob Nielsen (Author), Marie Tahir (Author)

** Web Application Design Handbook: Best Practices for Web-Based Software 
Susan Fowler (Author), Victor Stanwick (Author)
** Defensive Design for the Web: How to improve error messages, help, forms, and other crisis points
Matthew Linderman (Author), Jason Fried (Author)

** A Practical Guide to Usability Testing 
Joseph S. Dumas (Author), Janice C. Redish (Author)

In the same vein, Caroline Jarrett (www.formsthatwork.com/),
whom I consider the authority on designing Web forms, is
writing the definitive book on, well...designing Web forms. If it hasn’t appeared
by 2006, send her an email and pester her about it.

* Books
** Donald A. Norman
+ The Design of Everyday Things
  Donald A. Norman (Author)

+ Emotional Design: Why We Love (or Hate) Everyday Things
  Donald A. Norman (Author)

* Misc
** Usability News
http://psychology.wichita.edu/surl

This newsletter is my favorite source of usability research. Published twice a
year by the Wichita State University Software Usability Research Laboratory
(SURL), it always contains several very nice, bite-sized pieces of well-thoughtout
research. The full archives are available online.
