#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE: c++ summarize

* Bjarne Stroustrup's homepage
http://www2.research.att.com/~bs/homepage.html

  + Stroustrup's C++ Style and Technique FAQ
http://www2.research.att.com/~bs/bs_faq2.html

  + C++ Applications
http://www2.research.att.com/~bs/applications.html

* comp.lang.c++.moderated
Google group:
https://groups.google.com/forum/?fromgroups#!forum/comp.lang.c++.moderated

* 学习C++：实践者的方法[http://blog.csdn.net/pongba/article/details/1930150]
《Computer Systems：A Programmers Perspective》

《The C Programming Language》

《Accelerated C++》 Andrew Koenig是C++标准化过程中的核心人物之一

《The C++ Programming Language》


《The Pragmatic Programmer》

《C++ Coding Standard》

《Code Complete, 2nd Edition》

《你的灯亮着吗？》

C++的书，Bjarne的圣经《The C++ Programming Language》是高屋建瓴的。
《大规模C++程序设计》是挺务实的。《Accelerated C++》是最佳入门的。
《C++ Templates》是仅作参考的。《C++ Template Metaprogramming》是精力
过剩者可以玩一玩的，普通程序员碰都别碰的。《ISO.IEC C++ Standard 14882》
不是拿来读的。




* Materials
+ 免费的C++编译器

GCC http://gcc.gnu.org/install/binaries.html
MinGW http://www.mingw.org
Cygwin (GNU + cygnus + Windows) http://cygwin.com
Borland C++ Compiler 5.5 http://forms.embarcadero.com/forms/BCC32CompilerDownload
Digital Mars C/C++ Compiler for Win32 http://www.digitalmars.com
Open Watcom http://www.openwatcom.org/
Comeau C++ Online (EDG C++ front end) http://www.comeaucomputing.com/tryitout/

+ C++程序库

Boost http://www.boost.org
SGI STL http://www.sgi.com/tech/stl/
STLport http://www.stlport.org
STLSoft http://www.stlsoft.org/
Apache C++ Standard Library (STDCXX) http://stdcxx.apache.org/
ACE http://www.cs.wustl.edu/~schmidt/ACE.html
FC++ http://people.cs.umass.edu/~yannis/fc++/
Blitz++ http://sourceforge.net/projects/blitz/
MTL http://www.osl.iu.edu/research/mtl/
POOMA http://www.nongnu.org/freepooma/
CGAL http://www.cgal.org
ROOT http://root.cern.ch/root/
Loki http://sourceforge.net/projects/loki-lib/
Theron C++ concurrency library http://www.theron-library.com/
NUMA
http://lse.sourceforge.net/numa/
http://lse.sourceforge.net/numa/faq/



+ C++杂项

The C++ Standard Committee(ISO C++) http://www.open-std.org/jtc1/sc22/wg21/
Incompatibilities Between ISO C and ISO C++ http://david.tribble.com/text/cdiffs.htm
STLFilt: An STL Error Message Decryptor for C++ http://www.bdsoft.com/tools/stlfilt.html
CppUnit http://cppunit.sourceforge.net
The C++ Source http://www.artima.com/cppsource/
QT http://www.trolltech.com

+ 移动应用开发

Android http://www.android.com/
Apple https://developer.apple.com/programs/ios/develop.html
Web开发

W3Schools http://www.w3schools.com
Web浏览器

Chrome http://www.google.cn/chrome/intl/zh-CN/landing_chrome.html
Safari http://www.apple.com/safari/download/
Opera http://www.opera.com
Firefox http://www.mozillaonline.com

+ 开发者网站

Code Project http://www.codeproject.com
Code Guru http://codeguru.earthweb.com
Programmers Heaven http://www.programmersheaven.com
Experts Exchange http://www.experts-exchange.com
CSDN http://www.csdn.net

+ 期刊杂志

Dr. Dobb's Journal http://www.ddj.com
程序员 http://www.programmer.com.cn/

+ 个人主页

Bjarne Stroustrup http://www.research.att.com/~bs/
Herb Sutter http://www.gotw.ca
Scott Meyers http://www.aristeia.com
Bruce Eckel http://www.bruceeckel.com
Andrei Alexandrescu http://erdani.com/
jjhou http://jjhou.boolan.com/

+ 咨询培训

BoostPro Computing http://www.boostpro.com
BD Software http://www.bdsoft.com
Object Mentor http://www.objectmentor.com

+ 教程
  1. http://www.learncpp.com/
     LearnCpp.com is a totally free website devoted to teaching you to
     program in C++.




* c++ blog
http://www.cppblog.com/




* FAQ
http://www.comeaucomputing.com/techtalk/#constmf
