#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Certification Exam
#+OPTIONS: num:nil H:2


* CISSP
在業界頗負盛名的CISSP（Certified Information Systems Security
Professional），是(ISC)2（International Informaton Systems Security
Certification Consortium，國際資訊系統安全核準聯盟）所舉辦的資安管理認
證.

和一般技術類型認證不盡相同的是，CISSP這種管理類別的認證必須符合兩項特
定資格才能報考。首先，必須簽署由(ISC)2所制定的道德規範（Code of
Ethics），這是身為CISSP必須遵守的行為準則，同時也是CISSP的考題來源之一；
除此之外，還必須擁有5年以上和資訊安全相關的工作經驗，如果申請者是大學
相關科系畢業則縮短為3年。

CISSP是一項綜合性的資安管理證照，應試者必須在準備期間內吸收大量的資安
相關知識，CISSP包含資訊安全與風險管理（Information Security and Risk
Management）、存取控制（Access Control）、業務持續性與災害復原
（Business Continuity and Disaster Recovery Planning），以及密碼學
（Cryptography）等十項學科（Domain）。

欲參加CISSP的考試，必須先到(ISC)2的官方網站填寫報名表，以及繳交599美元
的報名費。考試題目是250題的單選題，全部是英文，作答方式和聯考一樣，以
2B鉛筆圈選，可以攜帶紙本字典進入考場查詢不懂的英文單字，所有的考試題目
必須在七個小時之內作答完畢，滿分為1,000分，不過只要取得700分以上就算通
過考試。

值得注意的是，通過考試並不表示已經取得了CISSP證照，只能算是CISSP的候選
人，在此之後，還必須持續進修，在為期三年的時間之內取得120分的進修點數，
否則必須重新參加考試。從2004年的6月1日開始，除了必須符合以上的條件之外，
還必須取得第三方專業人士的推薦才有能取得證照，有效期限為3年，在此期間
不得違反先前已經簽署的道德規範。文⊙楊啟倫

* PMP
PMP（Project Management Professional）是PMI（Project Management
Institute，專案管理學會），在1984年針對專案管理人員所提出的認證考試，
其目的在於培養專案規畫、執行與控管方面的知識，以及所需之技巧與領導能力

和CISSP相同的是，想要參加這項認項考試，必須先取得參加考試的資格，也就
是成為所謂的候選人，首先必須在PMI認可的教育機構接受35小時的課程，另外，
具備大學學歷（專科專歷不包含在內，碩士以上學位的應試資格也等同學士）的
人要有4,500小時以上的專案管理經驗，高中學歷則是7,500小時；PMI會從所有
參加考試的人員，抽出10%到20%的比例，要求提供資料進行資格審查，每位候選
人在1年內有3次考試資格，如果不幸沒有通過，則必須明年再來。

PMI發行的PMPBOK是PMP認證的指定教材，內容以PMP強調的「9大知識，5大流程」
為主，本書有正體中文的翻譯版本，不過目前的考試內容仍以英文為主，另外，
也有簡體中文的版本可供作答，根據PMI-TW（專案管理學會台灣分會）網站的說
法指出，正體中文的PMP考試已經在2007年5月向PMI提出申請，目前正在進行審
查作業中，一切順利的話，預計可在2008年1月推出。

想參加PMP考試，需要到PMI網站填寫資料報名，考試時間為4小時，題目總共有
200題，全部是英文的單選題，採用線上方式作答。200題當中有25題是做法未來
出題的參考用題，無法答對、答錯均不計分，候選人必須在剩下175題當中答對
106題以上，換句話說，越過60%的門檻才算過關。

+ http://www.preparepm.com/faq.html
+ [[https://www.project-management-prepcast.com/pmp-35-contact-hours-online-project-management-education][The Complete Guide to PMP® 35 Contact Hours of Project Management
  Education]]

* ITIL Foundation
這張ITIL Foundation是IT服務中最基本的證照，可搭配ISO 20000課程一起學習，
ISO 20000是教你如何制定目標，ITIL Foundation則是分析如何達到目標的手段，
ITIL Foundation的考試以專有名詞的解釋為主，適合一般專案經理。

目前ITIL主要是由APMG公司負責考試，再授權給旗下的EXIN及ISEB等組織，雖然
考題都出自同一題庫，但根據吳健銘與幾個考過Foundation v3證照人員的經驗
來看，ISEB的考題比EXIN容易。EXIN主要以電腦操作進行線上考試，而ISEB則是
紙本筆試，吳健銘以他本身的Foundation v3考試經驗為例，他認為EXIN的選項
是模擬兩可，要從中選出最適合的答案，多為情境式考題，但是ISEB則是直覺式
的選擇題，且多為專有詞的解釋，較容易從選項中選出正確的答案。
