#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: The Google Resume Notes
#+OPTIONS: num:nil H:2


* Chapter 2 Advanced Preparation
  Develop a tangible skill. You’ll position yourself best for these companies if you develop a
specific, tangible skill. If you want to be a marketer, learn about marketing. If you want to
be in sales, help a local organization raise money. Without a tangible skill, you’ll likely
blend in with everyone else—everyone else who’s waiting at the door to be let in.

Learn about technology. If you think you want to work at a tech company but don’t know
much about technology, now is a great time to start reading web sites like TechCrunch and
CNET, as well as company-specific blogs. Think about what the major topics are—social
networking, mobile applications, cloud computing—and ask yourself, who are the leaders
in this field, and why? In what ways are these fields changing technology, and therefore the
world?

** Get Project Experience
Project-heavy courses are an excellent way to add tangible “accomplishments” to your résumé,
even before you have the credentials to get “real” work experience. While other students are
trying to dodge these rigorous courses, you should seek them out. You should cherish them for all
the grueling, pizza-and-coffee-filled late nights that they bring.
“Remember the projects you work on,” Peter Bailey, a software engineer from Denver, adds.
“Understand them. Deconstruct them. Save samples of particularly tough problems you’ve
solved. Improve them, even if only on your own machine and on your own time. Because in the
future, interviewers will ask you many, many questions about the projects you’ve worked on.
They don’t want to know that you’re smart. They don’t want to know that you can figure out
anything with 30 seconds of Google time. They want to know that you can solve problems and
produce results—sometime before Christmas. And this holds true whether you’re fresh out of
college or a 20-year IT veteran.”

** Make an Impact
A good employee does everything that’s assigned to them; a great employee asks for more.
Perhaps the best thing you can do to get a great next job is to do a great job in your current one:

+ Think broadly. If you’re in an engineering role at a web-based
  company, is there additional debug information you can log? You
  probably (or hopefully) work with testers; how can you make their
  lives easier? The more people that you impact, the better your peer
  reviews will be and the more the company will value you.


+ Be really, really good at what you do. This doesn’t mean that you
  have to double your time at work. Perhaps it’s merely a matter of
  shutting off other distractions, or perhaps it’s a matter of being extra careful.

+ Solicit feedback proactively. Don’t wait until your midyear review
  to solicit feedback. At that point, your manager may be so
  overwhelmed that she writes your feedback hastily, at best. Asking
  for feedback early and frequently will demonstrate maturity, while
  also ensuring that you are able to quickly correct any issues.

+ Learn about other teams. Understanding the broader context of the
  company’s roles will be useful when you want a more senior position;
  for example, if you’re a developer, learn about what program
  managers do. If you’re in sales, learn about marketing. Even a
  little bit of exposure will help you a lot. It’ll show you to what
  other roles are doing and how they all fit together.





* Chapter 3 Getting in the Door
** The Informational Interview
The informational interview is an informal discussion with a company that is conducted before
the recruiting process has even begun. Usually, you approach an employee of a prospective
company and seek their advice about the role or company. Though it’s called an “informational
interview,” don’t mention the word interview when you talk to the employee.

Part of the value of the informational interview is that it’s low pressure. An employee can meet
with you and offer advice, regardless of whether the company is hiring. They get to “vet” you a
bit, and you get to evaluate them and their company.

These informational interviews are very common across tech companies, both for external
applicants and for internal candidates wishing to transfer teams.

Make sure to come with good, well-researched questions. The person will not be evaluating
your skills extensively, but they will evaluate your personality, communication, and interest.
Make sure to write a note thanking them for their time.

After this conversation, they may invite you to apply to their company and even offer to refer
you. If not, you can follow up after the interview and ask them what the best way is to apply or to
get in touch with a recruiter. If they don’t respond with an offer to help, then they are probably
not comfortable doing so for whatever reason. You will simply need to use alternative avenues to
apply for the position.

** Career Fairs
Before talking to Microsoft at the career fairs, students in the know would watch the line for a few
minutes. Each employee had his or her own system. Some would put a little mark (which was at
times as obvious as a smiley face) to indicate his invite/don’t invite decision. Others separated
résumés into good and bad piles. Either way, an observant person could learn the system. It didn’t
do them any good, of course, but it sure was nice to know the decision earlier.

Some candidates walk up with their elevator pitch all prepared: here’s who I am, here’s what
I’ve done, here’s what I’m good at, and here’s what I’d like to do.

Other candidates walk up, hand a recruiter their résumé, and just wait for the recruiter to ask
them questions. When asked what they want to do, they shrug. “Well, what kind of jobs do you
have for my major?”

“When a candidate can’t tell me what they want to do, or what they even like doing, that’s
when there’s not a good fit,” Raquel Garcia, a senior Microsoft recruiter, says. “Basically it’s like
I’m giving you a ticket to go anywhere in the world, and you can’t even tell me what continent
you want to go to.”

To maximize your chances of getting an interview invitation, follow these suggestions:
+ Do your homework. Research the companies you’re interested in and
  know which roles you’d be a good fit for. What do they look for in
  candidates? How can you address those skills in your conversation with a recruiter?
+ Prepare questions. Part of your job at a career fair is to show your
  passion for the company and the job. You should prepare a few
  open-ended questions to ask the company. This will facilitate
  conversation, as well as offer both you and the recruiter the chance
  to discover if there’s a good fit.
+ Prepare answers. A company might ask you basic questions about your
  background. You should be able to talk intelligently about your biggest accomplishments and challenges.
+ Practice your elevator pitch. The first 30 seconds with the staff at
  a career fair is your opportunity to impress. A strong candidate
  will be able to succinctly communicate their value-add.
+ Tailor your résumé. There’s no rule that says you can bring only one
  copy of your résumé to a career fair. If you’re applying for
  different types of positions, create tailored résumés for each position.
+ Dress appropriately. I once had a candidate wear a T-shirt to a
  career fair with a sexually themed phrase on it. If he can’t act
  appropriately at a first meeting, what will he be like on the job?
  Your attire at a career fair should be more or less the same as what
  you would wear to an interview.
+ Follow up. If possible, get the business card or e-mail address from
  the person you talk to, and follow up immediately after the career
  fair. You should reiterate your interest in the company, explain
  what you’d bring to the company, and attach a copy of your résumé. 

After speaking with hundreds of candidates at career fairs, most blend together in a giant mix
of résumés. One candidate, however, stands out: Alex, a precocious sophomore, who brought a
portfolio of his project work with him. On two additional sheets of paper, he provided screenshots
of his four biggest projects, with lengthier explanations that would head off some of our
questions: How did he build it? What did he enjoy? What did he learn? What was the hardest
part?

Raquel Garcia loves it when younger students like Alex approach her. “Whenever a freshman
comes up to talk to me, I always thank them for doing so. They showed guts in talking to me, and
I appreciate that. And they get early feedback on how they can start shaping their career so that, in
a year or two, they’re ready for Microsoft.”




** 
