#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE:Jolt Awards
#+OPTIONS: num:nil

Jolt大奖素有“软件业界的奥斯卡”之美誉，共设通用类图书、技术类图书、语言
和开发环境、框架库和组件、开发者网站等十余个分类，每个分类设有一个“震
撼奖”（Jolt Award）和三个“生产力奖”（Productivity Award）。一项技术产
品只有在获得了Jolt奖之后才能真正成为行业的主流，一本技术书籍只有在获得
了Jolt奖之后才能真正奠定经典的地位。赞助商Jolt可乐的广告词是“震撼全世
界”，Jolt奖就让我们看到，是谁在震撼着我们今天的世界。虽然Jolt并不起决
定作用，但代表了某种技术趋势与潮流。

JOLT大奖共设有：通用图书、技术图书、配置管理、协作工具、数据库引擎/数
据库工具、设计工具/建模、开发环境、企业工具、库/框架、移动开发工具、项
目管理工具、安全工具、测试、测试、工具、Web开发工具、Web网站/开发者网
络等分类。

+ [[http://www.drdobbs.com/joltawards/][Official website]]
+ [[http://en.wikipedia.org/wiki/Jolt_Awards#cite_note-jolt2011-0][WIKI]]
+ [[http://www.ppurl.com/forum/thread/1549/][历届「Jolt Awards」获奖书籍]]

* 2011 Books 

- Jolt Excellence Award: Continuous Delivery: Reliable Software
  Releases through Build, Test, and Deployment Automation, by Jez
  Humble and David Farley

- Jolt Productivity Award: Mining the Social Web: Analyzing Data from
  Facebook, Twitter, LinkedIn, and Other Social Media Sites, by
  Matthew A. Russell

- Jolt Productivity Award: Seven Languages in Seven Weeks: A Pragmatic
  Guide to Learning Programming Languages, by Bruce Tate

- Jolt Finalist: The Joy of Clojure: Thinking the Clojure Way, by
  Michael Fogus and Chris Houser

- Jolt Finalist: The Art of Computer Programming, Volume 4A:
  Combinatorial Algorithms, Part 1, by Donald Knuth

- Jolt Finalist: Domain-Specific Languages by Martin Fowler with
  Rebecca Parsons

* 2010 Books

- Jolt Excellence Award: Masterminds of Programming: Conversations with the Creators of Major Programming Languages, by Federico Biancuzzi and Shane Warden [2]
- Jolt Productivity Award: Hello World! Computer Programming for Kids and Other Beginners, by Warren D. Sande and Carter Sande [3]
- Jolt Productivity Award: SDLC 3.0: Beyond a Tacit Understanding of Agile, by Mark Kennaley 

* 2009 Books

** General
- Jolt Award: Adrenaline Junkies and Template Zombies: Understanding Patterns of Project Behavior, by Tom Demarco, Peter Hruschka, Tim Lister, Suzanne Robertson, James Robertson, and Steve McMenamin
- Productivity Award: Emergent Design: The Evolutionary Nature of Professional Software Development, by Scott L. Bain
- Productivity Award: Intellectual Property and Open Source: A Practical Guide to Protecting Code, by Van Lindberg
** Technical
- Jolt Award: Real World Haskell, by Bryan O'Sullivan, John Goerzen, and Don Stewart
- Productivity Award: High Performance MySQL: Optimization, Backups, Replication, and More, by Baron Schwartz, Peter Zaitsev, Vadim Tkachenko, Jeremy Zawodny, Arjen Lentz, and Derek J. Balling
- Productivity Award: Programming in Scala, by Martin Odersky, Lex Spoon, and Bill Venners

* 2008 Books 

** General
- Jolt Winner: Beautiful Code: Leading Programmers Explain How They Think by Andrew Oram
- Productivity Winner: Manage It!: Your Guide to Modern, Pragmatic Project Management by Johanna Rothman
- Productivity Winner: The Myths of Innovation by Scott Berkun
- Productivity Winner: Release It!: Design and Deploy Production-Ready Software by Michael T. Nygard
** Technical
- Jolt Winner: Continuous Integration: Improving Software Quality and Reducing Risk by Paul M. Duvall
- Productivity Winner: xUnit Test Patterns: Refactoring Test Code by Gerard Meszaros
- Productivity Winner: Head First SQL: Your Brain on SQL by Lynn Beighley
- Productivity Winner: The Rails Way by Obie Fernandez
* 2007 Books 

** General
- Jolt Winner: Agile Software Development: The Cooperative Game by Alistair Cockburn
- Productivity Winner: Catastrophe Disentanglement: Getting Software Projects Back on Track by E. M. Bennatan
- Productivity Winner: Practices of an Agile Developer: Working in the Real World by Venkat Subramaniam
- Productivity Winner: Software Estimation: Demystifying the Black Art: The Black Art Demystified by Steve McConnell
** Technical
- Jolt Winner: Head First Object-Oriented Analysis and Design: A Brain Friendly Guide to OOA&D by Brett McLaughlin
- Productivity Winner: Code Quality: The Open Source Perspective by Diomidis Spinellis
- Productivity Winner: Refactoring Databases: Evolutionary Database Design by Scott W. Ambler
- Productivity Winner: CSS: The Missing Manual by David Sawyer McFarland
* 2006 Books

** General
- Jolt Award: Prefactoring, by Ken Pugh
- Productivity Award: Innovation Happens Elsewhere: Open Source as Business Strategy, by Ron Goldman and Richard P. Gabriel
- Productivity Award: Producing Open Source Software: How to Run a Successful Free Software Project, by Karl Fogel
- Productivity Award: The Art of Project Management, by Scott Berkun
** Technical
- Jolt Award: Agile Web Development with Rails, by Dave Thomas, David Hansson, Leon Breedt, and Mike Clark
- Productivity Award: Framework Design Guidelines: Conventions, Idioms, and Patterns for Reusable .NET Libraries, by Krzysztof Cwalina and Brad Abrams
- Productivity Award: Practical Common Lisp, by Peter Seibel
- Productivity Award: Why Programs Fail: A Guide to Systematic Debugging, by Andreas Zeller
* 2005 Books

** General
- Jolt Award: Head First Design Patterns, by Elisabeth Freeman, Eric Freeman, Bert Bates, and Kathy Sierra
- Productivity Award: Joel on Software, by Joel Spolsky
- Productivity Award: Refactoring to Patterns, by Joshua Kerievsky
- Productivity Award: Software Factories: Assembling Applications with Patterns, Models, Frameworks, and Tools, by Jack Greenfield, Keith Short, Steve Cook, Stuart Kent, and John Crupi
** Technical
- Jolt Award: Better, Faster, Lighter Java, by Bruce A. Tate and Justin Gehtland
- Productivity Award: C++ Coding Standards: 101 Rules, Guidelines, and Best Practices, by Herb Sutter and Andrei Alexandrescu
- Productivity Award: Hibernate: A Developer's Notebook, by James Elliott
- Productivity Award: Java Developer's Guide to Eclipse, Second Ed., by Jim D'Anjou, Scott Fairbrother, Dan Kehn, John Kellerman, and Pat McCarthy
* 2004 Books

** General
- Jolt Award: Waltzing with Bears: Managing Risk on Software Projects, by Tom DeMarco and Timothy Lister
- Productivity Award: The Art of UNIX Programming, Eric S. Raymond
- Productivity Award: Lean Software Development: An Agile Toolkit, by Mary Poppendieck and Tom Poppendieck
- Productivity Award: Pragmatic Starter Kit, by Dave Thomas and Andy Hunt
** Technical
- Jolt Award: Test-Driven Development: A Practical Guide, by David Astels
- Productivity Award: About Face 2.0, by Alan Cooper and Robert Reimann
- Productivity Award: Agile Database Techniques: Effective Strategies for the Agile Software Developer, by Scott W. Ambler
- Productivity Award: Code Reading: The Open Source Perspective, by Diomidis Spinellis
* 2003 Books

** General
- Jolt Award: Agile Software Development: Principles, Patterns and Practices, by Robert C. Martin
- Productivity Award: Documenting Software Architectures: Views and Beyond, by Paul Clements, Felix Bachmann, Len Bass, David Garlan, James Ivers, Reed Little, Robert Nord, and Judith Stafford
- Productivity Award: Patterns of Enterprise Application Architecture, by Martin Fowler
- Productivity Award: Test-Driven Development: By Example, by Kent Beck
** Technical
- Jolt Award: Thinking in Java, 3rd Ed., by Bruce Eckel
- Productivity Award: Understanding Web Services, by Eric Newcomer
- Productivity Award: Core Java 2, Vol. 1: Fundamentals, 6th Ed., by Cay Horstmann and Gary Cornell
- Productivity Award: PHP and MySQL Web Development, by Luke Welling and Laura Thompson
* 2002 Books

- Jolt Award: Effective Java, by Joshua Bloch
- Productivity Award: Agile Software Development, by Alistair Cockburn
- Productivity Award: Software Craftsmanship, by Pete McBreen
- Productivity Award: Under Pressure and On Time,by Ed Sullivan
* 2001 Books

- Jolt Award: Adaptive Software Development, by James A. Highsmith III
- Productivity Award: Don't Make Me Think! A Common Sense Approach to Web Usability, by Steve Krug
- Productivity Award: Secrets and Lies, by Bruce Schneier
- Productivity Award: Writing Effective Use Cases, by Alistair Cockburn
* 2000 Books

- Jolt Award: Software For Use: A Practical Guide to the Models and Methods of Usage Centered Design, by Larry Constantine and Lucy Lockwood
- Productivity Award: Extreme Programming Explained, by Kent Beck
- Productivity Award: Software Requirements, by Karl E. Wiegers
- Productivity Award: After the Gold Rush: Creating a True Profession of Software Engineering, by Steve McConnell
* 1999 Books

- Jolt Award: Component Software: Beyond Object-Oriented Programming, by Clemens Szyperski
- Productivity Award: AntiPatterns: Refactoring Software, Architectures, and Projects in Crisis, by William Brown, Raphael Malveau, Hays McCormick, and Thomas Mowbray
- Productivity Award: Software Architecture in Practice, by Len Bass, Paul Clements, Rick Kazman, and Ken Bass
- Productivity Award: Thinking in Java, by Bruce Eckel
* 1998 Books

- Jolt Award: Object-Oriented Software Construction, Second Ed., by Bertrand Meyer
- Productivity Award: The Deadline: A Novel about Project Management, by Tom DeMarco
- Productivity Award: UML Distilled, by Martin Fowler with Kendall Scott
- Productivity Award: Building Object Applications that Work, by Scott Ambler
* 1997 Books

- Jolt Award: Rapid Development: Taming Wild Software Schedules, by Steve McConnell
- Productivity Award: The Distributed Objects Survival Guide, by Robert Orfali, Dan Harkey, and Jeri Edwards
- Productivity Award: Creating a Software Engineering Culture, by Karl E. Wiegers
- Productivity Award: Pattern-Oriented Software Architecture: A System of Patterns, by Frank Buschmann, Regine Meunier, Hans Rohnert, Peter Sommerlad, and Michael Stal
* 1996 Books

- Jolt Award: Thinking in C++, by Bruce Eckel
- Productivity Award: About Face: The Essentials of User Interface Design, by Alan Cooper
- Productivity Award: A Discipline for Software Engineering, by Watts Humphrey
- Productivity Award: What Every Programmer Should Know About Object-Oriented Design, by Meilir Page-Jones
* 1995 Books

- Jolt Award: Essential Client/Server Survival Guide, by Robert Orfali, Dan Harkey, and Jeri Edwards
- Productivity Award: Debugging the Development Process, by Steve Maguire
- Productivity Award: Design Patterns, by Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides
- Productivity Award: The Design and Evolution of C++, by Bjarne Stroustrup
* 1994 Books

- Jolt Award: Code Complete, by Steve McConnell
- Jolt Award: Object-Oriented Design and Analysis with Applications, Second Ed., by Grady Booch
- Productivity Award: Applied Cryptography, by Bruce Schneier
- Productivity Award: The Design and Evolution of C++, by Bjarne Stroustrup
- Productivity Award: Programming on Purpose, by P. J. Plauger
- Productivity Award: Writing Solid Code, by Steve Maguire
* 1993 Books

- Jolt Award: Undocumented Windows, by Andrew Schulman, David Maxey, and Matt Pietrek
- Jolt Award: Decline and Fall of the American Programmer, by Ed Yourdon
- Productivity Award: Object-Oriented Software Engineering: A Use-Case Driven Approach, by Ivar Jacobson, Magnus Christerson, Patrik Jonsson, and Gunnar Overgaard
- Productivity Award: Literate Programming, by Donald Knuth
- Productivity Award: Effective C++, by Scott Meyers
* 1992 Books

- Jolt Award: Object-Oriented Design with Applications, by Grady Booch
- Productivity Award: Advanced C++: Programming Styles and Idioms, by James Coplien
- Productivity Award: Object-Oriented Modeling and Design, by James R. Rumbaugh, Michael R. Blaha, William Lorensen, Frederick Eddy, and William Premerlani
- Productivity Award: Object Lifecycles: Modeling the World in States, by Sally Shlaer and Steve Mellor
* 1991 Books

- Jolt Award: Annotated C++ Reference Manual, by Margaret Ellis and Bjarne Stroustrup
- Productivity Award: The Art of Human-Computer Interface Design, edited by Brenda Laurel
- Productivity Award: Programming Windows, 2nd Ed., by Charles Petzold
- Productivity Award: Turbo C++ DiskTutor, by Greg Voss and Paul Chui
