#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE: Linux Overview
#+OPTIONS: num:nil H:2
* General
** main sites
http://wiki.linux.org.hk/
http://www.linux.org.tw/

** linux journal
http://www.linuxjournal.com/

** Linux Documentation
http://linux.die.net/

** http://linuxcommand.org/

** Davin's collection of unix programming links
http://www.cse.buffalo.edu/~milun/unix.programming.html


** other [fn:2]
http://www.fanqiang.com 
http://www.Linuxhq.com/，Linux总部，主要负责核心的开发工作。
http://freesoft.cei.gov.cn/，中国Linux的资源宝藏
http://xchina.cLinux.org/，包括Linux程序下载，窍门，技术资料，内容丰富。
http://www.Linuxaid.com.cn/，提供技术支持服务，也有很多面向初学者的资料
http://www.Linux.org.cn/
http://www.cLinux.org/，收集了各类Linux中文资料
http://lark.ihep.ac.cn/，内容包罗万象，有中文软件，软件仓库等。
http://Linux.joyo.com:3000/，有很多内容，还可以打包下载Linux公报。
http://home.jjinfo.com/personal/Linuxboy/，Linux发展介绍及资源荟萃。
http://www.xteamLinux.com.cn/
http://www.turboLinux.com.cn/
http://www.hklug.org/，了解香港Linux的好网站
http://chinese.Linux.org.tw/，为台湾中文化Linux计划(Chinese Linux Project)正式网站。
http://cle.Linux.org.tw/CLE/，中文Linux扩展(CLE)，基于Red Hat和KDE的中文解决
http://ccss.cc.nccu.edu.tw/
http://www.Linuxers.com.tw/，一本不错的Linux网络杂志。
http://www.redhat.com/，是搜索Linux各类资源的上好网站。
http://www.pht.com/，Turbo Linux 国外的官方网站
http://li.org/，有大量的Linux资源列表。
http://www.Linuxresources.com/，Linux网站，软件，文档，支持等等，内容应有尽有。
http://sunsite.unc.edu/Linux－source/，包含了几乎所有Linux分类的源代码。
http://Linux.box.ck/，资源全面的Linux宝箱。
http://www.Linuxsupportline.com/，Linux网上技术支持的网站。
http://lsd.Linux.cz/，Linux驱动程序的源代码
http://www.kde.org/，KDE的大本营。
http://www.kernel.org，齐全的Linux的核心的各种版本。
http://www.sendmail.org，Linux世界下最广泛使用的软件之一，这里就是它的老家。
ftp://sunsite.unc.edu/pub/Linux/，有着极丰富的软件资源
http://www.slackware.com/，Slackware Linux的网站，
LINUX学习网（从初学到高级）
http://Linux.ccpi.gov.cn/Linux/，有很多Linux安装、管理、释疑和指南类文章。
http://www.Linuxforum.net/，国内Linux爱好者的一个相互学习和交流的场所。
http://www.Linux.org.tw/，台湾的Linux爱好者组织，列有翻译的Linux HOWTO 中文版。
http://evon.el.cycu.edu.tw/，列有Linux简介及操作说明。
http://www.tvds.com.tw/Linux/，定期推出 Linux 应用的相关文章同时有线上讨论区。
http://www.Linux.com/，学习Linux的最好网站，也是Linux使用经验
http://www.caldera.com/，Caldera 的官方网站
http://www.Linux－howto.com/，查找Linux－Howto的最佳网站，包括了最
新最全的Linux－Howto的各种版本。
http://www.Linuxhelp.org/，最大最全的Linux在线帮助网站
http://www.Linuxgazette.com/，著名的免费在线杂志技巧，是Linux用户交流中心之一
http://www.Linuxfocus.org/，免费电子杂志《Linux focus》
，特色是每期集中讨论一个话题。
http://www.Linuxjournal.com/，很棒的Linux专业杂志
LINUX论坛
http://www.chinaunix.net 
http://Linux.inhk.net/，包含新闻、初学入门、技巧、资源和讨论等。
http://www.cLinuxworld.com/，中文门户网站，设有论坛、新闻栏目，还提供主页空间。
http://Linux.arecool.net/ ，有很丰富的中文分类文档。还有论坛，编程等。
http://www.Linux.org/，最权威的Linux网站， 文章讨论无所不包，软件硬件应有尽有。
http://bbs.tsinghua.edu.cn 水木清华BBS
http://bbs.ustc.edu.cn 上海交大BBS
http://bbs.sjtu.edu.cn 中国科技大学BBS
http://news.freesoft.cei.gov.cn，由宫敏博士主持，人气很旺，Linux爱好者的交流好场所。
http://news.cLinux.ml.org，是国内规模较大的新闻服务器，
http://cn.bbs.comp.Linux是各大学BBS站Linux版与News的连接。
http://202.38.64.2，国内最大的Linuxv新闻组之一
http://www.gb2312.com ，下载密码是 www.gb2312
著名的FTP网站：
ftp://ftp.cdrom.com　　
ftp://ftp.pku.edu.cn/pub/slackware
ftp://ftp.ihep.ac.cn/pub/Linux
ftp://ftp.synet.edu.cn/pub/Linux
ftp://ftp.sepc.ac.cn/pub/Linux
ftp://ftp.buptnet.edu.cn/pub/slackware　
ftp://net.tamu.edu/pub/Linux
ftp://freesoft.cei.gov.cn/pub/Linux，国内最大的Linux FTP站。
BSD学习网
http://fbsd.8800.org/freebsd.lab.mlc.edu.tw/default.htm
http://fbsd.8800.org/freebsd.lab.mlc.edu.tw/index.html
http://freebsd.sinica.edu.tw
http://ns1.study-area.org/phpBB/
http://ohaha.ks.edu.tw/
http://www.gocar.idv.tw/
http://w3.fjy.idv.tw/index.htm
http://freebsd.csie.nctu.edu.tw/
http://person.zj.cninfo.net/~syx/index.html
http://redhat.ecenter.idv.tw/bbs/forumdisplay.php?s=a3f86419d48f60d78734f30e406fe757&forumid=65
http://www.freebsd.org.hk/modules/news/
http://freebsd.ntu.edu.tw/
http://www.freebsd.org.hk/modules/news/

BSD资源网
ftp://ftp2.freebsd.org/
ftp://freebsd.nctu.edu.tw/
http://www.yesnew.com/~yangyi/chandbook.zip
http://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/index.html
http://www.yesnew.com/~yangyi/The_Complete_FreeBSD.zip
http://www.yesnew.com/~yangyi/TCP-IP1.zip
http://www.freebsdchina.org
SOLARIS（X86、SPARC）
http://202.108.44.140
ftp://202.108.44.140 user:unix2002 pass:unix2002
OTHERS:
http://linux.softhouse.com.cn 软件屋-Linux之家http://www.bluepoint.com.cn 蓝点Linux
http://cnheasa.org/linux Linux 中文资料
http://linux.ccpi.gov.cn/linux Linux操作指南 http://www.linuxzyd.com Linux专营
http://www.turbolinux.com.cn Turbo
http://www.linuxaid.com.cn Linux技术支持网站http://member.netease.com/~yzp Linux工作室http://www.linuxforum.net/ 中国Linux论坛
http://www.redflag-linux.com 红旗Linux
http://www.pocketix.com 嵌入式Linux
http://www.xteamlinux.com.cn XteamLinux
http://timzen.go.163.com Linux菜鸟入门
http://linux.tcpip.com.cn Linux非常新闻
http://zlinux.spedia.net JJ的Linux世界
http://lslnet.com/linux 自由软件Linux
http://member.netease.com/~yzp Linux工作室
http://giny.4y.com.cn/ 自由的精灵
http://linuxcity.com.cn/linuxstore Linux 精品店
http://www.linux21cn.com/ 21世纪linux
http://www.asplinux.com.cn asplinux中国网站
http://www.ibm.com/developerworks/cn/linux/ IBM--linux专区
http://www.medboo.com/~jj jj的linux世界
http://linux21cn.com 21世纪linux
http://www.linuxnow.com linux now
http://www.linux.org linux www
http://www.linuxgazette.com linux gazette
http://www.linux.org.cn linux 中国用户协会
http://www.linuxbyte.net/softwared.php LinuxByte 软件中心
http://linuxcity.com.cn/linuxstore/cd/cd.asp linuxcd精品光盘店
http://www.linuxhq.com Linux HeadQuarters
http://www.linuxmall.com LinuxMall.com
http://linux.ccpi.gov.cn linux操作指南
http://www.linuxdby.com/ linux大本营站
http://www.cstc.org.cn/anounce/linux/index.asp linux开放实验室 http://www.linuxcd.com.cn linux刻录网
http://free.prohosting.com/~lslnet linux蓝色小组
http://netsword.net/linux linux学习
http://www.linuxeden.com linux伊甸园
http://www.nodevice.com linux园地
http://linuxhome.my163.com linux之家(my163.com
http://members.tripod.com/~clinux linux中文手册
http://www.linuxzy.com linux专营
http://www.linuxwatch.org Linuxwatch
http://www.penguin64.com.cn/ penguin64中文网
http://www.redhat.com Red Hat
http://www.suse.com SuSE LINUX
http://www.unixaid.net unix中文社区
http://www.263bbs.net/ 博识网
http://www.westdata.net/linux/ 大漠驼铃--中文Linux学习
http://www.rce.com.cn/ 红旗linux培训与考试中心
http://www.hhcn.org 华恒嵌入式Linux技术资料网站
http://www.lslnet.com/linux 蓝森林
http://www.mamiyami.com 麻米亚资讯站
http://www.freelamp.com FreeLAMP.com
http://www.sinolinux.com 思凌网
http://linux.online.tj.cn Linux中心
http://badfish.3322.net Badfish's Linux
http://www.wanhenet.com 嵌入式Linux开发网
http://www.linuxbyte.net LinuxByte
http://www.cmpp.net 中国linux论坛
http://www.yaboy.org yaboy.org
http://www.iwork.f2s.com linux computing
http://www.linuxfocus.org linux focus
http://www.linuxjournal.com linux journal
http://www.yesky.com/72350081310785536/index.shtml 天极网--Linux园地
http://linux.ccidnet.com 赛迪网--Linux
* Bash
** learning the shell
http://linuxcommand.org/lc3_learning_the_shell.php
** Writing Shell Scripts
http://linuxcommand.org/lc3_writing_shell_scripts.php
** The Bash Reference Manual
http://www.gnu.org/software/bash/manual/bash.html

Perhaps in response to the usability issues found in the bash man page, the GNU Project produced the Bash Reference Manual. You can think of it as the bash man page translated into human readable form. While it lacks a tutorial focus and contains no usage examples, it is much easier to read and is more usefully organized than the bash man page.

** Greg's Wiki
http://mywiki.wooledge.org/

The bash man page and the Bash Reference Manual both extensively document the features found in bash. However, when we want a description of bash behavior, different resources are needed. The best by far is Greg's Wiki. This site covers a variety of topics, but of particular interest to us are the Bash FAQ which contains over one hundred frequently asked questions about bash, the Bash Pitfalls which describes many of the common problems script writers encounter with bash, and the Bash Guide, a useful set of tutorials for bash users. There are also several fun to read rants.

** Bash Hacker's Wiki
http://wiki.bash-hackers.org/start

Like Greg's Wiki, the Bash Hackers Wiki provides many different articles relating to bash, its features, and its behavior. Included are some useful tutorials on various programming techniques and issues with scripting with bash. While the writing is, at times, a little chaotic, it does contain useful information.

** Chet Ramey's Bash Page
http://tiswww.case.edu/php/chet/bash/bashtop.html

Chet Ramey is the current maintainer of bash and he has his own page. On it, you can find version information, latest news, and other things. The most useful document on the Bash Page is its version of the Bash FAQ. The NEWS file contains a concise list of features that have been added to each version of bash.

** Heiner's SHELLdorado
http://www.shelldorado.com/

SHELLdorado is a shell scripting education site. It features tutorials on various scripting topics and a large collection of shell scripts and functions.

** Advanced Bash Scripting HOWTO
http://www.tldp.org/LDP/abs/html/index.html

The Advanced Bash Scripting HOWTO is a detailed look at bash shell programming. A thoughtful treatment with lots of examples and exercises. A good companion piece for the LinuxCommand.org tutorials.

** The Bash Prompt HOWTO
http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/index.html

The Bash Prompt HOWTO is a surprisingly interesting discussion of all the things you can make the prompt do.

** Linux From Scratch
http://www.linuxfromscratch.org/

The Linux From Scratch tutorial will step you through the process of
building a complete Linux system from source code.[fn:1]

*

* Unix
** System Administration
http://h30097.www3.hp.com/docs/base_doc/DOCUMENTATION/V40F_HTML/APS2RFTE/TITLE.HTM

This guide describes the tasks you perform in order to maintain a
Compaq Tru64 UNIX (formerly DIGITAL UNIX) operating system running on
an Alpha server or workstation. You use UNIX commands, scripts, and
the SysMan graphical user interfaces to perform the system
administration tasks described in this manual. 

* Footnotes

[fn:1] http://linuxcommand.org/lc3_resources.php

[fn:2] http://hi.baidu.com/operationsystem/blog/item/8b0dca323340cc45ac4b5fe3.html
 
