#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE: Summarize
#+OPTIONS: num:nil
* General
** main sites
http://wiki.linux.org.hk/
http://www.linux.org.tw/

** linux journal
http://www.linuxjournal.com/

** Linux Documentation
http://linux.die.net/

** http://linuxcommand.org/

** Davin's collection of unix programming links
http://www.cse.buffalo.edu/~milun/unix.programming.html

* Bash
** learning the shell
http://linuxcommand.org/lc3_learning_the_shell.php
** Writing Shell Scripts
http://linuxcommand.org/lc3_writing_shell_scripts.php
** The Bash Reference Manual
http://www.gnu.org/software/bash/manual/bash.html

Perhaps in response to the usability issues found in the bash man page, the GNU Project produced the Bash Reference Manual. You can think of it as the bash man page translated into human readable form. While it lacks a tutorial focus and contains no usage examples, it is much easier to read and is more usefully organized than the bash man page.

** Greg's Wiki
http://mywiki.wooledge.org/

The bash man page and the Bash Reference Manual both extensively document the features found in bash. However, when we want a description of bash behavior, different resources are needed. The best by far is Greg's Wiki. This site covers a variety of topics, but of particular interest to us are the Bash FAQ which contains over one hundred frequently asked questions about bash, the Bash Pitfalls which describes many of the common problems script writers encounter with bash, and the Bash Guide, a useful set of tutorials for bash users. There are also several fun to read rants.

** Bash Hacker's Wiki
http://wiki.bash-hackers.org/start

Like Greg's Wiki, the Bash Hackers Wiki provides many different articles relating to bash, its features, and its behavior. Included are some useful tutorials on various programming techniques and issues with scripting with bash. While the writing is, at times, a little chaotic, it does contain useful information.

** Chet Ramey's Bash Page
http://tiswww.case.edu/php/chet/bash/bashtop.html

Chet Ramey is the current maintainer of bash and he has his own page. On it, you can find version information, latest news, and other things. The most useful document on the Bash Page is its version of the Bash FAQ. The NEWS file contains a concise list of features that have been added to each version of bash.

** Heiner's SHELLdorado
http://www.shelldorado.com/

SHELLdorado is a shell scripting education site. It features tutorials on various scripting topics and a large collection of shell scripts and functions.

** Advanced Bash Scripting HOWTO
http://www.tldp.org/LDP/abs/html/index.html

The Advanced Bash Scripting HOWTO is a detailed look at bash shell programming. A thoughtful treatment with lots of examples and exercises. A good companion piece for the LinuxCommand.org tutorials.

** The Bash Prompt HOWTO
http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/index.html

The Bash Prompt HOWTO is a surprisingly interesting discussion of all the things you can make the prompt do.

** Linux From Scratch
http://www.linuxfromscratch.org/

The Linux From Scratch tutorial will step you through the process of
building a complete Linux system from source code.[fn:1]

*

* Footnotes

[fn:1] http://linuxcommand.org/lc3_resources.php
 
