#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Virtex-6 FPGA OverView
#+OPTIONS: num:nil H:2


* Notes
** UG360 Virtex-6 FPGA Configuration User Guide Notes
*** OverView

These configuration pins serve as the interface
for a number of different configuration modes:

+ Master-Serial configuration mode
+ Slave-Serial configuration mode
+ Master SelectMAP (parallel) configuration mode (x8 and x16)
+ Slave SelectMAP (parallel) configuration mode (x8, x16, and x32)
+ JTAG/boundary-scan configuration mode
+ Master Serial Peripheral Interface (SPI) flash configuration mode
+ Master Byte Peripheral Interface Up or Down (BPI-Up or BPI-Down) flash
  configuration mode (x8 and x16 only)

The terms Master and Slave refer to the direction of the configuration
clock (CCLK):
+ In Master configuration modes, the Virtex-6 device drives CCLK from an internal
  oscillator. To select the desired frequency, BitGen -g ConfigRate option is used. The
  BitGen section of UG628, Command Line Tools User Guide provides more
  information.
+ In Slave configuration modes, CCLK is an input.


