#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Firmware Development
#+OPTIONS: num:nil

http://wiki.cyanogenmod.org/w/Development#The_CyanogenMod_Dev_Center
* Overview
** http://www.virtuousrom.com/p/roms.html
** CyanogenMod
CyanogenMod is an aftermarket firmware for a number of cell phones
based on the open-source Android operating system.

+ https://github.com/CyanogenMod
+ http://www.cyanogenmod.com/
+ Gerrit - http://r.cyanogenmod.com/
+ Freenote - #cyanogenmod (-dev)
+ Forum - http://forum.cyanogenmod.com/
+ Wiki - http://wiki.cyanogenmod.com/

** Blog
+ http://www.androidenea.com/2009/08/init-process-and-initrc.html

* The init process and init.rc
http://www.androidenea.com/2009/08/init-process-and-initrc.html


* Some commands
#+beign_src sh
$ adb reboot bootloader


#+end_src
* cyanogenmode notes
** External Android Development Resources (Master List) – The Internet Helps You Learn. Free links that teach Java, C, C++, and all things Android
http://wiki.cyanogenmod.org/w/Doc:_Development_Resources

*** Learn about the build system (GNU Make)
+ Android Build System
  http://www.kandroid.org/online-pdk/guide/build_system.html

+ GNU Make manual http://www.gnu.org/software/make/manual/make.html

+ The Android-Building Group
  https://groups.google.com/forum/?fromgroups#!forum/android-building

*** Learn about the Android kernel (based on the Linux kernel)
+ How To Build A Kernel
  http://source.android.com/source/building-kernels.html

*** Learn about the Android Frameworks
+ The official Android Developer Site
  http://developer.android.com/index.html

+ Android classes http://developer.android.com/reference/classes.html

** Team member
http://wiki.cyanogenmod.org/w/Devs
** adb intro
http://wiki.cyanogenmod.org/w/Doc:_adb_intro
*** What is adb?
ADB ("adb"), or the Android Debug Bridge, is a development tool
included with the Android SDK (Software Developer Kit), which allows
for communication from an Android device (such as a phone or tablet)
to a personal computer, and vice-versa. 
*** Popular adb commands
#+begin_src sh
adb shell -- this command establishes a shell interface for establishing a command-line session with the device. 

adb push <local> <remote> -- this command pushes a local file on the computer to a remote file on the device. You can include the full path to either the local or remote file.

adb pull <remote> [<local>] -- this command will pull a remote file on the device (you can include the path) to either a specified location on the computer or, if no destination is specified, to the current directory where the command was issued.

adb logcat -- this command allows you to view the device log in real time. It is also very useful for discovering and reporting bugs.

adb install <file> -- this is used to "side-load" apps (in their .apk format) to the device.
#+end_src
*** "Device not found" errors
Sometimes adb can't find your device. One solution is to run adb
kill-server and then adb start-server as root or Administrator to
restart the adb daemon with elevated privileges.


*** Adb --help
Android Debug Bridge version 1.0.31
#+begin_src sh
-d                            - directs command to the only connected USB device
                                returns an error if more than one USB device is present.
-e                            - directs command to the only running emulator.
                                returns an error if more than one emulator is running.
-s <specific device>          - directs command to the device or emulator with the given
                                serial number or qualifier. Overrides ANDROID_SERIAL
                                environment variable.
-p <product name or path>     - simple product name like 'sooner', or
                                a relative/absolute path to a product
                                out directory like 'out/target/product/sooner'.
                                If -p is not specified, the ANDROID_PRODUCT_OUT
                                environment variable is used, which must
                                be an absolute path.
devices [-l]                  - list all connected devices
                                ('-l' will also list device qualifiers)
connect <host>[:<port>]       - connect to a device via TCP/IP
                                Port 5555 is used by default if no port number is specified.
disconnect [<host>[:<port>]]  - disconnect from a TCP/IP device.
                                Port 5555 is used by default if no port number is specified.
                                Using this command with no additional arguments
                                will disconnect from all connected TCP/IP devices.

device commands:
 adb push <local> <remote>    - copy file/dir to device
 adb pull <remote> [<local>]  - copy file/dir from device
 adb sync [ <directory> ]     - copy host->device only if changed
                                (-l means list but don't copy)
                                (see 'adb help all')
 adb shell                    - run remote shell interactively
 adb shell <command>          - run remote shell command
 adb emu <command>            - run emulator console command
 adb logcat [ <filter-spec> ] - View device log
 adb forward <local> <remote> - forward socket connections
                                forward specs are one of: 
                                  tcp:<port>
                                  localabstract:<unix domain socket name>
                                  localreserved:<unix domain socket name>
                                  localfilesystem:<unix domain socket name>
                                  dev:<character device name>
                                  jdwp:<process pid> (remote only)
 adb jdwp                     - list PIDs of processes hosting a JDWP transport
 adb install [-l] [-r] [-s] [--algo <algorithm name> --key <hex-encoded key> --iv <hex-encoded iv>] <file>
                              - push this package file to the device and install it
                                ('-l' means forward-lock the app)
                                ('-r' means reinstall the app, keeping its data)
                                ('-s' means install on SD card instead of internal storage)
                                ('--algo', '--key', and '--iv' mean the file is encrypted already)
 adb uninstall [-k] <package> - remove this app package from the device
                                ('-k' means keep the data and cache directories)
 adb bugreport                - return all information from the device
                                that should be included in a bug report.

 adb backup [-f <file>] [-apk|-noapk] [-shared|-noshared] [-all] [-system|-nosystem] [<packages...>]
                              - write an archive of the device's data to <file>.
                                If no -f option is supplied then the data is written
                                to "backup.ab" in the current directory.
                                (-apk|-noapk enable/disable backup of the .apks themselves
                                   in the archive; the default is noapk.)
                                (-shared|-noshared enable/disable backup of the device's
                                   shared storage / SD card contents; the default is noshared.)
                                (-all means to back up all installed applications)
                                (-system|-nosystem toggles whether -all automatically includes
                                   system applications; the default is to include system apps)
                                (<packages...> is the list of applications to be backed up.  If
                                   the -all or -shared flags are passed, then the package
                                   list is optional.  Applications explicitly given on the
                                   command line will be included even if -nosystem would
                                   ordinarily cause them to be omitted.)


 adb restore <file>           - restore device contents from the <file> backup archive

adb help                     - show this help message
 adb version                  - show version num

scripting:
 adb wait-for-device          - block until device is online
 adb start-server             - ensure that there is a server running
 adb kill-server              - kill the server if it is running
 adb get-state                - prints: offline | bootloader | device
 adb get-serialno             - prints: <serial-number>
 adb get-devpath              - prints: <device-path>
 adb status-window            - continuously print device status for a specified device
 adb remount                  - remounts the /system partition on the device read-write
 adb reboot [bootloader|recovery] - reboots the device, optionally into the bootloader or recovery program
 adb reboot-bootloader        - reboots the device into the bootloader
 adb root                     - restarts the adbd daemon with root permissions
 adb usb                      - restarts the adbd daemon listening on USB
 adb tcpip <port>             - restarts the adbd daemon listening on TCP on the specified port

networking:
 adb ppp <tty> [parameters]   - Run PPP over USB.
Note: you should not automatically start a PPP connection.
<tty> refers to the tty for PPP stream. Eg. dev:/dev/omap_csmi_tty1
[parameters] - Eg. defaultroute debug dump local notty usepeerdns

adb sync notes: adb sync [ <directory> ]
 <localdir> can be interpreted in several ways:
 - If <directory> is not specified, both /system and /data partitions will be updated.
 - If it is "system" or "data", only the corresponding partition
   is updated.

environmental variables:
 ADB_TRACE                    - Print debug information. A comma separated list of the following values
                                1 or all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
 ANDROID_SERIAL               - The serial number to connect to. -s takes priority over this if given.
 ANDROID_LOG_TAGS             - When used with the logcat option, only these debug tags are printed.
#+end_src
** fastboot intro
*** A brief introduction to fastboot
fastboot is a small tool that comes with the Android SDK (software
developer kit) that can be used to re-flash partitions on your device.
It is an alternative to the recovery mode for doing installations and
updates.

 Please note that fastboot commands will ONLY work while the device is
 in fastboot mode.
*** Installing recovery using fastboot
Installing ClockworkMod Recovery on the device
1. Connect the device to the computer via USB.
2. Make sure the fastboot binary is in your PATH or that you place the downloaded image in the same directory as fastboot.
3. Open a terminal on your PC and reboot the device into fastboot mode by typing adb reboot bootloader or by using the hardware key combination.
4. Once the device is in fastboot mode, verify your PC sees the device by typing fastboot devices
     If you don't see your device serial number, and instead see "<waiting for device>", fastboot is not configured properly on your machine. See fastboot documentation for more info.
+ Flash ClockworkMod Recovery onto your device by entering the following command: fastboot flash recovery your_recovery_image.img where the latter part is the name of the file you downloaded.
+ Once the flash completes successfully, reboot the device into recovery to verify the installation.
      Note: Some ROMs overwrite recovery at boot time so if you do not plan to immediately boot into recovery to install CyanogenMod, please be aware that this may overwrite your custom recovery with the stock one.

** debugging with logcat
*** A bit about logcat
When Android is running, it's generating all kinds of system messages.
You see, programmers/developers can optionally output status
information (or errors or debugging notes) in real-time to a system
log, and Android itself sends all kinds of useful information out that
way.
*** Filtering
db logcat offers extra functionality to filter logs based on priority.
The usage is adb logcat *:# where # is one of the following.

#+begin_src sh
 V    Verbose (show all possibly useless logs, default level)
 D    Debug (show all reasonable debug logs)
 I    Info (show expected logs for regular usage)
 W    Warn (show possible issues that are not yet errors)
 E    Error (show issues that have caused errors)
 F    Fatal (show issues that are fatal to runtime and will often result in rebooting)
#+end_src

*** Color
+ Colored logcat by Jeff Sharkey
  https://code.google.com/p/colored-logcat/
  http://jsharkey.org/blog/2009/04/22/modifying-the-android-logcat-stream-for-full-color-debugging/
+ logcat-color by Marshall Culpepper
  https://github.com/marshall/logcat-color



*** Logcat for Bugtracker(On devices)

On device

This will generate a logcat on your sdcard which you can then attatch to a bug you want to report.
+ Open Console Application of your choice (CM comes with 'Terminal Emulator' preinstalled)
+ type logcat -d -f /sdcard/logcat.log *:V
+ alternatively the radio buffer can be viewed with logcat -b radio

#+begin_src sh
-d    makes it dump the logcat
-f    tell it where to save the log to
*:V   gets all Logs in Verbose mode
#+end_src 
** glossary
*** Bloatware
Software or 'apps' that you don't need, but come preinstalled to a
device's /system partition, meaning that you cannot remove them unless
the device has been rooted. Usually, these are apps are sponsored by a
company and included by a carrier for profit.
*** BFS
Brain Fuck Scheduler for Linux was created by veteran kernel
programmer Con Kolivas and has been reported to improve responsiveness
on light-NUMA (non-uniform memory access) Linux mobile devices and
desktop computers with fewer than 16 cores.
*** SuperCID
SuperCID is a special code, 11111111, which means that software from
any region can be installed. See superCID:
http://wiki.cyanogenmod.org/w/Basic_concepts#superCID

*** Vanilla
A clean, unmodified version of something. In the context of Android
ROMs, vanilla refers to the stock ROM that came pre-installed on the
device.

*** ----------------------------------android-------------
+ 32A PVT32A handsets have 288MB total RAM (192MB usable by OS - same as Hero handsets) and use the Qualcomm MSM7200A CPU.
+ 32B PVT32B handsets have 192MB total RAM (96MB usable by OS) and use the Qualcomm MSM7201A CPU.
+ ADP Android Developer Phone. The first ADP was a "development" version of the HTC Dream. The current ADP is the Samsung Nexus S.
+ CWM Short for ClockworkMod Recovery. Not to be confused with CM (Cyanogenmod).
+ Dalvik-Cache The dalvik-cache directory holds all of the pre-compiled .dex files created from installed apps. These files are static and do not change unless the app is updated.
+ flash_image A small utility to be used on the device that allows you to re-write system partitions with image files. If you don't have it, it can be found here.
+ NANDroid A set of tools that will enable anyone who has root on their Android device to make FULL system backups, in case something goes wrong or you want to try out that new experimental ROM/theme. NANDroid will backup (and restore) /system, /data, /cache, and /boot partitions.
+ NVFlash is a low-level flash utility for nVidia based devices which gives you low level access to the system to flash, format, recover, repartition and do many more functions. It is a very powerful tool and should be used with caution. Read and follow all instruction carefully when using nvflash. See http://rootzwiki.com/topic/35086-guide-nvflash-general-users-guide-unbrickrecoverdowngradeupgrade-tf201/#entry982736
+ Recovery Mode A special environment that you can boot into for troubleshooting and upgrading purposes.
+ SPL Second Program Loader, in conjunction with the IPL comprise a
  device's bootloader. Aside from bootstrapping Android, the
  bootloader also fulfills various diagnostic functions. One of these
  functions is the manipulation of data in the device's internal flash
  ram. Depending on the SPL installed, the user might be able to flash
  signed NBH files, flash nand images, and more. Note that the SPL is
  installed and operates independently of the Android build that runs
  atop it. Generally speaking, there are two variants of the SPL: Stock, which is 'locked' and is installed on most devices from the factory, and Engineering, which is 'unlocked' and has to be manually flashed - usually after 'rooting'.
+ S-OFF Usually a property of HTC devices. S-OFF allows the user to modify any partition on the device. Signature checking is disabled for zips, allowing the user to flash otapackages and custom kernels from recovery. S-ON prevents the user to allow these actions. See http://forum.xda-developers.com/showthread.php?p=26732440
+ Zipalign Reduces the amount of RAM consumed when running the application by allowing data to be mmap'd in; which causes all uncompressed data within the .apk, such as images or raw files, to be aligned on 4-byte boundaries.
*** -------------------------Hacking Definitions---------------
*** Aftermarket
Aftermarket generally refers to any product or service applied or requisitioned by end-users to add usability or functionality to the original product. Many aftermarket modifications can void the manufacturer's warranty. From a manufacturer's perspective, the after-market is any goods or services offered by the manufacturer directly to end-users of a given product or service. After-market services include support for warranties, contracts, and parts and accessories sales.
*** Exploit
A proof of concept local root exploit utilizing hotplug. Allows installation of a "rootshell" program on many Android 1.x and 2.x devices.
*** Flashing
The process of applying a firmware image (or ROM) to a device. It generally entails a very specific order of steps. Failing to complete any one of these steps properly may result in bricking the device.
*** Kang
The process of creating a code based off someone else's code or reapplying code that someone else created into your own code (e.g. git cherry-pick). The term "kang" or "kanging" can have a pejorative connotation, especially if one adopts code from someone else without giving due credit. However the term can also be used with a certain sense of irony; sometimes one will claim to have "kanged" with some tongue-in-cheek.

** Envsetup help
http://wiki.cyanogenmod.org/w/Envsetup_help

Invoking "$ source build/envsetup.sh"

#+begin_src sh
mka	 Builds using SCHED_BATCH on all processors
lunch	 lunch <vendor_name>_<product_name>-<build_variant>
breakfast	 breakfast <product_name>
brunch	 brunch <product_name>
omnom	 omnom <product_name>
tapas	 tapas [<App1> <App2> ...] [arm|x86|mips] [eng|userdebug|user]
croot	 Changes directory to the top of the tree
m	 Makes from the top of the tree
mm	 Builds all of the modules in the current directory
mmp	 Builds all of the modules in the current directory and pushes them to the device
mmm	 Builds all of the modules in the supplied directories
mmmp	 Builds all of the modules in the supplied directories and pushes them to the device
cgrep	 Greps on all local C/C++ files
jgrep	 Greps on all local Java files
resgrep	 Greps on all local res/*.xml files
godir	 Go to the directory containing a file
cmremote	 Add git remote for CM Gerrit Review
cmgerrit	 A Git wrapper that fetches/pushes patch from/to CM Gerrit Review
cmrebase	 Rebase a Gerrit change and push it again
aospremote	 Add git remote for matching AOSP repository
mkap	 Builds the module(s) using mka and pushes them to the device
cmka	 Cleans and builds using mka
reposync	 Parallel repo sync using ionice and SCHED_BATCH
installboot	 Installs a boot.img to the connected device
installrecovery	 Installs a recovery.img to the connected device
#+end_src
*** lunch
Unlike breakfast, lunch makes no assumptions with regard to device
configuration locations and formats, so it will scan the entire tree
for matching options (depending on the number of locally available
devices, this may take a significant amount of time). To build after
running lunch, simply issue the command mka. No bacon here

*** brunch
Defined simply, brunch is equivalent to

$ breakfast [device name] && mka bacon

This means that it sets up your build environment to be configured for
your device, and then commences the build process. mka bacon is just
CyanogenMods’s way of saying build the code for your device. It’s
generally only used for officially supported devices

** Basic concepts
http://wiki.cyanogenmod.org/w/Basic_concepts
*** S-OFF (Security OFF) Mode
Some bootloaders include a "Security ON" (AKA "S-ON") mode, whereby
certain operational restrictions are imposed on the boot. On some
devices (such as the T-Mobile G2), the S-ON bootloader may put the
operating system partition in a "read-only" mode. For others, S-ON may
cause the device to adopt behavior similar to a fully-locked
bootloader.

Switching the bootloader to S-OFF mode is therefore a prerequisite on
some devices to allow the operating system to be modified or replaced.

** All About Recovery Images
http://wiki.cyanogenmod.org/w/All_About_Recovery_Images
*** Overview
  recovery mode is, is a special "second boot" mode, independent of the
  normal boot, that you can start into that allows you to troubleshoot
  or update your device. Recovery mode lets you re-flash an entirely
  new operating system, clear out problematic cache partitions, and can
  "factory reset" your device, clearing out non-system data. The
  recovery can also let you back up and restore your Android
  installation. As if that wasn't enough, the recovery mode often will
  allow you to access your device from your computer via adb.
*** Popular Recoveries
+ ClockworkMod Recovery: https://github.com/koush
+ TWRP: http://teamw.in/project/twrp2  https://github.com/Dees-Troy

** Doc: more concepts
http://wiki.cyanogenmod.org/w/Doc:_more_concepts
*** Common Partitions and directories
+ /boot This partition stores the kernel and ramdisk. The kernel can
  be thought of as the "core" of the device's software. It is what
  allows the hardware to "talk" to the software, and vice versa. It
  also controls other aspects of the operating system on the device,
  such as what file formats the device is able to support. The ramdisk
  contains the very first bits of Android that are loaded. It's the
  software that loads everything else.

+ /recovery This partition holds the device's recovery software, which
  gives the user access to special functions, such as upgrading the
  operating system or making a backup of the device's software.

+ /system This is the main directory where the device's essential
  software, the operating system itself, is stored. When CyanogenMod
  is installed, this is where it goes. Generally speaking, this
  partition is loaded into "read only" mode so that you don't
  accidentally overwrite portions of Android, and it's only able to be
  modified under special circumstances.

+ /cache This directory stores temporary files used by Android.
  Generally, files on this partition are not usually critical to the
  operation of the device, and can be "cleared out" by wiping its
  contents, especially during every major upgrade.

+ /data This directory is where much of your personal data is stored.
  So if you download an app from the Android Market, it goes here. If
  you change a setting, that change is also stored here. If you
  receive a SMS, it too is stored here.

** Building Basics
http://wiki.cyanogenmod.org/w/Doc:_Building_Basics
*** The $OUT directory
+ /system -- this contains all the stuff that will become the /system
  folder on Android.

+ /root -- these files contain the files that are turned into the ram
  disk loaded and run by the kernel. The first program to be run by
  the kernel is called init, and it uses the init.rc and
  init.CODENAME.rc files to determine what happens next. See an
  discussion of that here.

+ /recovery/root The ramdisk that contains the recovery mode is here.

*** Commands
Make
+ make modules -- this command will show all available targets. You
  can build a single one by make my_target.

+ make showcommands -- this command will enable the verbose build
  mode.

ADB
+ adb remount -- If you've gotten errors trying to push files to
  /system due to it being in read-only mode, adb remount will remount
  /system into read-write mode--- provided that the shell has the
  correct root permissions to do so. This replaces having to type a
  longer command by hand such as mount -o rw,remount /system (as root)
  or something.

+ adb sync system -- assuming you have adb installed, this
  little-known, but powerful command will sync the contents of
  $OUT/system with the /system directory on your device. It does
  require that you have write access to /system. This command is very
  useful for making and testing quick changes to your device. Note
  though that adb sync system sometimes has problems with permissions
  and symlinks.


** using gerrit
http://wiki.cyanogenmod.org/w/Gerrit
*** Submitting to Gerrit
1. Setup an account on Gerrit, you can register at
   review.cyanogenmod.com
2. If you already have SSH keys set up (e.g. for Github), skip the
   following steps
*** Uploading your changes
1. First, you need to start a topic branch.
   =repo start <branch name> <project path>=
2. After you make your changes, you can commit them just as you would
   normally:
#+begin_src sh
git add <file you edited>
git commit
ctop (Same as moving to top/root of tree using cd)
#+end_src

3. upload your changes to the CyanogenMod server:
   =repo upload <project path>=

*** example
#+begin_src sh
#Add AWEXT Support
cd ~/android/system/
repo start mychanges-wpa_supplicant external/wpa_supplicant
cd ~/android/system/project
#Make changes, edit a few files, add new drivers.. etc.
git add *
git commit -am 'Added AWEXT drivers'
cd ~/android/system
repo upload external/wpa_supplicant
#+end_src


** Doc: eclipse
http://wiki.cyanogenmod.org/w/Doc:_eclipse

=cp ~/android/system/development/ide/eclipse/.classpath
~/android/system=

Open Eclipse
1. Click the File menu » new » java project
2. Give a project name of CyanogenMod
3. Uncheck use default location
4. Point the location to ~/android/system/
5. Keep all other defaults
6. Click finis

more : http://source.android.com/source/using-eclipse.html

** About local manifests – Add, remove, or replace source code repositories with local_manifest.xml
http://wiki.cyanogenmod.org/w/Doc:_Using_local_manifests
*** Overriding the manifest
create a folder called local_manifests and put that inside the .repo
directory, then put your XML inside that directory. You can place as
many override files in .repo/local_manifests as you like and repo will
pick them up during the next sync. You can call the files anything you
like as long as they end in .xml.

#+begin_src sh
<?xml version="1.0" encoding="UTF-8"?>
   <manifest>
     <remote name="omap" fetch="git://git.omapzoom.org/" />
     <remove-project name="CyanogenMod/android_hardware_ti_omap3" />
     <project path="hardware/ti/omap3" name="repo/android/hardware/ti/omap3" remote="omap" revision="jellybean"/>
   </manifest>
#+end_src

Note that when adding new projects, there are at least three parts defined:
+ remote -- the name of the remote. this can be one that was defined in either the regular manifest or local_manifest.xml.
+ name -- the name of the git project-- for github it has the format account_name/project_name
+ path -- where the git repository should go in your local copy of the source code.
+ revision -- (OPTIONAL) which branch or tag to use in the repository.

** Recreating CM Releases with Manifests – How to build for your device exactly like the buildbots do.
http://wiki.cyanogenmod.org/w/Doc:_manifests
** "make clean" vs. "make clobber"
http://wiki.cyanogenmod.org/w/Doc:_make_clean_vs_make_clobber


** Doc: the cm source
http://wiki.cyanogenmod.org/w/Doc:_the_cm_source



** The JIRA project management system
 https://jira.cyanogenmod.org

general User's Guide for JIRA 
https://confluence.atlassian.com/display/JIRA052/JIRA+Documentation
** View the latest accepted changes
http://changelog.bbqdroid.org/





** After You Build
http://wiki.cyanogenmod.org/w/After_You_Build
** porting intro
http://wiki.cyanogenmod.org/w/Doc:_porting_intro



** Setting up a Virtual Machine for CyanogenMod development
https://skydrive.live.com/?cid=b3bff0d42ae1e534&id=B3BFF0D42AE1E534%21107

* android open source project[fn:1]

** more
http://source.android.com/source/initializing.html
** Version Control with Repo and Git
http://source.android.com/source/version-control.html

Repo is a repository management tool that we built on top of Git. Repo
unifies the many Git repositories when necessary, does the uploads to
our revision control system, and automates parts of the Android
development workflow. Repo is not meant to replace Git, only to make
it easier to work with Git in the context of Android. The repo command
is an executable Python script that you can put anywhere in your
path. 

Gerrit is a web-based code review system for projects that use git.

*** Basic Workflow
#+begin_src sh
Use repo start to start a new topic branch.
Edit the files.
Use git add to stage changes.
Use git commit to commit changes.
Use repo upload to upload changes to the review server.
#+end_src
*** Task reference
#+begin_src sh
$ repo sync
$ repo sync PROJECT0 PROJECT1 PROJECT2 ...
$ repo start BRANCH_NAM
$ repo status
$ repo start BRANCH_NAME PROJECT
$ repo branches
$ repo diff
$ repo upload

$ repo prune
#+end_src

** Using Eclipse
http://source.android.com/source/using-eclipse.html


* Footnotes

[fn:1] http://source.android.com/

