#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: gpio_led
#+OPTIONS: num:nil

* locate
include/linux/leds.h


* data structure
#+begin_src c
  struct gpio_led {
          const char *name;
          const char *default_trigger;
          unsigned        gpio;
          unsigned        active_low : 1;
          unsigned        retain_state_suspended : 1;
          unsigned        default_state : 2;
          /* default_state should be one of LEDS_GPIO_DEFSTATE_(ON|OFF|KEEP) */
  };
#+end_src

Each LED is represented as a sub-node of the gpio-leds device.  Each
	node's name represents the name of the corresponding LED.
	
	LED sub-node properties:
	- gpios :  Should specify the LED's GPIO, see "Specifying GPIO information
	  for devices" in Documentation/powerpc/booting-without-of.txt.  Active
	  low LEDs should be indicated using flags in the GPIO specifier.
	- label :  (optional) The label for this LED.  If omitted, the label is
	  taken from the node name (excluding the unit address).
	- linux,default-trigger :  (optional) This parameter, if present, is a
	  string defining the trigger assigned to the LED.  Current triggers are:
	    "backlight" - LED will act as a back-light, controlled by the framebuffer
			  system
	    "default-on" - LED will turn on, but see "default-state" below
	    "heartbeat" - LED "double" flashes at a load average based rate
	    "ide-disk" - LED indicates disk activity
	    "timer" - LED flashes at a fixed, configurable rate
	- default-state:  (optional) The initial state of the LED.  Valid
	  values are "on", "off", and "keep".  If the LED is already on or off
	  and the default-state property is set the to same value, then no
	  glitch should be produced where the LED momentarily turns
          off (or on).  The "keep" setting will keep the LED at
          whatever its current state is, without producing a glitch.  The default is off if this
	  property is not present.




** examplex
#+begin_src c
{
		.name			= "overo:red:gpio21",
		.default_trigger	= "heartbeat",
		.gpio			= 21,
		.active_low		= true,
	}
#+end_src 

