#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Hacker's Delight
#+OPTIONS: num:nil H:2


* Overview
** homepage
http://www.hackersdelight.org/
** Related Sites
+ The Aggregate Magic Algorithms, 26 bit twiddling algorithms from
  Hank Dietz and others http://aggregate.org/MAGIC/

+ The Assembly Gems page, tips for the x86 and M680x0, by John
  Eckerdal http://www.df.lth.se/~john_e/

+ Bit Twiddling Hacks, by Sean Anderson
  http://graphics.stanford.edu/~seander/bithacks.html#CopyIntegerSign

+ HAKMEM, the famous memo is now computer readable! thanks to Henry
  Baker http://www.inwap.com/pdp10/hbaker/hakmem/hakmem.html

+ Matters Computational: Ideas, Algorithms, Source Code, by Jorg
  Arndt. LOTS of good stuff here. Also available at major book
  stores. http://www.jjj.de/fxt/fxtbook.pdf

+ Plane Filling Curves, Hilbert's and Moore's, by Alexander Bogomolny
  http://www.cut-the-knot.com/do_you_know/hilbert.shtml

+ Plane Filling Curves: Peano's & Wunderlich's, by Alexander Bogomolny
  http://www.cut-the-knot.com/Curriculum/Geometry/Peano.shtml
+ Programmer's Heaven http://www.programmersheaven.com/

+ Programming Pages of Jasper Neumann, an especially nice section on
  bit permutations http://programming.sirrida.de/

+ A Zillion Monkeys, much about programming, particularly about Intel
  x86 processors, by Paul Hsieh Has a huge list of sites of interest
  to computer aficionados.
  http://www.azillionmonkeys.com/qed/tech.shtml

+ Income tax help in the Monroe CT area
  http://www.jwbutleraccounting.com/

* Chapter 1. Introduction
