#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: SoftfWare
#+OPTIONS: num:nil H:2

* Firefox
** vimfx
https://addons.mozilla.org/en-US/firefox/addon/vimfx/

https://github.com/akhodakivskiy/VimFx
* Dropbox
** Why aren't certain files on one computer syncing to another
https://www.dropbox.com/help/145/en

1. Check bad files:https://www.dropbox.com/bad_files_check
2. Incompatible characters with Windows
   When naming your files, avoid characters incompatible with the
   Windows file system:
   #+begin_src sh
   < (less than)
   > (greater than)
   : (colon)
   " (double quote)
   | (vertical bar or pipe)
   ? (question mark)
   * (asterisk)
   #+end_src
3. Monitoring more than 10000 folders
   The Linux version of the Dropbox desktop application is limited
   from monitoring more than 10000 folders by default. Anything over
   that is not watched and, therefore, ignored when syncing. 

   This command will tell your system to watch up to 100000 folders.
   Once the command is entered and you enter your password, Dropbox
   will immediately resume syncing.
   #+begin_src sh
   echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p
   #+end_src
4. Turning on extended attribute (xattr) support in Linux
   Some Linux distributions have extended attributes (xattrs) turned
   off by default. If you're running a Linux distribution with an ext3
   or ext4 file system, it's possible to turn on xattr support,
   typically through your /etc/fstab settings file. Please refer to
   your Linux distribution's documentation for instructions.

* Ubuntu 下让sublime-text3支持中文输入法
下载 [[./Files/sublime-imfix.c][sublime-imfix.c]] 并保存在sublime安装的目录下
sublime_text3默认安装的目录：=/opt/sublime_text/=


安装C/C++的编译环境和 =gtk libgtk2.0-dev= 并编译：

#+begin_src sh
sudo apt-get install build-essential  
sudo apt-get install libgtk2.0-dev
gcc -shared -o libsublime-imfix.so sublime-imfix.c  `pkg-config --libs --cflags gtk+-2.0` -fPIC
#+end_src

启动 Sublime Text 试一试，可以使用fcitx输入中文了
#+begin_src sh
LD_PRELOAD=./libsublime-imfix.so subl
#+end_src

#+begin_src sh
mv libsublime-imfix.so /usr/lib
gksu gedit /usr/share/applications/sublime-text.desktop
# change Exec=/opt/sublime_text/sublime_text %F to
Exec=bash -c 'LD_PRELOAD=/usr/lib/libsublime-imfix.so /opt/sublime_text/sublime_text' %F
# change Exec=/opt/sublime_text/sublime_text -n
Exec=bash -c 'LD_PRELOAD=/usr/lib/libsublime-imfix.so /opt/sublime_text/sublime_text' -n
# change Exec=/opt/sublime_text/sublime_text --command new_file
Exec=bash -c 'LD_PRELOAD=/usr/lib/libsublime-imfix.so /opt/sublime_text/sublime_text' --command new_file
#+end_src
