#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Xen、OpenVZ、KVM、Hyper-V、VMWare虚拟化技术介绍
#+OPTIONS: num:nil H:2


* Xen 
官网：http://xen.org/

Xen 由剑桥大学开发，它是基于硬件的完全分割，物理上有多少的资源就只能分
配多少资源，因此很难超售。可分为Xen-PV（半虚拟化），和Xen-HVM（全虚拟
化）。

Xen是不能超售内存和硬盘的，当母服务器只有16G内存以及100G硬盘时，当开
Xen架构（任意一个虚拟化）的1G内存、25G硬盘的子机时，会直接占用服务器1G
内存，以及25G硬盘，所以Xen的性能，相比OpenVZ在超售的情况下要好。

+ Xen-PV：半虚拟化，所以它仅仅适用于linux系列VPS，但它的性能损失比较少，
  大概相对于母机的4%-8%左右。
+ Xen-HVM：全虚拟化，可以安装windows或自由挂载ISO文件安装任意系统，由
  于是全虚拟化，所以性能损失较大，大概相对于母机性能损失8%-20%左右。


+ Xen适用人群：预算较为充足，且希望VPS有较高性能的客户
+ Xen注意事项：注意Xen-PV和Xen-HVM的区别。
+ Xen可用系统：Xen-PV：纯Linux，Xen-HVM：支持Windows、Linux等。
+ Xen代表商家：Linode.com
* OpenVZ 
官网：http://openvz.org/

OpenVZ（简 称OVZ）采用SWsoft的Virutozzo虚拟化服务器软件产品的内核，是
基于Linux平台的操作系统级服务器虚拟化架构。这个架构直接调用母服务器
（母机）中的内核，模拟生成出子服务器（VPS，小机），所以，它经过虚拟化
后相对于母服务器，性能损失大概只有的1-3%。

当然 OpenVZ可以超售，意思味着一台服务器总共16G内存，他可以开出配置为1G
内存×17台以上的子服务器。因为他的虚拟架构关系属于：客户用多少，就扣除
母服务器多少，所以OpenVZ架构的VPS较为便宜。但由于存在超售因素，如果服
务商毫无休止的超售会导致服务器的性能急剧下降。

OpenVZ另一个特点是，它是 *直接调用母服务器的内核* ，所以会导致部分软件无法
使用，以及部分内核文件是无法修改。

+ OpenVZ适用人群：新手、低预算客户
+ OpenVZ注意事项：资源不是自己独有的，安装VPN服务需要注意检测虚拟网卡支持。
+ OpenVZ可用系统：Linux（不支持Windows）
+ OpenVZ代表商家：Buyvm.net
* KVM
网站：http://www.linux-kvm.org/

KVM是Linux下的全功能虚拟化架构，基于KVM架构的VPS，默认是没有系统的，可
自己上传ISO或调用服务商自带的ISO手动安装系统。这个非常适合热爱DIY自己
VPS的客户。

由于KVM架构全功能虚拟化架构，甚至拥有独立的BIOS控制，所以对母服务器性
能影响较大，所以基于KVM的VPS较贵，但KVM VPS相对其它架构的VPS较为自由。

+ KVM适用人群：折腾帝
+ KVM注意事项：虚拟化性能比Xen略低
+ KVM可用系统：Windows、Linux系列
+ KVM代表商家：Hostgation.com

* Hyper-V
网站：http://www.microsoft.com/zh-cn/server-cloud/

Hyper-V是微软的一款虚拟化产品，大部分国内的VPS服务商使用这个架构，主要
是因为其转为Windows定制，管理起来较为方便。目前的Hyper-V也支持Linux，
只不过性能损失比较严重。

Hyper-V完美支持Windows系统，包括32位和64位。如果大家选购Hyper-V架构的
VPS，强烈建议使用Windows。

Hyper-V目前不能超售内存，但可超售硬盘，硬盘是根据客户使用情况扣除。一
般来说，服务器的硬盘不会100%用完，这点不用担心。

+ Hyper-V适用人群：Windows系统爱好者
+ Hyper-V注意事项：Linux操作系统性能较低
+ Hyper-V可用系统：Windows、Linux
* VMWare
网站：http://www.vmware.com/

vSphere 是VMware公司推出一套服务器虚拟化解决方案，目前的最新版本为5.0
。vSphere5 中的核心组件为 VMware ESXi 5.0.0（取代原ESX）, ESXi是一款可
以独立安装和运行在祼机上的系统，因此与他我们以往见过的VMware
Workstation 软件不同的是它不再依存于宿主操作系统之上。在ESXi安装好以后，
我们可以通过vSphere Client 远程连接控制，在ESXi 服务器上创建多个VM（虚
拟机），在为这些虚拟机安装好Linux /Windows Server 系统使之成为能提供各
种网络应用服务的虚拟服务器，ESXi 也是从内核级支持硬件虚拟化，运行于其
中的虚拟服务器在性能与稳定性上不亚于普通的硬件服务器，而且更易于管理维
护

VMware vSphere 是用于虚拟化的软件组件套件。这些组件包括 ESXi、vCenter
Server 以及在 vSphere 环境中实现许多不同功能的其他软件组件

