#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: ZFS(The Z File System) summarize
#+OPTIONS: num:nil H:2

* Overview


ZFS has three major design goals:[fn:1]
+ Data integrity: All data includes a checksum of the data. When data
  is written, the checksum is calculated and written along with it.
  When that data is later read back, the checksum is calculated again.
  If the checksums do not match, a data error has been detected. ZFS
  will attempt to automatically correct errors when data redundancy is
  available.
+ Pooled storage: physical storage devices are added to a pool, and
  storage space is allocated from that shared pool. Space is available
  to all file systems, and can be increased by adding new storage
  devices to the pool.
+ Performance: multiple caching mechanisms provide increased
  performance. [[https://www.freebsd.org/doc/handbook/zfs-term.html#zfs-term-arc][ARC]] is an advanced memory-based read cache. A second
  level of disk-based read cache can be added with [[https://www.freebsd.org/doc/handbook/zfs-term.html#zfs-term-l2arc][L2ARC]], and
  disk-based synchronous write cache is available with [[https://www.freebsd.org/doc/handbook/zfs-term.html#zfs-term-zil][ZIL]].



* todo
自动 ZFS 快照，ZFS 垃圾清理

   + 或者安装ZFS，使用ZFS制作ZRAID1/RAID5等数据冗余，相较于LVM，ZFS管
     理较为方便（只需要两条命令），但是对内存开销较大.另外值得注意的是，
     由于OS DataBlock大小的关系，在创建ZPool的时候，记得加上 -o
     ashift=12 参数，以大幅提升ZFS的性能。
     #+begin_src sh
       sudo add-apt-repository ppa:zfs-native/stable
       sudo aptitude update
       sudo aptitude install ubuntu-zfs
     #+end_src
* reference
19.1. What Makes ZFS Different
https://www.freebsd.org/doc/handbook/zfs.html

https://www.ibm.com/developerworks/cn/linux/l-zfs/

https://arstechnica.com/information-technology/2014/02/ars-walkthrough-using-the-zfs-next-gen-filesystem-on-linux/

https://www.howtogeek.com/175159/an-introduction-to-the-z-file-system-zfs-for-linux/

https://wiki.ubuntu.com/ZFS

http://docs.oracle.com/cd/E19253-01/819-5461/zfsover-2/

http://www.freenas.org/zfs/

https://wiki.archlinux.org/index.php/ZFS
* More
+ [[https://www.freebsd.org/doc/handbook/zfs-term.html][ZFS Features and Terminology]]

* cc
#+begin_html
<p class="info">

</p>

<p class="warning">

</p>
#+end_html


#+begin_src sh

#+end_src

* Footnotes

[fn:1] https://www.freebsd.org/doc/handbook/zfs.html

