#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE: Web Server
#+OPTIONS: num:nil

* Github 
  https://github.com/
** GitHubwatcher
https://github.com/DAddYE/githubwatcher
** gitignore
https://github.com/GitHub/gitignore
** 
* Bitbucket 
https://bitbucket.org/

* gitorious
https://gitorious.org/

* Self Hosted Git Management
http://gitlabhq.com/
* Cloud application platform
http://www.heroku.com/

* ohloh
 http://www.ohloh.net/
* gerrit
http://code.google.com/p/gerrit/

* TI gforge
https://gforge.ti.com/gf
* 免费的云计算技术服务
** Cloud IDEs 云计算的集成开发环境
*** koding
koding是一个免费的，功能齐全的云开发环境，创建和编辑代码非常方便。
http://koding.com/

*** cloud9 IDE
cloud9 IDE是一个免费在线开发环境，支持Javascript和Node.js以及HTML，CSS，PHP，JAVA，Ruby和其他23种语言。
https://c9.io/

*** eXo Cloud IDE
eXo Cloud IDE是一个多租户，托管的云开发环境，可以直接部署到一个PaaS平
台，最重要的是，它是完全免费的 ，并且声称部署云的IDE只需花费几分钟的时
间。http://www.cloud-ide.com/
** Source Code Management  源代码管理
*** CloudForge
CloudForge（Codesion）是一个易于使用的开发平台，由CollabNet提供云服务
交付。和CloudFoundry.com，Force.com和亚马逊网络服务平台类似。
http://www.cloudforge.com/

*** GitHub
合作办公最好的方式就是GitHub。
https://github.com/
*** bitbucket
存储Git和Mercurial源代码存储在一个无限的私人档案库。
https://bitbucket.org/
*** Mercurial
Mercurial是一个免费的，分布式的源代码控制管理工具。它有效地处理任何规
模的项目，并提供一个简单而直观的界面。 http://mercurial.selenic.com/
*** Fossil
Fossil提供简单，高可靠性，分布式软件配置管理。
http://www.fossil-scm.org/download.html
** Issue Tracking  问题跟踪
*** TrackStudio
TrackStudio是超高配置的问题跟踪系统，具有工作流引擎和文件管理系统，可
以用来跟踪任何问题的解决方案，如任务安排，需求整理，桌面支持处理，项目
监控，硬件部署和工作人员雇用的进展等。http://www.trackstudio.com/
*** YouTrack
YouTrack是一个创新的问题跟踪和项目跟踪工具，可以自定义您的问题跟踪，以
适应您的工作——而不是其他方式。操作只是两个简单的控制问题，快去享受快闪
电般感觉吧！http://www.jetbrains.com/youtrack/
*** Issue Tracking Anywhere
Issue Tracking Anywhere是一个基于网络的错误和问题跟踪系统，主要是为工
作跟踪，项目跟踪，客户支持和软件开发设计。
http://www.dynamsoft.com/blog/dynamsoft-products/bug-tracking-issue-tracking-anywhere-2/
** Cloud Database and Open Source DBs  云数据库和开源的DB
*** xeround
xeround是能取代现有的MySQL数据库，并且提供无缝的MySQL的可扩展性和高可
用性的服务。xeround运行在云中，允许您扩展数据库或自动退出，即使在发生
故障时的也能保持可用性。你可以运行亚马逊Web服务和Rackspace公司的数据库，
惠普云服务等。http://xeround.com/
*** MySQL的衍生版本 - Percona、MariaDB、MySQL branch at Google 
MySQL是世界上最流行的开源数据库。无论你是技术的ISV还是大型企业，MySQL
可以经济有效地帮助您提供高性能，进行可伸缩的数据库应用。
+ [[http://www.percona.com/][Percona]] - Experts in MySQL, InnoDB, and LAMP Performance 
+ [[https://mariadb.org/][MariaDB]] - MySQL 原創辦人繼續製作、維護的產品
+ [[https://code.google.com/p/google-mysql/][MySQL branch maintained and used at Google]] (google-mysql) 
+ [[https://github.com/twitter/mysql][twitter/mysql]] - Twitter 的 MySQL branch 套件.

*** CouchDB
ouchDB是一个数据库，它完全拥抱网络，使用JSON文档存储您的数据存储，网页
浏览器访问您的文件，使用JavaScript进行查询，整合和转化。
http://couchdb.apache.org/
*** MongoDB
MongoDB的（来自“humongous”）是一个可扩展，高性能，开源NoSQL数据库。 
http://www.mongodb.org/ http://docs.mongodb.org/ecosystem/platforms/amazon-ec2/
*** Cassandra
Cassandra是支持跨越多个数据中心的最好的产品，为用户提供更低的延迟。
http://cassandra.apache.org/
http://wiki.apache.org/cassandra/CloudConfig

*** Neo4j
Neo4j的是一个高性能的的NOSQL图形数据库，具有一个成熟和强大的数据库的所
有功能。 http://neo4j.org/ 
*** hadoop
一个分布式系统基础架构，由Apache基金会开发，用户可以在不了解分布式底层
细节的情况下，开发分布式程序，充分利用集群的威力进行高速的运算和存储。
http://hadoop.apache.org/
** CMS（Content Management System） 内容管理系统
*** WordPress
WordPress是一个开源项目，这意味着世界上有数百人在为之工作，这也意味着
你可以自由使用世界上500强的网站主页，无需支付任何许可费和拥有一些其他
重要的自由 http://wordpress.org/
*** Drupal
Drupal是一个免费的软件包，让您可以轻松地组织，管理和发布，而且有层出不
穷的各种定制的内容。 http://drupal.org/
*** Joomla
Joomla是一个屡获殊荣的内容管理系统（CMS），它使您能够为网站建立功能强
大的在线应用。 http://www.joomla.org/
** Payment Gateways 支付网关
*** QuantumGateway
QuantumGateway功能丰富，会让您的企业在同行业中占据的优势。
http://www.cdgcommerce.com/free-payment-gateway.php
*** Fastcharge
Fastcharge支付网关™是一个商家帐户服务及信用卡处理解决方案，已经与5200
多个购物车展开合作。http://www.fastcharge.com/
*** SwissMicsi
http://www.swissmicsi.com/index.html
** IaaS/PaaS/Code Hosting  IaaS/PaaS/代码托管
*** Amazon EC2
为了帮助新的AWS的客户获得云服务，AWS是推出一个免费使用层，新的AWS的客
户将能够获得一个免费的Amazon EC2微实例一年的使用权，同时还可以免费使用
亚马逊S3服务。http://aws.amazon.com/free/

*** CloudBees
CloudBees平台作为服务（PaaS）架构为云计算开发和部署服务提供了强大的基
础。 http://www.cloudbees.com/platform/how-it-works.cb
*** Engine Yard
Engine Yard的云是最好的平台服务（PaaS），被广泛的应用于从小型的Web应用
程序运行在一个单一的计算实例，到大型企业应用需要的可靠性，弹性和高性能
可用性集群。https://www.engineyard.com/products/cloud
*** jelastic
jelastic是下一代Java的托管平台，它可以运行和扩展任何Java应用程序无需代
码的改变。http://jelastic.com/
*** PHPfog
PHPfog应用程序栈的设计具有高可靠性，易于使用，可扩展性和高速度的优势，
从传入的HTTP请求提供您的关键数据和功能。https://phpfog.com/platform
** Load Testing 负载测试
*** LoadStorm
LoadStorm™是一个Web负载测试工具。它解决了传统昂贵的性能测试工具的问题
和托管开源工具的麻​​烦。http://loadstorm.com/load-test-tool/
*** CloudTest
CloudTest® Lite是SOASTA’s 免费下载版本，提供快速创建测试和实时分析。
http://www.soasta.com/cloudtest/lite/
*** BlazeMeter
BlazeMeter是100％JMeter的兼容，自我服务的负载测试云，能够使用全面的报
告和分析工具瞬间产生巨大的压力测试。
http://blazemeter.com/about-blazemeter
*** Monitoring 监控
Pingdom致力于世界上90％的公司的正常运行时间监控需求，尽一切努力保持提
供最佳运行时间的监测服务。 http://www.pingdom.com/about/
*** Monitor
Monitor提供自由的Web和云系统监测服务
http://www.monitor.us/en/website-monitoring
*** Neustar
Neustar提供方便的，可定制的网站监测和负载测试。
https://browsermob.com/website-monitoring
** Knowledge Base/Helpdesk 知识库/帮助
*** UserVoice 
UserVoice是一个创建简单的在线反馈，帮助台和知识基础的软件。
产品页：http://www.uservoice.com/
*** NeuQs
NeuQs帮助台软件将确保您提供专业的服务水平，拥有及时的管理和高层次的反馈系统。
产品页：http://www.neuqshelpdesk.com
*** iHelpDesk
iHelpDesk托管服务台的应用，在解决问题方面，能够减少手动工作和提高服务的质量。
产品页：http://www.ihelpdesk.com/faq.php
** Web Analytics 网络分析
*** 谷歌Analytics
谷歌Analytics是企业级的网络分析解决方案，能够为您的网站流量和营销效果提供了丰富的见解和分析。
产品页：http://www.google.com/intl/en_uk/analytics/
*** woopra
woopra最根本的想法，实现真正的实时分析能力，能够使用它作为您的工作基础，基于这个原因，所有这些功能都被放在一个单一的、用户友好的平台上。
产品页：http://www.woopra.com/features/

*** clicktale
clicktale能够看到游客对您的网站做的一切，甚至是每一个鼠标的移动，悬停点击和滚动。
产品页：http://www.clicktale.com/
*** clicky
clicky是一个实时网络分析服务，这意味着，当你登录并查看您的统计数据时，你能看到了您网站每一分钟的数据流量。
产品页：http://getclicky.com/help/









* host
2、日本高速空间：成功申请Phpapps日本免费空间:1GB空间支持FTP可绑域名速度快
3、法国云空间：Another Service法国免费云空间内存256MB可绑域名支持SSH
