#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE:A Software Developer's Reading Plan
#+OPTIONS: num:nil


《代码大全2》第35章第4节软件开发者的阅读计划

* 入门级
Adams, James L. 《Conceptual Blockbusting: A guide to Better Ideas》, 4th ed. Cambridge, MA: Perseus Publishing, 2001.
http://book.douban.com/subject/1783551/

Bentley, Jon. 《Programming Pearls》, 2d ed. Reading, MA: Addison-Wesley, 2000.
《编程珠玑》人民邮电出版社 2006-11
http://book.douban.com/subject/1910326/

Glass, Robert L. 《Facts and Fallacies of Software Engineering》. Boston, MA: Addison-Wesley, 2003.
《软件工程的事实与谬误》中国电力出版社 2006-01-01
http://book.douban.com/subject/1723351/

McConnell, Steve. 《Software Project Survival Guide》. Redmond, WA: Microsoft Press, 1998.
《软件项目生存指南》清华大学出版社 2003-4
http://book.douban.com/subject/1229895/

McConnell, Steve. 《Code Complete》, 2d ed. Redmond, WA: Microsoft Press, 2004.
《代码大全（第2版）》电子工业出版社 2006-3
http://book.douban.com/subject/1477390/

* 熟练级
Berczuk, Stephen P. and Brad Appleton. 《Software Configuration Management Patterns: Effective Teamwork, Practical Integration》. Boston, MA: addison-Wesley, 2003.
《软件配置管理模式》中国电力出版社 2004-6
http://book.douban.com/subject/1170846/

Fowler, Martin. 《UML Distilled: A Brief Guide to the Standard Object Modeling Language》, 3d ed. Boston, MA: Addison-Wesley, 2003.
《UML精粹 标准对象建模语言简明指南(第2版)》清华大学出版社 2002-5-1
http://book.douban.com/subject/1231832/

Glass, Robert L. 《Software Creativity》. Reading, MA: Addison-Wesley, 1995.
http://book.douban.com/subject/1849630/

Kaner, Cem, Jack Falk, Hung Q.Nguyen. 《Testing Computer Software》, 2d ed. New York, NY: John Wiley & Sons, 1999.
《计算机软件测试》机械工业出版社 2004-5
http://book.douban.com/subject/1230459/

Larman, Craig. 《Applying UML and Patterns: An Introduction to Object-Oriented Analysis and the Unified Process》, 2d ed. Englewood Cliffs, NJ: Prentice Hall, 2001.
《UML和模式应用》机械工业出版社 2006-5
http://book.douban.com/subject/1792387/

McConnell, Steve. 《Rapid Development》. Redmond, WA: Microsoft Press, 2003.
《快速软件开发》电子工业出版社 2002-1
http://book.douban.com/subject/1007738/

Wiegers, Karl. 《Software Requirements》, 2d ed. Redmond, WA: Microsoft Press, 2003.
《软件需求》清华大学出版社 2004-11
http://book.douban.com/subject/1239562/

"Manager's Handbook for Software Development" NASA Goddard Space Flight Center. Downloadable from sel.gsfc.nasa.gov/website/documents/online-doc.htm

* 专业级
Bass, Len, Paul Clements, and Rick Kazman. 《Software Architecture in Pratice》, 2d ed. Boston, MA: Addison-Wesley, 2003.
《软件构架实践》清华大学出版社 2003-8
http://book.douban.com/subject/1131829/

Fowler, Martin. 《Refactoring: Improving the Design of Existing Code》. Reading, MA: Addison-Wesley, 1999.
《重构》人民邮电出版社 2010
http://book.douban.com/subject/4262627/

Gamma, Erich, et al. 《Design Patterns》. Reading, MA: Addison-Wesley, 1995.
《设计模式》机械工业出版社 2000-9
http://book.douban.com/subject/1052241/

Gilb, Tom. 《Principles of Software Engineering Management》. Workingham, England: Addison-Wesley, 1988.
http://book.douban.com/subject/2627153/

Maguire, Steve. 《Writing Solid Code》. Redmond, WA: Microsoft Press, 1993.
《编程精粹》人民邮电出版社 2009.2
http://book.douban.com/subject/3406939/

Meyer, Bertrand. 《Object-Oriented Software Construction》, 2rd ed. New York, NY: Prentice Hall PTR, 1997.
《面向对象软件构造》机械工业出版社 2003-01-01
http://book.douban.com/subject/1102733/

“Software Measurement Guidebook” NASA Goddard Space Flight Center.
Available from sel.gsfc.nasa.gov/website/documents/online-doc.htm. 

* more details
For more details on this professional development program, as well as for up-todate
reading lists, see our professional development website at
http://www.construx.com/professionaldev/.

