#+SETUPFILE: ~/.emacs.d/src/org-templates/level-1.org
#+TITLE: The Elements of Style
#+OPTIONS:  H:2


* 使用规则
** 加's来形成单数名词地所有格
无论最有一个辅音是什么，都遵循这条规则。所以写成，

+ Charles's friend
+ Burns's poems
+ the witch's malice

例外是古代以-es和-is为结尾地专有名词地所有格，所有格Jesus'，和这样地形
式for conscience's sake, for righteousness' sake。但是如此的形式
Moses's Laws, Isis' temple 通常被如下所代替

+ the laws of Moses
+ the temple of Isis

代词hers, its, theirs, yours和ours没有撇号。但是，不定代词使用撇号来表
明所有格。

+ one's rights
+ somebody else's umbrella

一个通常的错误是，把it's写成its, 或反之。第一个是“it is”的缩写，第二个
是个所有格。

~It's a wise dog that scratches its own fleas.~

** 在由一个连接词连接的超过3个东西的序列中，在除了最后一个外的每个东西后使用逗号
所以写成
#+begin_verse
red, white, and blue golder, silver, or copper
He opened the letter, read it, and made a note of its content.
#+end_verse
这个逗号经常被称为“序列”逗号。在商业公司名字里，最后的逗号经常被省略。
对这个公司遵循这个使用方法。

~Little, Brown and Company Donaldson, Lufkin & Jenrette~

** 内部插入语句在逗号间
#+begin_verse
The best way to see a contry, unless you are pressed for time, is to
travel on foot.
#+end_verse
这条规则很难应用；经常很难去决定一个如however的词，或一个短句是否是插
入的。如果对于句子流畅度的中断是细微的，那么逗号或许可以安全的省略。但
是，中断是否细微或重要，别忽略一个逗号，却留下另一个。不可防备的产生如
此的标点
#+begin_verse
Marjories husband, Colonel Nelson paid us a visit yesterday.
or
My brother you will be pleased to hear, is now in perfect health.
#+end_verse

日期总是包含插入词和数字。标点如下：
#+begin_verse
February to July, 1992
April 6, 1986
Wednesday, November 14, 1990
#+end_verse
注意习惯忽略逗号在

=6 April 1988=

最后一种形式是一个极好的写日期的方法；数字被一个词所分开，基于此，数字
能一下被认出。

一个名字或标题在一个直接的位置是插入语：
#+begin_verse
If, Sir, you refuse, I cannot predict what will happen.
Well, Susan, this is a fine mess you are in.
#+end_verse

那些名字后的缩写etc., i.e.,和 e.g.,学位缩写，和称谓都是插入语，应该相
应的标点。
#+begin_verse
Letters, packages, etc., should go here.
 Horace Fulsome, Ph.D., presided. 
Rachel Simonds, Attorney
The Reverend Harry Lang, S.J.
#+end_verse

但是不需要逗号来分开一个名字与一个限定标示的条目。
#+begin_verse
Billy the Kid
The novelist Jane Austen
William the Conqueror
The poet Sappho
#+end_verse

尽管Junior的缩写Jr.,通常被认为插入语，逻辑上显示，事实上，它是限制词，
所以并不需要一个逗号。

=James Wright Jr.=

非限制关系子句是插入语，如类似被连接词引入标明时间或地点的子句。逗号因
此需要。非限制性子句不是用来标明或定义先前的名词。
#+begin_verse
The audience, which had at first been indifferent, became more and more interested.
In 1769, when Napoleon was born, Corsica had but recently been acquired by France.
Nether Stowey, where Coleridge wrote The Rime of the Ancient Mariner, is a few miles from Bridgewater.
#+end_verse

在这些句子中，通过which, when 和where引入的子句是非限制的；它们不限制
或定义，仅仅加入一些东西。在第一个例子中，通过which引入的子句不是用来
说明意味哪些可能的观众，读者可能之前就已经知道了。子句加入插入式的一个
叙述来补充主要的子句。三个句子中的每一句都是两段原本可能可以互相独立的叙述组成
的。
#+begin_verse
The audience was at first indifferent. Later it became more and more interested.
Napoleon was born in 1769. At that time Corsica had but recently been acquired by France.
Coleridge wrote The Rime of the Ancient Mariner at Nether Stowey. Nether Stowey is a few miles from Bridgewater.
#+end_verse

限制性子句，相反的，不是插入句，不用逗号来分开。因此
#+begin_verse
People who live in glass houses shouldn't throw stones.
#+end_verse

这里由who引入的子句用来表明这些人指哪些；这个句子，不象上面的句子，不
能分开成两段独立的叙述。同样理念的逗号使用应用在分词短语和同位语上。

#+begin_verse
People sitting in the rear couldn't hear, (restrictive)
Uncle Bert, being slightly deaf, moved forward, (non-restrictive) 
My cousin Bob is a talented harpist, (restrictive)
Our oldest daughter, Mary, sings, (nonrestrictive)
#+end_verse

当一个句子的主子句被一段短语或从句所超前，使用一个逗号来分开这些元素。
#+begin_verse
Partly by hard fighting, partly by diplomatic skill, they enlarged their dominions to the east and rose to royal rank with the possession of Sicily.
#+end_verse
** 在连词前放一个逗号来引入一个独立的子句
#+begin_verse
The early records of the city have disappeared, and the story of its first years can no longer be reconstructed.
The situation is perilous, but there is still one chance of escape.
#+end_verse

两部分句子的第二部分的成员是通过as（意义上指”因为“），for，or，nor，或
while（意义上指“然后同时”）同样的需要一个逗号在这些连词前。

如果一个从句，或一段引入语需要用逗号来分开，不需要逗号，在第二段独立从
句前，和连词后。这种状况危险的，但是如果我们准备迅速反映，那仍然有希望
逃避。

当对于两个从句的主语是一样，并且只用一次来表述，那么当连接词是/but/时，
一个逗号就很有用。当连接词是/and/，逗号可以忽略当两句的关系紧密或接近
的。
#+begin_verse
I have heard the arguments, but am still unconvinced.
He has had several years' experience and is thoroughly competent.
#+end_verse
** 不要用逗号来连接独立子句
当两个或多个子句在语法上完整，并没用连接词来连接成一句复合句，那么合适
的标点是分号。
#+begin_verse
Mary Shelley's works are entertaining; they are full of engaging ideas.
It is nearly half past five; we cannot reach town before dark.
#+end_verse

当然，把它们纠正成两个句子，用句号取代分号。
#+begin_verse
Mary Shelley's works are entertaining. They are full of engaging ideas.
It is nearly half past five. We cannot reach town before dark.
#+end_verse

如果插入一个连词，那么逗号是合适的标志。(Rule 4)
#+begin_verse
Mary Shelley's works are entertaining, for they are full of engaging ideas.
It is nearly half past five, and we cannot reach town before dark.
#+end_verse

通过如上3种形式的对比，清楚的显示了第一中的优势。至少在给出的例子中，
它比第二种形式好，因为它暗示了2个句子间的紧密关系，但第二种形式却没有，
好过第三种是因为它更简洁而显得有力。确实，这一显示句子关系的简单方法是
最有用合成句子策略之一。如上的句子关系，通常是一中因素和结果。


注意，如果第二个分句由一个副词引领而不是个连词，如 /accordingly/, /besides/,
/then/, /therefore/, 或 /thus/,这个分号仍然需要。
#+begin_verse

#+end_verse

一种例外的分号规则值得在这里注意。一个逗号更适合，当分句们很短并在形式
上类似，或当句子的语气简单和会话式。
#+begin_verse

#+end_verse

** 不要把句子一分为二
也就是，不要使用句号来替代逗号。

在这些例子中，第一个句号应当被一个逗号替换，接下去的开头词小写。

