#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: JTAG and Debug Overview
#+OPTIONS: num:nil H:2


* GSG
** GSG:Debugging projects
http://processors.wiki.ti.com/index.php/GSG:Debugging_projects
** GSG:Using BIOS
   how to create and debug a project using BIOS
http://processors.wiki.ti.com/index.php/GSG:Using_BIOS

** GSG:Common target configurations
http://processors.wiki.ti.com/index.php/GSG:Common_target_configurations#Beagleboard.2C_Hawkboard.2C_Leopardboard.2C_Pandaboard
** Target Configuration - Custom Configurations
http://processors.wiki.ti.com/index.php/Target_Configuration_-_Custom_Configurations

** GSG:Adding GEL files to a target configuration
http://processors.wiki.ti.com/index.php/GSG:Adding_GEL_files_to_a_target_configuration
*** Configuring a GEL file
1. With the target configuration editor open, select the tab Advanced
   at the bottom.
2. Expand the configuration and select the connection that corresponds
   to the core that will be configured. 
3. On the box initalization script provide the location of the GEL
   file obtained from the board manufacturer.



** GSG:Connecting to slave cores in SoC devices
http://processors.wiki.ti.com/index.php/GSG:Connecting_to_slave_cores_in_SoC_devices


** GSG:Automation and Scripting
http://processors.wiki.ti.com/index.php/GSG:Automation_and_Scripting

Debug Server Scripting (DSS) is a set of cross platform Java APIs to
the Debug Server which allow scripting through Java or 3rd Party tools
such as JavaScript (via Rhino), Java) , Python (via Jython), TCL (via
Jacl/Tclblend), etc. JavaScript is the default (and preferred)
scripting language supported by DSS.


* Without GUI, Debug Server Scripting
http://processors.wiki.ti.com/index.php/Debug_Server_Scripting
* Linux Debug in CCSv5
http://processors.wiki.ti.com/index.php/Linux_Debug_in_CCSv5
* Debugging JTAG Connectivity Problems
http://processors.wiki.ti.com/index.php/Debugging_JTAG_Connectivity_Problems
* Spectrum Digital JTAG Emulator FAQ
http://support.spectrumdigital.com/guides/JTAG_Emulator_guide/

* DBGJTAG Graphical User Interface
http://processors.wiki.ti.com/index.php/DBGJTAG_Graphical_User_Interface

* Simulation
http://processors.wiki.ti.com/index.php/Category:Simulation

* Blackhawk
** USB100v2(XDS100)
*** JTAG EMULATION DRIVER DOWNLOAD
http://www.blackhawk-dsp.com/support/Drivers.aspx#BH-USB-100v2D
*** Firmware Updates for the Blackhawk XDS100-class product
http://www.blackhawk-dsp.com/support/xds100/Default.aspx
*** TI XDS100 Wiki Support Page
http://processors.wiki.ti.com/index.php/XDS100
*** reprogam it
http://e2e.ti.com/support/dsp/c6000_multi-core_dsps/f/639/t/131875.aspx?pi24928=2
go back to http://processors.wiki.ti.com/index.php/XDS100#Q:_How_can_I_check_if_the_VID.2FPID_for_the_EEPROM_are_programmed_correctly.3F  note the part that says 

Note:It is possible to reprogram the EEPROM using MPROG or FT_Prog and
the .ept file. The .ept file depends on the type of device you have.
If you have a FT2232C device download the following FT2232C EPT file.
If you have a FT2232H device download the following FT2232H EPT file.
Refer to the instructions in the How to make an XDS100 section




** Blackhawk guide and a FAQ list
http://www.blackhawkdsp.com/support/get.aspx?name=EMULATOR&type=appnote&subtype=TROUBLESHOOT

http://www.blackhawkdsp.com/support/FAQ.aspx
* JTAG Connectors(Hardware Pins)
http://processors.wiki.ti.com/index.php/JTAG_Connectors#JTAG_Connectors 

* TI Emulation FAQ
http://processors.wiki.ti.com/index.php/Emulation_FAQ
