#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Interview Questions
#+OPTIONS: num:nil H:2

* So, Do You Have Any Questions?[fn:1]
n the end, if you are interested in this job, make sure to say so!
Your final question should really nail the closer: “I just want to
let you know that I am very interested in this opportunity, and hope
we can move forward. What are the next steps in the interview
process?” Don’t leave without determining what the expectations are
for the next steps, and how and when YOU should follow-up. Ask what
their timetable is for hiring, and how their hiring process works. 

** examples
+ What's a typical day like for this role? Get an idea for the day
  to day tasks and initiatives you'll be working on.

+ How would you describe the daily work environment / company culture
  here?

+ What characteristics have made your best employees successful here?

+ Earlier, you mentioned (blank). Can you tell me a little more about
  how that works in your department?

+ How do you measure success for this role? If the employer doesn't
  know how to define this it could be good or bad. It could be good
  because you could potentially be able to shape the success metrics /
  parameters for them or it could be bad if they simply have no idea
  how to set you up for success and end up doing it incorrectly.

+ How would you describe the culture of the company?

+ What opportunities have you had to work with different people and
  projects during your time at the company?

+ What are the current priorities and focus areas at the company?

+ What is the current project you're working on?(if interviewer hasn't
  already told you about it)

+ What is one thing you enjoy most and one thing you hate most about
  working here?

+ What are the biggest challenges I will encounter in this role?
  It's easy to hear the the good stuff about the job. What you want to
  hear are the issues so you know what you're getting into.

+ What is the leadership style like at this company?

+ What type of culture has the leadership put in place at the company?

** NOT to ask and SHOULD ask[fn:3]
*** What NOT to ask during an interview:
+ Don’t ask what the company does, what products they produce, or
  other basic questions that anyone could find the answers to by
  simply reading the company’s website. (Do your homework, and don’t
  sound like an idiot!)
+ Don’t ask about compensation, vacation, or benefits. Those are
  clearly things that fall under the category of “what’s in it for
  me” — but certainly won’t show what’s in it for the interviewer!
  On the other hand, if the interviewer brings up the salary issue
  first, be prepared to address it head on.
+ Don’t ask about anything sensitive or negative that you might
  have read or heard about the company — e.g. recent layoffs, poor
  financial performance, bad press reports, lawsuits, complaints or
  any other negative issues you are aware of.
+ Don’t ask generic, standard questions that sound as though you
  found them on a website (like this blog!) and are reciting them
  from a script. Most savvy interviewers will be able to spot those
  types of canned questions a mile away, and easily distinguish them
  from more thoughtful, insightful questions that pertain
  specifically to their company or the exact position you are
  interviewing for.
+ Don’t ask personal questions about the interviewer’s family,
  marital status, children, hobbies, political opinions, religious
  affiliation, etc. Unless you have a prior history with the person,
  issues like that are totally inappropriate for an interview with
  someone you just met. (On the other hand, if they bring those things
  up first then simply follow their lead … but tread carefully with
  these topics and don’t offer up too much personal information of
  your own. Try to stay focused on the business at hand.)
+ Don’t ask point blank if you are going to get the job. That tends
  to put the interviewer on the spot, and makes people feel very
  uncomfortable.
*** What you SHOULD ask:
+ Ask open-ended questions, as opposed to yes-no questions. “Can you
  tell me more about …” “What is your opinion of …” The idea is
  to get the interviewer to talk more — to reveal more information
  about the company, about the position, about themself and about
  their expectations. Ideally, you can then use that information to
  say things that will demonstrate that you truly fit whatever it is
  they seem to be looking for.
+ Take something you learned beforehand about the company, and probe
  further. Show that you’ve done your homework about the company. Ask
  specific questions about those things that you learned. Start out
  with something like “During my research, I read that … I was
  wondering …” Demonstrating that you’ve read up on the company,
  and that you are curious and interested can be very impressive!
+ Take something discussed during the interview, and probe further.
  Expand on topics already covered, and ask for more details. This
  shows that you’ve been paying attention, and that you are curious,
  interested and eager to learn more.
+ Ask about the company’s culture and work environment. Those are
  issues that tend to be rather abstract, and less likely to be
  explained on their website. Therefore, they are good topics to ask
  the interviewer about.
+ Ask about what qualities they look for in a successful employee. How
  can someone succeed and grow within the company? What are the
  specific goals and expectations for the position you are
  interviewing for? What do they hope to accomplish — both short and
  long term — with this hire?

* Answering the Salary Question[fn:2]





* cc
#+begin_src sh

#+end_src


* Footnotes

[fn:1] https://www.quora.com/What-are-the-questions-that-can-be-asked-when-the-interviewer-asks-Any-questions

[fn:2] https://michaelspiro.wordpress.com/2009/10/07/hello-world/

[fn:3] https://michaelspiro.wordpress.com/2013/01/01/so-do-you-have-any-questions-nailing-the-interview-closer/



