#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: shadowsocks超详细科普教程
#+OPTIONS: num:nil H:2


没有可用的shadowsocks节点线路，shadowsocks在你手里也是浮云这个作为重点先说一下
* Docker + DigitalOcean + Shadowsocks 5分钟科学上网
+ Shadowsocks for OSX:
  https://github.com/shadowsocks/shadowsocks-iOS/wiki/Shadowsocks-for-OSX-%E5%B8%AE%E5%8A%A9
+ Shadowsocks clients: https://shadowsocks.com/client.html

1. choose docker 16.2 on 14.04
2. add ssh keys
3. 安装 Shadowsocks
   #+begin_src sh
      docker pull oddrationale/docker-shadowsocks
     docker run -d -p 1984:1984 oddrationale/docker-shadowsocks -s 0.0.0.0 -p 1984 -k paaassswwword -m aes-256-cfb
   #+end_src
    paaassswwword 就是等下配置客户端需要的密码
4. check
  #+begin_src sh
    docker ps
   #+end_src
5. 客户端配置： ip, port, password, and aes-256-cfb

* Shadowsocks的小白使用教程
+ http://51.ruyo.net/p/412.html
+ http://t.cn/Ry42Kbx

chrome浏览器配合代理扩展的设置，下拉记事本滑块到底，看附3
首先明确一点，不管 Shadowsocks 有几种版本，都分为服务端和客户端，
服务端是部署在服务器（VPS）上的，客户端是在你的电脑上使用的。
简单说一下windows系统，你有shadowsocks节点的情况下，Shadowsocks客户端的设置代理使用教程
一定要有有效SS节点才行 一定要有有效SS节点才行网或群共享下载Windows系统
的Shadowsocks客户端软件为绿色免安装，下载 解压到任意目录，如：
D:/Program Files/shadowsocksshadowsocks的账号(本地客户端配置参数)一般
包括这么几个部分

4-1 ：服务器 IP （一般为域名或数字ip）

4-2： Port ：服务器端口 （不同的账号的端口也都是不同的）

4-3 ：Password：你的密码

4-4 ：加密模式：鼠标点击下拉小三角选取

依次手动输入以下3项
shadowsocks 服务器域名或IP服务器端口密码并选择ss服务商提供的节点对应的加密方式
点击“确定”
右下角的 代理端口 指的是本地监听端口，一般保持默认1080就可以，不用你填。
现在的ss站都提供二维码形式的ss节点配置参数文件
对于二维码形式的ss节点配置文件，也可以用客户端自带的二维码扫描功能快速添加
右键>任务栏>ss客户端图标>服务器>扫描屏幕二维码
客户端支持添加多线路节点，方便你切换，选择相对你网络环境质量较好，速度快的节点。
shadowsocks节点速度快慢，影响shadowsocks节点速度的因素：
你的机房（地理位置，影响节点路由），运营商（网络封锁程度、丢包率、延迟），
时间段（高峰期），运营商QoS限速，你的本地物理宽带等等。
总结起来就是一句话：无法预测。
一般免费或付费shadowsocks站都会提供多个不同vps的节点供你选择切换。

5. 桌面右下角 任务栏 右键ss图标 选择 启用系统代理。
   系统代理模式 根据自己需要选择pac或全局代理 ，一般建议pac
6. 打开IE浏览器，访问https://www.youtube.com/

其他浏览器的shadowsocks代理设置参考上面的教程链接或下面的说明
网上找了几个客户端的使用教程 供参考
+ http://www.awolau.com/shadowsocks/shadowsocks-win7-xp.html
+ http://cnwall.tk/useage-muti-plat-shadowsocks/
+ https://cnlic.com/?paged=2

如果使用Shadowsocks，请清除或还原以前修改过的hosts文件，也请务必关闭其
他占用1080等端口的代理、翻墙软件

* 付费的shadowsocks节点
提供商鱼龙混杂，没个统一的流量和收费标准
确需购买，建议多比较几家的节点和流量
能提供试用当然最好，有月付，季付尽量不要选择年付。
现在基本所有的shadowsocks站都提供收费服务
以下链接是一部分提供收费服务的shadowsocks商家
非广告，非推广，来源网络，仅供参考

shadowsocks各种版本及教程:

+ www.wegotofqss.info
+ www.wegotofqss.info

+ https://www.fyzhuji.com/shadow.html
+ https://www.start-ss.biz/
+ https://www.deepss.org/index.php
+ http://my.ssjsq.net/
+ http://playss.co/
+ http://www.qiushiss.com/cart.php
+ https://www.bluecloud.pw/
+ http://www.hishadowsocks.com/
+ https://my.ssh91.net/
+ http://www.pgfastss.org/order.php
+ http://my.ssh91.net/cart.php
+ http://www.pgfastss.com/index.php
+ http://blog.onlybird.com/收费ssh代理
+ http://itti.xyz/
+ https://www.ezlink.hk/order
+ https://vnet.link/ 微林（中转）

*注意*：Shadowsocks.com不是shadowsocks官网，就是一个纯提供商业服务的网
站，所售服务和其他shadowsocks商业站一样。

公开的shadowsocks线路极易遭到恶意流量消耗和DDoS攻击或恶意破解ssh
现在明码公开的免费线路，网上论坛和v2ex 还有G+ twitter几乎已经没有了，
你可以试着自己搜一下 http://t.cn/RLTGXfn或http://t.cn/RLTGoxm

* 获取shadowsocks节点的几种方式
1. 抢码获取免费流量 免费或免费+收费的shadowsocks站，现在注册码都由站长
   或管理员严格控制发放了。肉少狼多，现在抢码有难度
2. 自己买vps搭建。 安全，流量独享。缺点;节点单一，速度如何没保证，靠人品值。
3. 买现成的ss服务商提供的服务

缺点：一般都有流量限制。
没有有效节点，想免费体验一把的只能自己想其他办法了。

+ http://www.hishadowsocks.com/ 4小时更新一次密码
+ http://www.ishadowsocks.com/ 6小时更新一次密码
+ http://www.surperoneblog.com/shadowsocks.php 6小时更新一次密码
+ http://sscat.cc/free/ 3小时更新一次密码
+ http://kf0.cc/ 4小时更新一次密码
+ https://www.ezlink.hk/free.php 密码每天0点更新
+ http://freehide.co.uk/free-shadowsocks/
+ https://namaho.com 半个月更换一次密码 不限速不限量不收费不负责
+ http://www.htovpn.net/?View=FreeSS 3小时更新一次密码 需要注册
+ http://sskuai.pw/
+ https://plus.google.com/communities/104092405342699579599 shadowsocks免费帐号
+ https://plus.google.com/communities/109962494203239446911
+ https://plus.google.com/+GhostAssassin/posts/NrDZWoXVjSD 免费shadowsocks大集合
+ http://www.fyhqy.com/356/
+ http://yyf.sg/code 免费shadowsocks邀请码集合站
+ QQ搜群 shadowsocks 有的shadowsocks qq群有免费ss线路或内部放邀请码
+ 以上链接或链接中的免费shadowsocks随时可能失效，这个就没啥好解释的了。
  有问题，自己随时google解决。

+ 1个shadowsocks讨论圈
  https://plus.google.com/s/shadowsocks

提醒一下
如非确实必要，尽量不要用shadowsocks全局
可以通过软件自带pac或浏览器安装代理管理扩展，实现智能分流
如何修改shadowsocks pac文件
http://www.awolau.com/shadowsocks/start-pac.html

实现科学上网时，启用系统代理后，Shadowsocks客户端会自动配置一个IE代理，使用本地127.0.0.1:1080，默认会选择PAC模式。关于PAC，大家可以参考维基百科。
选择PAC模式后，系统会根据PAC配置文件pac.txt(与Shadowsocks.exe同级目录)，
当你的浏览器访问这个配置文件里面配置的URL时，会使用代理，否则则不会使用代理。
这样既节省ss流量，也会提高国内网站的访问速度，这个很不错。
最后，如果大家发现有什么网站被Qiang了，可以在pac.txt这个文件里面添加这
个网站URL，即可通过ss的代理来访问了。同时，最好也定期从GFWList更新PAC。

* 如何制作便携版shadowsocks
下载2.5.6版（clowwindy）shadowsocks（只有高于这版的才支持制作便携版）
在 shadowsocks.exe 所在目录创建一个 shadowsocks_portable_mode.txt 文件
退出程序，重启程序
https://github.com/shadowsocks/shadowsocks-windows/releases

源码下架，可以自行寻找
注：SSR版貌似不支持此项功能

* shadowsocks俗称 纸飞机
ShadowSocks是Clowwindy开发的，一个轻量级的几乎跨平台的开源翻墙应用。
Shadowsocks 是一个安全的socks5代理，由于服务端与终端都简便易用，
目前配合VPS主机后十分稳定，已慢慢取代GAE等成为主流代理工具。

* Shadowsocks功能特性：
1. 高性能：基于异步 I/O，事件驱动的程序实现；专为大并发、大流量的应用
   场景优化；无需保持连接状态，适用于移动设备及无线网络。

2. 低资源占用：完全以原生代码实现，后台服务内存占用不超过10MB。
3. 跨平台：可以在PC、MAC、智能手机（iPhone与Android）、甚至路由器（OpenWRT）中运行。
4. 安全：支持多种加密方案及多种加密强度，提供系统级别的网络数据加密。
5. 开源：由社区维护的开源项目，包括GPL及MIT两种协议的多种实现。

有必要先说明一下，用shadowsocks科学上网不是"免费"的。
shadowsocks软件是免费的,但必须要有架设好的服务器线路才能实现无障碍的“科学上网”。
架设shadowsocks需要自己购买vps，在服务器端搭建，或买别人搭建好出售流量的线路。
网上有免费分享的shadowsocks线路，这种是可以免费使用的。

shadowsocks官方信息
+ http://shadowsocks.org/en/download/clients.html
shadowsocks官网
+ http://shadowsocks.org/en/index.html
shadowsocks作者
+ https://www.v2ex.com/member/clowwindy
shadowsocks官方 pac
+ https://github.com/clowwindy/gfwlist2pac
shadowsocks官方的2种pac模式（无法更新了）
fast mode pac
+ https://raw.githubusercontent.com/clowwindy/gfwlist2pac/master/test/proxy.pac
precise mode pac
+ https://raw.githubusercontent.com/clowwindy/gfwlist2pac/master/test/proxy_abp.pac
  一个shadowsocks可用的可更新的pac
+ https://raw.githubusercontent.com/KyonLi/ss-pac/master/ss.pac

shadowsocks客户端官网下载页面
+ http://shadowsocks.org/en/download/clients.html
Windows系统shadowsocks旧版及MAC电脑客户端shadowsocks官方下载页面
+ http://sourceforge.net/projects/shadowsocksgui/files/dist/
github的下载链接(最新版)
+ https://github.com/shadowsocks/shadowsocks-windows/releases


低于2.5.2的旧版Shadowsocks-win-x.x.x.zip和Shadowsocks-win-dotnet4.0-x.x.x.zip的区别
For >= Windows 8 or with .Net 4.0, download Shadowsocks-win-dotnet4.0-x.x.x.zip.
For <= Windows 7 or with .Net 2.0, download Shadowsocks-win-x.x.x.zip.

** 注意：
NET 2.0不能在Windows10良好运行，
从2.5.2这个版本开始，我们不再支持.NET 2.0。最低要求 .Net 4.0
现在Shadowsocks-win-2.5.2.zip和Shadowsocks-win-dotnet4.0-2.5.2.zip是完全相同的文件。
如果您使用的是Windows XP或7，请安装.NET 4.0或更高版本。
负载均衡：就是多个连接分摊到各个服务器 随机选择服务器
高可用：按最低延迟+最稳定的标准（丢包率）自动选择一个服务器进行连接
累计丢包率：通过定时 ping 来测速和选择。如果要使用本功能，请打开菜单里
的统计可用性

+ shadowsocks作者关于windows2.0客户端功能性的说明
  http://www.chinagfw.org/2014/11/shadowsocks-for-windows-20.html
+ http://vc2tea.com/whats-shadowsocks/ 写给非专业人士看的 Shadowsocks 简介
+ https://blog.linuxeye.com/423.html Shadowsocks原理

** 安卓客户端-影梭的官网下载页面
+ https://play.google.com/store/apps/details?id=com.github.shadowsocks
+ https://github.com/shadowsocks/shadowsocks-android/releases

安卓未root，也可以使用shadowsocks

安卓版教程 http://51.ruyo.net/p/412.html
设置要点：路由-绕过局域网及中国大陆地址，全局代理-勾选“设置系统代理”。
设置完成后，点击右上角的开关，即可开启Shadowsocks代理
有特殊原因还在坚守fqrouter2的，可以添加自己的shadowsocks线路，添加后
fqrouter可满血复活

* shadowsockR
+ shadowsocks-rss版下载链接
+ shadowsockR就是第三方shadowsocks编译版（群共享的神奇海螺版shadowsocks-SSR）
+ shadowsockR官方链接：+ https://github.com/breakwa11/shadowsocks-rss
+ ShadowsocksR 服务端安装教程
+ https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup
+ https://plus.google.com/u/0/+MikotoMisakamm
+ https://plus.google.com/u/0/118234153777431449917/posts
  使用第三方shadowsocks编译版前，请务必仔细阅读shadowsockR主页的参数解
  释和说明

* 路由器端shadowsocks教程
+ https://cokebar.info/
+ https://php-rmcr7.rhcloud.com/openwrt-fq/
+ http://hong.im/2014/03/16/configure-an-openwrt-based-router-to-use-shadowsocks-and-redirect-foreign-traffic/

具体哪些型号的路由器支持shadowsocks?
想自己动手的，淘宝搜 openWRT,QQ搜 群openWRT

* iOS端 shadowsocks客户端教程

iOS使用shadowsocks的前提条件是必须越狱！越狱！越狱！
+ http://www.pgssh.com/ios-shadowsocks.html
未越狱的话，ss客户端仅相当于一个内置浏览器，无法代理其他应用。
直接在appstore搜索 Shadowsocks，下载地址：
+ http://itunes.apple.com/us/app/shadowsocks/id665729974?ls=1&mt=8
iOS 越狱了的话，可以代理其他应用端。越狱的直接在 Cydia 里搜索 Shadowsocks ，然后安装。
+ http://jas0n.me/2014/11/12/up_14_11_12/
未越狱的iOS端建议使用anyconnectvpn或最近的神器Surge
+ http://www.cellsystech.com/docs/%E5%85%8D%E8%B4%B9%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%BF%A1%E6%81%AF%E5%8F%8A%E5%8D%8F%E8%AE%AE/


关于Surge
已经提交apple,在AppStore上架
+ http://t.co/TF1WvOgq1c Surge AppStore 购买前说明。
购买直达链接： 
+ http://itunes.apple.com/cn/app/surge-web-developer-tool-proxy/id1040100637?ls=1&mt=8

Surge 新手使用指南
+ http://medium.com/@scomper/surge-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-a1533c10e80b
如何配置surge在ios中使用shadowsocks科学上网
+ http://ideafoc.us/2015/10/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AEsurge%E5%9C%A8ios%E4%B8%AD%E4%BD%BF%E7%94%A8shadowsocks%E7%A7%91%E5%AD%A6%E4%B8%8A%E7%BD%91/
+ http://surge.run/
+ http://gist.github.com/soffchen/05bc0f017a10486eb646
+ http://twitter.com/Blankwonder
+ http://plus.google.com/+LeoLiu/posts/GPvHQ7uj2iv
+ http://www.pgyer.com/b7c37752060a55ceeae89159d6cedd52
Surge可以去twitter上找作者要测试版
需要 OS X 10.10 / iOS 9.0 以上版本

* shadowsocks客户端参数简单说明
#+begin_src sh
"server"， 服务器名称 一般填写域名或ip
"server_port"， 服务端监听端口 填写ss提供者给你的服务器端口
"local_address"， 本地中转地址 通常为 127.0.0.1
"password"， 接入服务端密码
"method"， 加密方式 通常为 aes-256-cfb或rc4-md5
"local_port"， 本地监听端口， 默认为 1080 ，本地端口一般保持默认即可
"timeout"， 以秒为单位的连接超时时长
#+end_src


说明:ss://开头的地址是base64加密方式提供的shadowsocks线路，
解密方法：
复制ss:// 后面的字符串，解密后，就可以得到格式为method:password@IP:Port的服务器地址。
一个base64解密网站
http://tool.chinaz.com/Tools/Base64.aspx?jdfwkey=cvvmy


注意：

+ 切记遵守vps所在国法律，勿做违法或法律禁止事宜。
+ 千万不要挂shadowsocks使用p2p BT下载。
+ 因为美国的vps需要遵从美国的DMCA版权法律，如果该vps被用于bt下载，
+ 使用的vps的ip就会被记录下来。VPS商家就会封号，vps就会被停止服务。
+ 如果不想失去这个翻墙手段，最好不要翻墙的时候用p2p。

* 自己部署shadowsocks服务器端的教程
以下为vps端自己部署shadowsocks服务器端的教程，不是自己部署的就略过
大流量或重度用户建议自己搭建或购买适合自己流量,价位的shadowsocks服务
对个人隐私和安全性比较重视的，就自己部署shadowsocks服务器端吧
网上搭建和优化教程很多，自己动手搜一下。以下几个链接供参考
官网教程
+ https://github.com/shadowsocks/shadowsocks/wiki

网上搜集的一部分教程 打不开的链接挂代理访问
+ http://vbird.dic.ksu.edu.tw/
+ http://shadowsocks.blogspot.com/2015/01/shadowsocks.html
+ http://www.dothinking.cn/ruan-jian-jing-pin-wu/shadowsocks-vps.html
+ https://plus.google.com/103234343779069345365/posts/Xce4EJpLGhX
+ http://shadowsocks.blogspot.com/2015/01/shadowsocks.html
+ http://ju.outofmemory.cn/entry/114637
+ http://www.abclite.org/602
+ http://teddysun.com/399.html
+ https://php-rmcr7.rhcloud.com/shadowsocks-server/
+ http://www.fanyue.info/2015/02/shadowsocks.html 搬瓦工一键shadowsocks教程
+ http://jannerchang.tumblr.com/post/114392917710/4-23
+ http://www.cmsky.com/shadowsocks-manyuser-udp/ Shadowsocks-Manyuser开启UDP支持
+ http://www.cmsky.com/serverspeeder-install/ 安装锐速为网络加速
+ https://blog.linuxeye.com/423.html Shadowsocks一键安装脚本
+ https://blog.linuxeye.com/426.html ShadowSocks多用户管理系统搭建（moeSS+manyuser）
+ http://cnwall.tk/bandwagonhost-one-key-install-shadowsocks/
+ http://www.tennfy.com/3334.html
+ http://www.tennfy.com/2022.html
+ http://capbone.com/shadowsocks/
+ http://www.tennfy.com/2843.html
+ http://www.tennfy.com/2148.html
** iOS端搭建anyconnect教程
+ https://plus.google.com/+McGhostGao/posts/Z4gJrZsiRyp
+ http://lifehacker.io/post/108708838206/cisco-anyconnect-shadowsocks
+ http://ifreedomlife.com/2015/04/20/Setup-Cisco-AnyConnect-VPN-on-CentOS7/
+ http://jannerchang.tumblr.com/post/108814743720/centos7-strongswan-ios-vpn
+ http://goo.gl/WRW8ns
+ http://www.cmsky.com/anyconnect/

* 关于VPS（虚拟专用服务器）的基础知识
+ http://cnwall.tk/about-vps/
+ https://www.v2ex.com/go/vps
+ http://cnwall.tk/about-vps-ssh-client/
+ http://www.vpser.net/vps-howto
+ http://since1989.org/digitalocean/vps-vpn-shadowsocks.html
+ https://www.appfordev.com/68.html

几个vps测评网站（排名不分先后）：
1. LEB: http://lowendbox.com/
2. 老左博客： http://www.laozuo.org/vps
3. 主机测评： http://www.zhujiceping.com/
4. freehao123: http://www.freehao123.com/category/vps-zhuji/
5. 年付vps： http://www.yrvps.com/
6. 赵荣部落： http://www.zrblog.net/?
7. VPS推荐网 http://vpsadd.com/
8. 主机博士 http://www.drpsafe.com/
9. 小夜博客 http://www.vpsmm.com/
10. v2ex https://www.v2ex.com/go/vps

* 以后翻墙的方向，重点就是去中心化
** fqrouter2作者:
为何有fqrouter？
因为当年GFW还是一个入侵检测系统，不是一个防火墙。
这就意味着可以利用很多入侵检测系统的漏洞来做无代理的翻墙，这是很有意思
的事情。

** 为何关闭fqrouter？
因为今年GFW已经正式升级为一道防火墙了，google的成千上万个ip被封。
这种行为相当于把部分国际互联网进行了物理层面的拔网线。
今后的翻墙只有资源的比拼了，对于这种索然无味的事情我就不在这个上面浪费生命了。
那我怎么翻墙？（文字作者）
找渠道买shadowsocks帐号。这种零散的基于交易的行为是去中心化的，长期的，
有生命力的。


** shadowsocks 作者clowwindy:
从实际情况上来看，Shadowsocks 没有办法离开去中心化的服务器。要么自己花钱买 VPS，
要么用有人分享的账号，要么用有人提供的付费服务，他们各有所长，适合不同的人。

+ http://www.solidot.org/story?sid=45231

** ShadowsocksBackup
+ https://github.com/Long-live-shadowsocks
+ https://github.com/ShadowsocksBackup

* Shadowsocks Windows 官方使用说明
** 功能
+ 系统代理设置
+ PAC 模式和全局模式
+ GFWList 和用户规则
+ 支持 HTTP 代理
+ 支持多服务器切换
+ 支持 UDP 代理
** 下载
下载 最新版
https://github.com/shadowsocks/shadowsocks-windows/releases。

基本使用
在任务栏找到 Shadowsocks 图标
在 服务器 菜单添加多个服务器
选择 启用系统代理 来启用系统代理。请禁用浏览器里的代理插件，或把它们设置为使用系统代理。
除了设为系统代理，你也可以直接自己配置浏览器代理。在 SwitchyOmega 中把代理设置为 SOCKS5 或 HTTP 的 127.0.0.1:1080。这个 1080 端口可以在服务器设置中设置。
** PAC
可以编辑 PAC 文件来修改 PAC 设置。Shadowsocks 会监听文件变化，修改后会自动生效。
你也可以从 GFWList （由第三方维护）更新 PAC 文件。
你也可以使用在线 PAC URL
服务器自动切换
负载均衡：随机选择服务器
高可用：根据延迟和丢包率自动选择服务器
累计丢包率：通过定时 ping 来测速和选择。如果要使用本功能，请打开菜单里的统计可用性。
也可以实现 IStrategy 接口来自定义切换规则，然后给我们发一个 pull request。
** UDP
对于 UDP，请使用 SocksCap 或 ProxyCap 强制你想使用的程序走代理。
** 多实例
如果想使用其它工具如 SwitchyOmega 管理多个服务器，可以启动多个 Shadowsocks。 为了避免配置产生冲突，把 Shadowsocks 复制到一个新目录里，并给它设置一个新的本地端口。
另外在 SwitchyOmega 中需要使用 SOCKS5 代理，因为 HTTP 代理还是只会启动一个。

** 服务器配置
请访问 服务器
https://github.com/shadowsocks/shadowsocks/wiki/Ports-and-Clients#linux--server-side 获取更多信息。

** 绿色模式
如果你想把所有临时文件放在 shadowsocks/temp 目录而不是系统的 temp 目录， 可以在shadowsocks 所在目录创建一个 shadowsocks_portable_mode.txt 文件。
** 开发
Visual Studio 2015 is required.
授权
GPLv3

* 附1 shadowsocks如何实现类VPN代理:
+ Shadowsocks（Sock5代理）的PAC模式与全局模式与VPN的区别
  http://t.cn/Ry4wJ6x
+ 使用Proxifier把shadowsocks代理转为全局代理(类VPN)
  http://t.cn/Ry42ih9
+ Proxifier下载
  Proxifier 3.28 吕达嵘汉化注册版（安装即为注册版）
  http://www.hanzify.org/software/13717.html
+ Proxifier v3.28 破解版
  Initex.Software.Proxifier.v3.28.Standard.Edition.Incl.Keymaker-ZWT
  http://www89.zippyshare.com/v/5iEwpCKM/file.html
  Initex.Software.Proxifier.v3.28.Portable.Edition.Incl.Keymaker-ZWT
+ http://www12.zippyshare.com/v/BqNsbIiu/file.html
+ 本站系列教程： https://gochrome.info/tag/proxifier-series/

* 附2 shadowsocks如何代理本地游戏客户端或其他软件客户端：

shadowsocks如何代理本地游戏客户端或其他软件客户端

关于代理UDP（以TCP转发或UDP转发均可）
官方shadowsocks和第三方客户端shadowsocksR最新版，都支持配合使用SocksCap64/SocksCap/ProxyCap等工具，把需要TCP和UDP代理的程序通过本版本程序转发。即不需要折腾OpenWrt或路由器即可在PC上获得UDP转发的能力，是游戏玩家的福音
如果你是个人用户，可自行更新服务端或向你的ss站长提议更新后端。
如果你是站长，可从https://github.com/breakwa11/shadowsocks/tree/manyuser
获取最新的多用户分支代码，与原版本兼容。

1. 需要第三方软件SocksCap64/SocksCap/ProxyCap
2. 需要有支持udp转发的shadowsocks节点

+ SocksCap64教程（SocksCap/ProxyCap使用方法大同小异）
  http://www.cmsky.com/sockscap64-shadowsocks/
+ SocksCap64免费
  http://www.sockscap64.com/
+ Sockscap 免费
  http://www.socksproxychecker.com/sockscap.html
+ Sockscap汉化版
  http://www.hanzify.org/software/8898.html
+ Proxycap
  http://www.proxycap.com/download.html

破解
+ x86 http://www43.zippyshare.com/v/39892822/file.html
+ x64 http://www74.zippyshare.com/v/12710611/file.html

注意：Proxifier 不支持处理 UDP 流量，Proxifier是靠实现类vpn方式实现第三方应用代理

* 附3 chrome浏览器SwitchyOmega扩展如何添加shadowsocks的代理设置:
chrome浏览器SwitchyOmega扩展如何添加shadowsocks的代理设置？
1. 添加shadowsocks的浏览器全局模式

#+begin_src html
右键SwitchyOmega扩展图标
选项>>
新建情景模式>>
名称：shadowsocks 全局(名称随便填)>>
类型：选择：代理服务器>>
点击：创建>>
代理协议：一定选择SOCKS5 ，代理服务器 填写127.0.0.1 ，代理端口填写
1080
#+end_src

2. 添加shadowsocks的浏览器pac模式

#+begin_src html
新建情景模式>>
名称：shadowsocks pac(名称随便填)>>
类型：选择：pac情景模式>>
点击：创建>>
pac网址>>复制下面这个链接到pac网址一栏
https://raw.githubusercontent.com/KyonLi/ss-pac/master/ss.pac
点击：立即更新情景模式
shadowsocks官方有2种pac模式，用哪个或都添加这个随你便
fast mode pac（快速）和precise mode pac（精确）
#+end_src

3.添加shadowsocks的"自动切换"代理模式，
+begin_src html
有个步骤用纯文字表诉的话，略微有点困难，这里掠过。
需要的自己导入OmegaOptions.bak
群共享和网盘的OmegaOptions.bak (文件大小243KB那个)
包括shadowsocks"自动切换" "shadowsockspac"和"shadowsocks全局" 3种情景模式，导入即可
#+end_src


+ SwitchyOmega 商店下载链接
  https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif
+ SwitchyOmega官方备用下载地址
  https://github.com/FelisCatus/SwitchyOmega/releases
+ 附：原gfwlist项目迁移到 https://github.com/gfwlist/gfwlist
  https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

本站原创switchyomega配置文件
+ switchyomega自动切换版：https://gochrome.info/switchyomega-config/
+ switchyomega虚拟情景版：https://gochrome.info/switchyomega-virtual/

站长推荐使用虚拟情景模式（共内置了8套模式）
+ 火狐浏览器添加规则和chrome大同小异
+ Google 即将关闭 Google Code，原gfwlist项目主页
+ https://code.google.com/p/autoproxy-gfwlist/

* 附4 全球付Globalcash虚拟信用卡和paypal申请教程：
全球付Globalcash虚拟信用卡和paypal注册申请教程
+ http://www.cmsky.com/globalcash/
+ http://jingyan.baidu.com/article/e73e26c0e3913b24adb6a7a4.html

* 附5 什么是cn2?：
+ 中国电信下一代承载网络（国际流量走的cn2线路）
  http://www.chinatelecom.com.cn/gjywpd/gj-qqwl/
  https://www.netroby.com/view.php?id=3459
  http://baike.baidu.com/subview/2193652/2193652.htm
  http://cablemap.info/ Greg's Cable Map
+ CN2网络延迟和丢包监控:
  http://183.91.49.53/public/sla/slaPerformanceNew.html

如果你连不上服务器，请首先检查SS客户端配置是否正确：
服务器域名或ip ，服务器端口 ，密码 ，加密方式，检查上面四项，确认没有填错。
如果均正常，依然连不上的话，请尝试Ping下 服务器域名或ip,看是否通；
如果不通，一般是你的线路问题（电信、联通、地域、时间等相关，有可能是暂时性问题）。
但注意在少数情况下，不管你是否能Ping通，都跟是否能连上ss服务器无关。
最后说下，一般都不会是服务器的问题，也就是说最大的可能性是：1.客户端参数配置，2.浏览器代理设置。

Shadowsocks 为什么出现 500 Internal Privoxy Error
可能原因：
1. 客户端的服务器信息错误
2. 服务端未正常启动或线路问题（被墙？）
3. 如果有使用端口转发，有可能是转发线路问题

通俗点说
1. 客户端配置参数填错，或参数有变化,自己更新不及时
2. 服务器端挂了，或线路被墙 （可能性很小）
3. 使用端口转发的，联系你的服务商

可能有人会有觉得100多人同时在用一个服务器会非常慢，
但实际上这点用户数对服务器造成的压力并没你想像中的大。
根据过去的服务器监控数据来看，平时的带宽使用平均在12Mbps左右，
间中会有去到20Mbps的突发流量，可以说完全没有压力。
CPU使用率长期在10%以下。内存方面没做太多优化，保持在60%左右。
或者100人同时在看视频的话，带宽可能就真的有压力，但这种概率几乎不存在，
而且就算你家有100Mbps的宽带，服务器也有100Mbps的带宽，你也会受中间线路最小带宽路段的限制，想像下木桶短板原理，而且“网络”中还有很多你意想不到的情况和条件存在，所以用（总带宽/使用人数来）算每人得到的带宽这种方法实在不合理。


