#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: 上网
#+OPTIONS: num:nil H:2


+ Lantern：是一个软件，包括桌面版和移动版，暂时iOS版本还没有出来，软件
  利用了多种技术来访问被墙网站。也提供收费版，也是下载可用。
+ GoAgent：如果你是Mac用户，可以使用XX-net，对GoAgent进行了封装，后台
  利用Google App Engine的服务，Github网站有详细的使用说明，相对折腾一
  些。
+ [[https://github.com/XX-net/XX-Net/wiki/XXNET%E8%B6%85%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B][GoAgent/XX-net]]： 这个是多年以前折腾的方法，一直有效，关键在于是多配置
  几个你个人的GAE的APPID，看Youtube、Google、维基基本无障碍；对于以前
  未配置过的，稍微有一点折腾。此为第一备份方案；
+ Amazon AWS EC2搭建免费VPN服务器：每个用户有免费一年的试用期，可以搭
  建免费VPN服务。缺点是也比较折腾，速度一般。具体方法用『Amazon AWS
  EC2搭建免费VPN服务器』搜索。
+ [[https://vpnxx.net/?p=556][修改系统HOSTS]] ：所谓GFW更多的是对域名进行DNS污染从而屏蔽网站，配置
  HOSTS，可以直接通过IP访问网站，是一种更快捷的方式。网友LAOD 收集了一
  个比较全的HOSTS列表，可以方便的访问Google和维基等网站。
+ 还有各种免费的VPN、代理、shadowsocks等，但是都不太推荐，因为不稳定，
  会折腾的你心力交瘁的。

+ [[https://vpnxx.net/?cat=2][付费VPN]]： 最常规的方案，一般情况下几乎所有设备和应用都原生支持VPN。问
  题在于VPN的稳定性，以及需要经常性的切换通过 VPN 访问被墙网站和不通过
  VPN直接访问未被墙网站。尽管有配置路由表的分流方案，但是并不是很方便。
  好消息是也有一些 VPN 服务商在服务端提供了自动分流的方案，后面有更多的
  说明。
+ 付费Shadowsocks：使用Socks5代理方式，加密数据链接，只有支持socks5的
  应用才能使用，不过常用的个人服务包括浏览网页、视频服务等都是支持的。
+ 自建VPN、Shadowsocks服务：购买虚拟主机，自建服务，甚至再购买一个相对
  高端的路由器，[[https://softwaredownload.gitbooks.io/openwrt-fanqiang/content/ebook/03.0.html][刷一个OpenWrt系统，在路由器上直接配置好VPN]]或者
  Shadowsocks服务，在应用的时候只要连上路由器即可科学上网。推荐给企业
  用户或技术人士。
+ 浏览器收费插件：也有一些免费插件，但这类服务都有一个通用的问题，稳定
  性问题，另外只能用在浏览器场景。还有一些浏览器的代理工具插件，比如
  SwitchyOmega、switchproxy等，这些工具一般和vpn、Shadowsocks 等服务配
  合使用。
+ Heroku+goproxy搭建自己个人的翻墙姿势
