#+SETUPFILE: ~/.emacs.d/src/org-templates/level-2.org
#+TITLE: Programming documents
#+OPTIONS: num:nil

* http://herbert.the-little-red-haired-girl.org/en/compdocs/index.html
+ GNU Bison Reference Manual. (DVI) (Postscript).
+ Can't Happen or /* NOTREACHED */ or Real Programs Dump Core is a classic article on avoiding bugs when programming (in C) (PDF File)!
+ The CVS Documentation (HTML) (HTML tree in a tar archive).
+ Using and Porting GNU CC (DVI) (Postscript), the GNU C Preprozessor (DVI) (Postscript), both (HTML trees in a tar archive).
+ GNU C Reference Card (DVI) (Postscript).
+ GDB Reference Card (DVI) (Postscript).
+ Debugging with the GNU Debugger (DVI) (Postscript) (HTML tree in a tar archive).
+ The GNU C Library Reference Manual (DVI) (Postscript) (HTML tree in a tar archive).
+ User's Guide to the GNU C++ Library (DVI) (Postscript).
+ lclint, a C Source Code Checker (HTML) (HTML tree in a tar archive). The (longish) one file version is useful for searching the documentation.
+ GNU make (DVI) (Postscript) (HTML tree in a tar archive).
+ The GNU Coding Standards (DVI) (Postscript) (HTML tree in a tar archive).

+ The JavaTM 2 Platform, Standard Edition, v1.2.2 API Specification (the
main page contains further links).


+ The GNU tar Documentation (HTML) (HTML tree as tar archive).
+ The Texinfo Documentation (DVI) (Postscript) (HTML tree as tar
archive).



* http://www.faqs.org
